// QCM du cahier CCA (FSJES Aïn Chock), classés par partie.
// conf : S = réponse sûre, P = probable, V = à vérifier, E = entraînement (rédigé par SaadConcours).
// Sources : uniquement les sujets du Master CCA d'Aïn Chock. QCM des sessions 2024 et 2022 (formation
// continue), reconstitution non officielle 2022/23, et exercices des épreuves rédigées 2017-2020 et des
// deux sujets non datés, mis en QCM (« mis en QCM » : énoncé du sujet, propositions de SaadConcours).
// Les QCM conf "E" (entraînement SaadConcours) sont exclus du PDF par build.mjs (AVEC_ENTRAINEMENT).
const R = String.raw;
const Q24 = (n) => `CCA 2024 · Q${n}`;
const FC = (n) => `CCA 2022 (formation continue) · Q${n}`;
const REC = (n) => `CCA 2022/23 (reconstitution) · Q${n}`;
const ADA = (s) => `CCA ${s} · mis en QCM`;
const ENT = "Entraînement SaadConcours (hors annales)";

export const QCM = {
  // ───────────────────────── Partie 1 · Comptabilité générale et approfondie
  1: [
    { key: "R17", src: REC(1), conf: "S", q: "Les charges et les produits constatés d'avance, ainsi que les charges à payer et les produits à recevoir, sont enregistrés en application du principe de :",
      o: { A: "spécialisation des exercices", B: "prudence", C: "continuité d'exploitation", D: "importance significative" },
      ok: "A", ex: "Les écritures de régularisation rattachent chaque charge et chaque produit à l'exercice qu'il concerne, quelle que soit la date du paiement : c'est la spécialisation (ou indépendance) des exercices." },
    { src: ADA("2020 (formation continue) et non daté 2"), conf: "S", q: "Le principe du coût historique signifie que :",
      o: { A: "les biens restent inscrits à leur valeur d'entrée, quelle que soit l'évolution de leur valeur de marché", B: "les biens sont réévalués chaque année à leur valeur de marché", C: "les biens sont évalués à leur prix de vente probable", D: "les biens sont évalués à leur coût de remplacement" },
      ok: "A", ex: "Valeur d'entrée : coût d'acquisition, coût de production ou valeur actuelle pour un apport. Elle ne bouge plus ensuite. Une baisse de valeur passe par un amortissement ou une provision (prudence) ; une hausse n'est jamais constatée, sauf réévaluation légale. Question de cours posée en 2020 et dans le sujet non daté 2." },
    { src: ADA("2017 et 2019 (formation initiale)"), conf: "S", q: "L'état des soldes de gestion (ESG) du modèle normal comprend :",
      o: { A: "le tableau de formation des résultats (TFR) et le tableau de la capacité d'autofinancement", B: "le bilan et le compte de produits et charges", C: "le TFR et le tableau de financement", D: "l'ETIC et le tableau de financement" },
      ok: "A", ex: "L'ESG regroupe le TFR (marge brute, valeur ajoutée, EBE, résultats intermédiaires) et le tableau de la CAF et de l'autofinancement. Les états de synthèse du CGNC sont cinq : bilan, CPC, ESG, tableau de financement, ETIC." },
    { src: REC(2), conf: "S", q: "À la date d'inventaire, des fournitures de bureau enregistrées dans un compte d'achats non stockés ne sont pas encore consommées. La régularisation consiste à constater :",
      o: { A: "des charges à payer", B: "des charges constatées d'avance", C: "des produits à recevoir", D: "des produits constatés d'avance" },
      ok: "B", ex: "La partie non consommée ne concerne pas l'exercice : on la sort des charges (débit 3491 « Charges constatées d'avance », crédit 6125). Elle sera reprise en charge au début de l'exercice suivant." },
    { src: Q24(3), conf: "S", q: "Lors d'une remise d'un effet de commerce à l'encaissement :",
      o: { A: "le bénéficiaire ne passe aucune écriture comptable", B: "la banque crédite le remettant sans attendre l'échéance", C: "la commission prélevée par la banque est soumise à la TVA" },
      ok: "C", ex: "A est faux : le remettant débite 5113 « Effets à encaisser ou à l'encaissement » par le crédit de 3425. B décrit l'escompte, pas l'encaissement : la banque ne crédite qu'après l'échéance. Les commissions bancaires sont soumises à la TVA (10 %)." },
    { src: Q24(1), conf: "S", q: "La différence entre le prix de consignation des emballages (300 DH) et leur prix de reprise (250 DH) constitue pour le fournisseur :",
      o: { A: "une charge soumise à la TVA", B: "un mali sur emballages", C: "un produit soumis à la TVA" },
      ok: "C", ex: "Le fournisseur garde 50 DH : c'est un boni sur reprise d'emballages, produit accessoire soumis à la TVA. Le mali (B) est la perte du client." },
    { src: Q24(2), conf: "P", q: "Le 01/10, le fournisseur « AGRO BIO » adresse à son client « MINI MARKET » la facture n° 110 pour 400 boîtes non restituées, consignées 30 DH l'unité. Chez le fournisseur, l'enregistrement consiste à :",
      o: { A: "débiter le compte 3421 « Clients » de 12 000", B: "créditer le compte 7127 « Ventes de produits accessoires » de 10 000", C: "créditer le compte 4455 « État, TVA facturée » de 2 000" },
      ok: "BC", ex: R`En lisant les 30 DH comme un prix TTC : $400 \times 30 = 12\,000$ TTC, soit 10 000 HT et 2 000 de TVA. On débite 4425 « Clients, dettes pour emballages et matériel consignés » (la consignation est déjà inscrite), pas 3421. Si le prix de 30 DH était HT, la vente serait de 12 000 HT et B deviendrait faux : c'est pourquoi la réponse est « probable ».` },
    { src: Q24(5), conf: "P", q: "Les frais de constitution représentent :",
      o: { A: "un actif fictif", B: "une charge", C: "un actif réel" },
      ok: "AB", ex: "Par nature, ce sont des charges. On les inscrit à l'actif (2111, immobilisations en non-valeurs) pour les étaler sur 5 ans au plus : un actif fictif, sans valeur de revente, que l'analyse financière élimine. Selon les IFRS, ils restent en charges." },
    { src: REC(4), conf: "P", q: "Pour une machine, l'entreprise a engagé : prix HT 450 000 ; transport 2 400 TTC ; installation 6 000 HT ; essai et mise au point 4 200 HT ; formation du personnel 18 000 HT. TVA de 20 % récupérable. La valeur d'entrée selon le CGNC est de :",
      o: { A: "450 000 DH", B: "458 000 DH", C: "476 000 DH", D: "480 200 DH" },
      ok: "B", ex: R`$450\,000 + 2\,400/1{,}2 + 6\,000 = 458\,000$. La formation n'est jamais un élément du coût. Avec les frais d'essai, on obtiendrait 462 200, absent des options : ici, le sujet les traite comme exclus. Lis toujours les options avant de trancher.` },
    { src: Q24(9), conf: "P", q: "Le 20/1/N, une entreprise a réglé par chèque les frais liés à l'acquisition d'une immobilisation : droits d'enregistrement 20 000 ; légalisation 780 ; conservation foncière 4 600 ; honoraires du notaire 6 000. Ces frais :",
      o: { A: "peuvent faire partie du coût d'acquisition de l'immobilisation", B: "doivent figurer en immobilisations en non-valeurs", C: "doivent être enregistrés en charges" },
      ok: "A", ex: "Ces frais d'acquisition (31 380 DH) peuvent, au choix de l'entreprise, être incorporés au coût ou étalés au compte 2121 « Frais d'acquisition des immobilisations ». B et C sont fausses à cause de « doivent ». Un document de correction qui circule retient B : c'est un traitement possible, pas une obligation." },
    { src: ADA("2019"), conf: "P", q: "Matériel industriel : net commercial 931 000 (après remise), escompte de règlement 2 % : 18 620, transport 6 400 HT, installation 5 240 HT. Un ingénieur-conseil consulté pour choisir le matériel a facturé 3 000 HT. Le coût d'acquisition est de :",
      o: { A: "924 020", B: "942 640", C: "945 640", D: "1 127 060" },
      ok: "B", ex: R`$931\,000 + 6\,400 + 5\,240 = 942\,640$. L'escompte de règlement est un produit financier (7386 « Escomptes obtenus »), pas une réduction du coût : A le déduit. Les honoraires de choix, engagés avant la décision d'achat, vont en charges : C les ajoute. D est le total TTC des factures.` },
    { key: "R3", src: ADA("2019 (formation initiale)"), conf: "S", q: "Une machine est achetée 1 000 000 € HT ; transport 8 000 € ; frais de port MARSA MAROC 16 800 HT ; taxes d'entrée 271 400 ; TVA à l'importation 2 168 000. Cours du jour d'arrivée et de dédouanement : 10,84. Avant l'achat, le directeur technique est parti en mission choisir le fournisseur : 6 450 € (69 956,70 DH). Coût d'acquisition :",
      o: { A: "11 214 920", B: "11 284 876,70", C: "13 382 920", D: "10 926 720" },
      ok: "A", ex: R`$10\,840\,000 + 86\,720 + 16\,800 + 271\,400 = 11\,214\,920$. La mission de choix est une charge (6143) : B l'ajoute. La TVA à l'importation est récupérable : C l'ajoute. D oublie les frais de port et les taxes d'entrée.` },
    { src: FC(1), conf: "S", q: "Matériel importé pour usage interne : facture nette 83 980 € ; cours le jour de la réception 10,82, cours le jour du virement 10,85 ; quittance de douane : droits et taxes 47 250, TVA 181 732,72. Coût du matériel importé :",
      o: { A: "1 003 738,00 DH", B: "955 913,60 DH", C: "958 433,00 DH" },
      ok: "B", ex: R`$83\,980 \times 10{,}82 + 47\,250 = 908\,663{,}60 + 47\,250 = 955\,913{,}60$. C prend le cours du virement : l'écart de cours ultérieur est une perte de change, pas un élément du coût. La TVA à l'importation est récupérable.` },
    { src: FC(2), conf: "S", q: "Mêmes données. L'écriture d'acquisition du matériel importé est :",
      o: { A: "D 2332 : 955 913,60 ; D 3455 : 181 732,72 ; C 4481 : 1 137 646,32", B: "D 2332 : 955 913,60 ; D 3455 : 181 732,72 ; C 4481 : 908 663,60 ; C 4458 État Douane : 228 982,72", C: "D 2332 : 958 433,00 ; D 3455 : 181 732,72 ; C 1486 : 911 183,00 ; C 4459 État Douane : 228 982,72" },
      ok: "B", ex: "La dette envers le fournisseur étranger s'inscrit au cours de réception (908 663,60). La quittance (droits + TVA) est une dette distincte envers la douane. A mélange les deux tiers dans un seul compte ; C prend le cours du virement et le compte 1486, réservé aux dettes de plus d'un an." },
    { src: FC(3), conf: "S", q: "Mêmes données. Le virement au fournisseur étranger (commissions 1 120 HT, TVA 10 %) s'enregistre :",
      o: { A: "D 1486 : 911 183,60 ; D 6147 : 1 120 ; D 3455 : 112 ; C 7331 Gains de change : 2 519,40 ; C 5141 : 909 895,60", B: "D 4481 : 958 433,60 ; D 6147 : 1 120 ; D 3455 : 112 ; C 5141 : 959 665,60", C: "D 4481 : 908 663,60 ; D 6147 : 1 120 ; D 3455 : 112 ; D 6331 Pertes de change : 2 519,40 ; C 5141 : 912 414,00" },
      ok: "C", ex: R`L'euro a monté (10,82 → 10,85) : la société perd $83\,980 \times 0{,}03 = 2\,519{,}40$. Le total exact du crédit banque est 912 415 : le sujet a un dirham d'écart, C reste la bonne réponse. A constate un gain alors qu'on doit des devises qui s'apprécient.` },
    { key: "R1", src: REC(5), conf: "S", q: "Matériel reçu le 20/07/N : facture de 62 000 €, remise commerciale 5 % ; cours à la réception 10,65 ; cours au règlement 10,68 ; droits et taxes non récupérables 31 360 ; commission bancaire sur le virement 1 200 HT. Le coût d'acquisition est de :",
      o: { A: "658 645 DH", B: "627 285 DH", C: "752 742 DH", D: "664 917 DH" },
      ok: "A", ex: R`$62\,000 \times 95\,\% = 58\,900$ € ; $58\,900 \times 10{,}65 = 627\,285$ ; $+ 31\,360 = 658\,645$. La commission bancaire est une charge financière liée au règlement.` },
    { key: "R2", src: REC(6), conf: "S", q: "Mêmes données. Le montant du virement qui règle uniquement le fournisseur étranger, hors commission et taxes, est de :",
      o: { A: "658 645 DH", B: "630 372 DH", C: "627 285 DH", D: "629 052 DH" },
      ok: "D", ex: R`$58\,900 \times 10{,}68 = 629\,052$. La différence avec la dette inscrite (627 285) est une perte de change de 1 767 DH (compte 6331).` },
    { src: ADA("2018"), conf: "S", q: "La SA « MCCA » importe des ordinateurs pour les revendre : facture de 123 600 € convertie au cours du dédouanement (10,85), frais MARSA MAROC 2 880 HT, droits et taxes 67 053. L'achat s'enregistre au débit de :",
      o: { A: "2355 « Matériel informatique » pour 1 410 993", B: "6111 « Achats de marchandises » pour 1 410 993 (1 341 060 + 2 880 + 67 053)", C: "3111 « Marchandises » pour 1 341 060", D: "6111 pour 1 344 768, au cours du paiement" },
      ok: "B", ex: "Des biens achetés pour être revendus sont des marchandises : compte 6111, frais accessoires d'achat inclus. Seuls les ordinateurs prélevés ensuite pour un usage interne deviennent des immobilisations (2355). Le stock (3111) ne bouge qu'à l'inventaire." },
    { src: FC(4), conf: "S", q: "Facture de fournitures de bureau : total 12 220 ; escompte 2 % : 244,40 ; net financier 11 975,60 ; TVA 20 % : 2 395,12 ; total à payer 14 370,72. Écriture :",
      o: { A: "D 6125 : 12 220 ; D 3455 : 2 395,12 ; C 7386 Escomptes obtenus : 244,40 ; C 4411 : 14 370,72", B: "D 6125 : 11 975,60 ; D 3455 : 2 395,12 ; C 4411 : 14 370,72", C: "D 6125 : 12 220 ; D 3455 : 2 395,12 ; C 7336 : 244,40 ; C 4411 Dettes sur acquisitions d'immobilisations : 14 370,72" },
      ok: "A", ex: "L'escompte de règlement est un produit financier : on ne le compense pas avec l'achat (principe de non-compensation). B est équilibrée mais compense. C utilise un compte 7336 qui n'existe pas. La TVA est bien calculée sur le net financier." },
    { src: FC(5), conf: "V", q: "Deux voitures Renault DACIA (net commercial 177 600, TVA 35 520), affectées au DRH et au directeur commercial. Le coût comptabilisé pour les deux voitures de service est de :",
      o: { A: "177 600,00 DH", B: "231 120,00 DH", C: "183 993,60 DH" },
      ok: "B", ex: R`Voitures de tourisme : TVA non récupérable, donc coût TTC. Le calcul exact est $177\,600 \times 1{,}2 = 213\,120$. La facture du sujet affiche par erreur 231 120 (chiffres inversés) et la proposition B le reprend : c'est la réponse attendue, mais retiens 213 120.` },
    { src: FC(6), conf: "V", q: "Mêmes données. Voitures reçues le 02/09/N, amortissement linéaire 20 %. La dotation au 31/12/N est de :",
      o: { A: "46 224,00 DH", B: "15 408,00 DH", C: "11 840,00 DH" },
      ok: "B", ex: R`Avec le bon coût : $213\,120 \times 20\,\% \times 4/12 = 14\,208$. Avec le total erroné du sujet : $231\,120 \times 20\,\% \times 4/12 = 15\,408$ (B, cohérente avec la question précédente). A compte une année entière, C amortit le HT.` },
    { src: ADA("non daté 1"), conf: "S", q: "Une entreprise de textile reçoit la facture d'un camion : 562 600 HT (options comprises), TVA 112 520, frais d'immatriculation 8 500, vignette 4 500. Prorata de déduction : 100 %. Coût d'acquisition du camion :",
      o: { A: "571 100", B: "575 600", C: "683 620", D: "562 600" },
      ok: "A", ex: R`$562\,600 + 8\,500 = 571\,100$. La TVA d'un véhicule utilitaire est récupérable (C la garde). L'immatriculation est un frais accessoire nécessaire à la mise en service. La vignette est une taxe annuelle : charge (6167). B l'incorpore.` },
    { src: ADA("non daté 1"), conf: "S", q: "Même camion, mais l'entreprise est un assujetti partiel : prorata de N-1 = 78 %, prorata définitif de N = 72 %. Le coût d'entrée enregistré à l'acquisition est de :",
      o: { A: "571 100", B: "595 854,40", C: "602 605,60", D: "683 620" },
      ok: "B", ex: R`À l'achat, on déduit au prorata provisoire (celui de N-1) : $112\,520 \times 78\,\% = 87\,765{,}60$. La part non déductible, $24\,754{,}40$, entre dans le coût : $571\,100 + 24\,754{,}40 = 595\,854{,}40$. Au 31/12, la baisse du prorata (−6 points) entraîne un reversement de $6\,751{,}20$ : le coût devient 602 605,60 (C), mais pas à l'acquisition.` },
    { src: ADA("2017"), conf: "S", q: "La TVA supportée sur l'acquisition d'une machine s'élève à 1 413 600. Elle a été déduite au prorata provisoire de 72 %. Le prorata définitif de N s'établit à 81 %. Au 31/12/N :",
      o: { A: "complément de déduction de 127 224 DH", B: "reversement de 127 224 DH", C: "complément de déduction de 395 808 DH", D: "aucune régularisation" },
      ok: "A", ex: R`Le prorata monte de 9 points : $1\,413\,600 \times 9\,\% = 127\,224$ de TVA supplémentaire à déduire (débit 34551, crédit 2332, car cette TVA avait été incorporée au coût). 395 808 est la totalité de la TVA non déduite (28 %).` },
    { src: ADA("2020 (formation continue)"), conf: "S", q: "Quatre micro-ordinateurs (24 000 HT) sont acquis le 01/07/N et amortis en dégressif sur 4 ans. La dotation de N est de :",
      o: { A: "3 000", B: "4 500", C: "9 000", D: "6 000" },
      ok: "B", ex: R`Taux linéaire 25 %, coefficient 1,5 pour 3 ou 4 ans : 37,5 %. Prorata dès le 1er jour du mois d'acquisition : $24\,000 \times 37{,}5\,\% \times 6/12 = 4\,500$. A est le linéaire sur 6 mois, C une année pleine en dégressif.` },
    { src: ADA("2018"), conf: "S", q: "Du matériel informatique est amorti en dégressif sur une durée de 6 ans et 8 mois. Le taux dégressif est de :",
      o: { A: "22,5 %", B: "30 %", C: "45 %", D: "15 %" },
      ok: "C", ex: R`Taux linéaire : $1 / 6{,}667 = 15\,\%$. La durée dépasse 6 ans : coefficient 3, d'où 45 %. Coefficients : 1,5 (3 ou 4 ans), 2 (5 ou 6 ans), 3 (plus de 6 ans). Le « 8 mois » est là pour te faire basculer au coefficient 3.` },
    { src: ADA("2020 (formation continue)"), conf: "S", q: "Des frais d'acquisition d'immobilisations de 234 600 DH, engagés le 08/01/N-4, sont amortis au taux constant de 20 %. La dotation de l'exercice N est de :",
      o: { A: "46 920", B: "0 (totalement amortis fin N-1)", C: "23 460", D: "234 600" },
      ok: "A", ex: R`Les non-valeurs s'amortissent par annuités constantes sur 5 ans au plus, sans prorata temporis : N-4, N-3, N-2, N-1, N. L'exercice N porte la 5e et dernière annuité : $234\,600 \times 20\,\% = 46\,920$. Fin N, on les sort de l'actif.` },
    { src: REC(7), conf: "S", q: "Au cours de l'exercice N, l'entreprise a reçu une subvention d'investissement de 390 000 DH pour financer l'acquisition d'un terrain de 620 000 DH. Le contrat ne prévoit aucune clause d'inaliénabilité. Le montant de la reprise annuelle est de :",
      o: { A: "62 000 DH", B: "230 000 DH", C: "39 000 DH", D: "390 000 DH" },
      ok: "C", ex: "Le terrain ne s'amortit pas. Sans clause d'inaliénabilité, la subvention est reprise en dix fractions égales : 390 000 / 10 = 39 000. Avec une clause, elle serait reprise sur la durée d'inaliénabilité." },
    { src: REC(8), conf: "S", q: "Le 30/09/2021, une entreprise cède pour 130 000 DH une voiture de tourisme acquise et mise en service le 15/07/2019 pour 250 000 HT (TVA de 20 % non récupérable), amortie au taux linéaire de 20 %, prorata en mois (mois d'acquisition et de cession inclus). Le résultat de cession est :",
      o: { A: "une moins-value de 35 000 DH", B: "une moins-value de 7 500 DH", C: "une plus-value de 5 000 DH", D: "une plus-value de 130 000 DH" },
      ok: "A", ex: R`Coût TTC : 300 000. Amortissements : $30\,000\ (6\ \text{mois}) + 60\,000 + 45\,000\ (9\ \text{mois}) = 135\,000$. VNA : 165 000. Résultat : $130\,000 - 165\,000 = -35\,000$.` },
    { src: Q24(7), conf: "S", q: "Un atelier construit par l'entreprise a coûté 1 500 000 DH en 2022 (inscrits en immobilisations en cours à la clôture 2022) et 800 000 DH en 2023. L'écriture d'achèvement au 31/12/2023 (hors TVA) est :",
      o: { A: "D 2321 : 2 300 000 / C 2392 : 2 300 000", B: "D 2321 : 2 300 000 / C 2392 : 1 500 000 ; C 7143 Immobilisations corporelles produites : 800 000", C: "D 2392 : 800 000 / C 7143 : 800 000" },
      ok: "B", ex: "Les 1 500 000 de 2022 sont déjà en 2392 : on les solde. Les 800 000 de 2023 sont des charges de l'exercice, neutralisées par le produit 7143. A ignore la production de 2023, C ne transfère pas l'atelier achevé. Question d'écriture du sujet 2024, présentée ici en QCM. Les corrigés qui circulent ajoutent une livraison à soi-même imposable : D 34551 / C 4455 de 460 000." },
    { src: Q24(8), conf: "S", q: "Début janvier N-10, une entreprise a souscrit un crédit-bail immobilier (bâtiment de 2 700 000 DH, dépôt de garantie 500 000 DH). Elle lève l'option le 01/01/N pour 950 000 DH. Le bâtiment entre à l'actif pour :",
      o: { A: "2 700 000 DH", B: "950 000 DH", C: "3 650 000 DH", D: "450 000 DH" },
      ok: "B", ex: "En CGNC, le bien entre au prix de levée de l'option (D 2321 : 950 000). Les loyers déjà payés étaient des charges. Si le dépôt de garantie s'impute sur le prix, la banque ne paie que 450 000 (C 2486 : 500 000 ; C 5141 : 450 000). Question d'écriture du sujet 2024, présentée ici en QCM. En IFRS 16, le bien serait au bilan dès le début du contrat." },
    { src: REC(3), conf: "S", q: "Au 31/12/N, une créance de 45 000 €, enregistrée au cours de 10,68, vaut 10,45 à l'inventaire. Échéance : 15/03/N+1. Quel écart de conversion inscrire au bilan, indépendamment de la provision ?",
      o: { A: "Un écart de conversion passif de 10 350 DH", B: "Un écart de conversion actif de 10 350 DH", C: "Un écart de conversion actif de 1 035 DH", D: "Aucun écart avant le règlement" },
      ok: "B", ex: R`$45\,000 \times (10{,}68 - 10{,}45) = 10\,350$. La créance baisse : perte latente, écart de conversion actif (D 3701 / C 3421), couvert par une provision pour perte de change.` },
    { key: "R13", src: Q24(23), conf: "S", q: "Au 31/12/23 : créance de 65 000 €, cours d'entrée 10,68, cours d'inventaire 10,45, échéance 15/03/24. Le comptable doit constater :",
      o: { A: "une perte de change de 14 950 DH", B: "une dotation aux provisions de 14 950 DH", C: "un écart de conversion actif de 14 950 DH" },
      ok: "BC", ex: R`$65\,000 \times 0{,}23 = 14\,950$. Écart de conversion actif (D 3701 / C 3421) et provision pour perte de change (D 6393 / C 4506). La perte de change (A) ne sera constatée qu'au règlement. Même trame que la créance de 45 000 € de la reconstitution 2022/23.` },
    { src: Q24(24), conf: "V", q: "Matériel acquis le 01/09/2023 : 960 000 HT, TVA 20 %. 30 % payés comptant ; le reste en deux versements égaux indexés sur l'inflation (2,25 % retenus fin 2023). À la date d'inventaire 2023 :",
      o: { A: "on crédite 5141 « Banques » de 403 200", B: "on débite 1486 « Fournisseurs d'immobilisations » de 403 200", C: "on crédite 5141 « Banques » de 412 272" },
      ok: "BC", ex: R`Reste dû : $1\,152\,000 \times 70\,\% = 806\,400$, soit deux échéances de 403 200. Si la première tombe au 31/12/2023 (le sujet ne le dit pas), on débite la dette du nominal et on paie $403\,200 \times 1{,}0225 = 412\,272$ ; les 9 072 sont une charge financière. Sans échéance à cette date, aucun paiement : d'où « à vérifier ».` },
    { src: Q24("6-2"), conf: "P", q: "Le 20/02/2023, la société « MAF » cède un local commercial acquis le 10/02/2020. Pour la TVA à reverser, on crédite le compte :",
      o: { A: "4445 « État, TVA facturée »", B: "4456 « État, TVA due (suivant déclarations) »", C: "4457 « État, impôts et taxes à payer »" },
      ok: "B", ex: "La TVA reversée est une dette envers l'État, déclarée : 4456. A porte un numéro faux (la TVA facturée est au 4455). Le montant du reversement est calculé dans la partie Fiscalité (question sur les 90 000 DH)." },
  ],

  // ───────────────────────── Partie 2 · Comptabilité des sociétés
  2: [
    { key: "R14", src: Q24(16), conf: "S", q: "Exercice 2023 : bénéfice net 768 000 DH ; capital social 2 040 000 ; report à nouveau débiteur 48 000 ; réserve légale 188 400. La dotation à la réserve légale est de :",
      o: { A: "36 000 DH", B: "38 400 DH", C: "15 600 DH" },
      ok: "C", ex: R`$5\,\% \times (768\,000 - 48\,000) = 36\,000$, mais le plafond de 10 % du capital (204 000) est presque atteint : il manque $204\,000 - 188\,400 = 15\,600$.` },
    { src: REC(18), conf: "S", q: "Capital : 5 900 actions de 190 DH, soit 1 121 000 ; réserve légale déjà constituée 98 100 ; report à nouveau débiteur 60 000 ; bénéfice 380 000. La dotation à la réserve légale est de :",
      o: { A: "14 000 DH", B: "16 000 DH", C: "22 000 DH", D: "19 000 DH" },
      ok: "A", ex: R`Dotation théorique : $5\,\% \times (380\,000 - 60\,000) = 16\,000$. Plafond : $112\,100 - 98\,100 = 14\,000$. On retient 14 000. Comme dans le sujet 2024, le report débiteur s'impute avant le calcul.` },
    { src: Q24(18), conf: "P", q: "La valeur nominale de l'action d'une SA :",
      o: { A: "est librement fixée par les statuts", B: "ne doit pas être inférieure à 50 DH pour les SA non cotées", C: "ne doit pas être inférieure à 100 DH pour les SA non cotées" },
      ok: "B", ex: "Les statuts fixent le nominal, mais dans le respect du minimum légal de la loi 17-95 : 50 DH pour une SA non cotée. A est trop absolu." },
    { src: Q24(19), conf: "S", q: "Dans le cas d'une augmentation du capital, le prix d'émission peut être :",
      o: { A: "inférieur à la valeur nominale de l'action", B: "égal à la valeur nominale de l'action", C: "supérieur à la valeur nominale de l'action" },
      ok: "BC", ex: "Émission au pair (B) ou avec une prime d'émission (C). Une émission en dessous du nominal est interdite : elle créerait un capital fictif." },
    { src: Q24(20), conf: "S", q: "La SA « LIDOL » (capital 3 000 000 : 15 000 actions de 200 DH) émet 5 000 actions de numéraire, nominal 200, prix d'émission 250, libérées du minimum légal. Les fonds versés à la banque sont de :",
      o: { A: "250 000 DH", B: "312 500 DH", C: "500 000 DH" },
      ok: "C", ex: R`Minimum légal : le quart du nominal plus la totalité de la prime. $5\,000 \times (50 + 50) = 500\,000$. A oublie la prime ; B applique le quart au prix d'émission.` },
    { key: "R15", src: Q24(21), conf: "S", q: "Une SA constituée le 01/04/2020 au capital de 2 400 000 DH (12 000 actions : 9 000 de numéraire, 3 000 d'apport). Le dernier quart est libéré le 01/07/2022. Premier dividende de 4 %. Montant pour 2022 :",
      o: { A: "87 000 DH", B: "96 000 DH", C: "72 000 DH" },
      ok: "A", ex: R`Nominal 200. Apports : $3\,000 \times 200 \times 4\,\% = 24\,000$. Numéraire, 3/4 libérés : $9\,000 \times 200 \times 3/4 \times 4\,\% = 54\,000$. Dernier quart sur 6 mois : $9\,000 \times 50 \times 4\,\% \times 6/12 = 9\,000$. Total 87 000. B suppose tout libéré sur l'année.` },
    { src: Q24(22), conf: "V", q: "Le 01/04/2023, une SA appelle le 3e quart de son capital (14 000 actions de nominal 120). À la date limite, un actionnaire de 700 actions ne se libère pas, et 1 400 actions ont été libérées intégralement :",
      o: { A: "on crédite le compte 4468 « Autres comptes d'associés créditeurs » de 42 000", B: "on crédite le compte 3462 « Actionnaires, capital souscrit et appelé non versé » de 420 000", C: "on débite le compte 5141 « Banques » de 483 000" },
      ok: "A", ex: R`Appel : $14\,000 \times 30 = 420\,000$. Impayé : 21 000. Versements anticipés du 4e quart : $1\,400 \times 30 = 42\,000$, une dette envers les actionnaires (A). Banque : $420\,000 - 21\,000 + 42\,000 = 441\,000$ (C est faux). B n'est juste que si les 21 000 impayés sont reclassés en « actionnaires défaillants ».` },
    { src: REC(16), conf: "P", q: "Dans une SA, quelle condition relative aux frais de constitution doit être respectée avant toute distribution de bénéfices ?",
      o: { A: "Ils doivent être totalement amortis", B: "Ils doivent être amortis au moins pour moitié", C: "Ils doivent seulement être mentionnés dans l'ETIC", D: "Ils peuvent rester non amortis si la trésorerie est suffisante" },
      ok: "A", ex: "On ne distribue pas de bénéfice tant que l'actif contient des frais d'établissement non amortis : ce serait distribuer un capital fictif." },
    { src: REC(17), conf: "S", q: "Un associé met un immeuble à la disposition d'une société pour une durée déterminée, à titre d'apport, tout en conservant la propriété. Il s'agit d'un apport :",
      o: { A: "en pleine propriété", B: "en jouissance", C: "en numéraire", D: "en industrie" },
      ok: "B", ex: "La société reçoit l'usage temporaire du bien ; l'associé en reste propriétaire et le récupère au terme." },
    { src: REC(19), conf: "S", q: "Dans une SA, le premier dividende attribuable aux actions ordinaires est calculé sur :",
      o: { A: "le montant total du capital souscrit, libéré ou non", B: "le montant libéré et non remboursé du capital social", C: "le total des capitaux propres figurant au bilan", D: "le résultat net avant affectation à la réserve légale" },
      ok: "B", ex: "Le premier dividende (intérêt statutaire) rémunère les seules sommes libérées et non amorties du capital : voir la question du premier dividende de 87 000 DH." },
    { src: ENT, conf: "E", q: "Une SA de 10 000 actions, valeur réelle 300 DH, émet 2 000 actions nouvelles au prix de 240 DH. La valeur théorique du droit préférentiel de souscription est de :",
      o: { A: "60 DH", B: "10 DH", C: "50 DH", D: "12 DH" },
      ok: "B", ex: R`Valeur après émission : $\frac{10\,000 \times 300 + 2\,000 \times 240}{12\,000} = 290$. DPS $= 300 - 290 = 10$. A est l'écart brut entre valeur et prix d'émission, qu'il faut répartir sur toutes les actions.` },
    { src: ENT, conf: "E", q: "Une augmentation de capital par incorporation de réserves :",
      o: { A: "augmente les capitaux propres", B: "ne modifie pas le montant des capitaux propres", C: "fait entrer de la trésorerie", D: "diminue le capital" },
      ok: "B", ex: "Simple virement de compte à compte (D 1140 ou 1152 / C 1111) : la composition des capitaux propres change, pas leur total. Les actionnaires reçoivent des actions gratuites, et un droit d'attribution remplace le DPS." },
  ],

  // ───────────────────────── Partie 3 · Normes IFRS (aucune question dans les annales connues)
  3: [
    { src: ENT, conf: "E", q: "Les normes IFRS sont élaborées par :",
      o: { A: "l'IASB", B: "le FASB", C: "l'IFAC", D: "le Conseil national de la comptabilité" },
      ok: "A", ex: "L'IASB (International Accounting Standards Board) publie les IFRS et a repris les IAS de l'ancien IASC. Le FASB normalise aux États-Unis (US GAAP), l'IFAC regroupe la profession d'audit, le CNC marocain a élaboré le CGNC." },
    { src: ENT, conf: "E", q: "Dans le cadre conceptuel de l'IASB, les deux caractéristiques qualitatives fondamentales de l'information financière sont :",
      o: { A: "la prudence et la permanence des méthodes", B: "la pertinence et la représentation fidèle", C: "la comparabilité et la rapidité", D: "la régularité et la sincérité" },
      ok: "B", ex: "Pertinence et représentation fidèle sont fondamentales ; comparabilité, vérifiabilité, rapidité et compréhensibilité sont des caractéristiques auxiliaires. La régularité et la sincérité sont les termes du droit comptable marocain." },
    { src: ENT, conf: "E", q: "Lequel de ces documents ne fait pas partie des états financiers complets selon IAS 1 ?",
      o: { A: "Le tableau des flux de trésorerie", B: "L'état des variations des capitaux propres", C: "L'état des soldes de gestion", D: "Les notes annexes" },
      ok: "C", ex: "IAS 1 : état de la situation financière, état du résultat net et des autres éléments du résultat global, variations des capitaux propres, flux de trésorerie, notes. L'ESG est un état propre au CGNC." },
    { src: ENT, conf: "E", q: "Selon IAS 2, les stocks sont évalués :",
      o: { A: "au coût historique, sans dépréciation", B: "au plus faible du coût et de la valeur nette de réalisation", C: "à la juste valeur", D: "au coût de remplacement" },
      ok: "B", ex: "Valeur nette de réalisation : prix de vente estimé, moins les coûts d'achèvement et de commercialisation. Les méthodes de coût admises sont le FIFO et le coût moyen pondéré : le LIFO est interdit." },
    { src: ENT, conf: "E", q: "Selon IAS 16, après sa comptabilisation initiale, une immobilisation corporelle est évaluée :",
      o: { A: "obligatoirement au coût historique", B: "selon le modèle du coût ou le modèle de la réévaluation, appliqué à toute une catégorie d'actifs", C: "à la juste valeur, avec variations en résultat", D: "à sa valeur de revente" },
      ok: "B", ex: "Le modèle de la réévaluation porte les écarts positifs en capitaux propres (écart de réévaluation). Le CGNC ne connaît que le coût historique, sauf réévaluation légale." },
    { src: ENT, conf: "E", q: "Selon IAS 16, de grosses réparations prévues tous les 5 ans sur un équipement sont traitées :",
      o: { A: "par une provision pour grosses réparations", B: "comme un composant distinct, amorti sur sa propre durée", C: "en charges l'année de la dépense", D: "en capitaux propres" },
      ok: "B", ex: "Approche par composants : chaque élément significatif à durée d'utilité différente est amorti séparément. La provision pour grosses réparations, encore admise par le CGNC (voir la question de comptabilité analytique sur la charge étalée), n'existe pas en IFRS." },
    { src: ENT, conf: "E", q: "Selon IAS 38, les dépenses de recherche et de développement sont :",
      o: { A: "toutes immobilisées", B: "toutes en charges", C: "en charges pour la recherche ; immobilisées pour le développement si six critères sont remplis", D: "immobilisées pour la recherche ; en charges pour le développement" },
      ok: "C", ex: "Les six critères : faisabilité technique, intention d'achever, capacité d'utiliser ou de vendre, avantages économiques probables, ressources disponibles, évaluation fiable des dépenses." },
    { src: ENT, conf: "E", q: "En IFRS, les frais de constitution d'une société sont :",
      o: { A: "inscrits en immobilisations en non-valeurs", B: "comptabilisés en charges de l'exercice", C: "déduits du capital", D: "amortis sur 5 ans" },
      ok: "B", ex: "IAS 38 interdit d'activer les dépenses de démarrage et de constitution. C'est une différence nette avec le CGNC, qui les inscrit au compte 2111 (voir la question 5 du sujet 2024, en partie 1)." },
    { src: ENT, conf: "E", q: "Selon IFRS 16, chez le preneur, un contrat de location de 5 ans portant sur un bâtiment donne lieu à :",
      o: { A: "des loyers en charges, sans inscription au bilan", B: "un droit d'utilisation à l'actif et une dette locative au passif", C: "une simple mention dans les notes", D: "une provision pour loyers futurs" },
      ok: "B", ex: "Seules les locations de 12 mois au plus et celles de faible valeur peuvent rester hors bilan. En CGNC, le crédit-bail reste hors bilan : redevances en charges (6132), le bien n'entre à l'actif qu'à la levée d'option." },
    { src: ENT, conf: "E", q: "Selon IAS 37, une provision est comptabilisée si :",
      o: { A: "l'entreprise prévoit des pertes d'exploitation futures", B: "il existe une obligation actuelle résultant d'un événement passé, une sortie de ressources probable et une estimation fiable", C: "la direction décide de constituer une réserve de précaution", D: "un risque est simplement possible" },
      ok: "B", ex: "Les trois conditions sont cumulatives. Pas de provision pour pertes opérationnelles futures. Un risque seulement possible donne lieu à une information en annexe (passif éventuel)." },
    { src: ENT, conf: "E", q: "Selon IAS 21, à la clôture, la perte de change latente sur une créance client en devises est :",
      o: { A: "inscrite en écart de conversion actif et provisionnée", B: "comptabilisée en résultat de l'exercice", C: "ignorée jusqu'au règlement", D: "portée en capitaux propres" },
      ok: "B", ex: "En IFRS, les éléments monétaires sont convertis au cours de clôture, et l'écart (perte ou gain latent) passe en résultat. Le CGNC passe par l'écart de conversion actif et la provision pour perte de change, et ne constate pas le gain latent." },
    { src: ENT, conf: "E", q: "Selon IAS 20, une subvention liée à un actif est présentée :",
      o: { A: "en capitaux propres, comme dans le CGNC", B: "en produit différé, ou en déduction de la valeur comptable de l'actif", C: "en produit de l'exercice d'encaissement", D: "en dette financière" },
      ok: "B", ex: "IAS 20 interdit l'inscription directe en capitaux propres. Le CGNC inscrit la subvention en capitaux propres assimilés (1311), puis la reprend au rythme des amortissements (ou en dix ans pour un terrain sans clause, voir la partie 1)." },
    { src: ENT, conf: "E", q: "Une machine a une valeur comptable de 500 000 DH. Sa juste valeur diminuée des coûts de sortie est de 420 000 DH, et sa valeur d'utilité de 450 000 DH. Selon IAS 36, la perte de valeur est de :",
      o: { A: "80 000 DH", B: "50 000 DH", C: "0 DH", D: "30 000 DH" },
      ok: "B", ex: R`Valeur recouvrable $= \max(420\,000 ; 450\,000) = 450\,000$. Perte $= 500\,000 - 450\,000 = 50\,000$. A retient le minimum.` },
    { src: ENT, conf: "E", q: "Selon IAS 8, un changement de méthode comptable s'applique :",
      o: { A: "de façon prospective, sur les exercices futurs seulement", B: "de façon rétrospective, en retraitant les exercices antérieurs présentés", C: "uniquement en annexe", D: "sur décision de l'administration fiscale" },
      ok: "B", ex: "Un changement de méthode est rétrospectif (comparatifs retraités). Un changement d'estimation (durée d'utilité, par exemple) est prospectif. Le CGNC demande, lui, de justifier le changement et d'en donner l'incidence dans l'ETIC." },
    { src: ENT, conf: "E", q: "Selon IFRS 15, le chiffre d'affaires est comptabilisé :",
      o: { A: "à l'encaissement", B: "lorsque (ou à mesure que) l'entreprise remplit une obligation de prestation, par le transfert du contrôle du bien ou du service au client", C: "à la signature du contrat", D: "à la livraison, dans tous les cas" },
      ok: "B", ex: "Cinq étapes : identifier le contrat, identifier les obligations de prestation, déterminer le prix, le répartir entre les obligations, comptabiliser le produit quand chaque obligation est remplie." },
  ],

  // ───────────────────────── Partie 4 · Comptabilité analytique et contrôle de gestion
  4: [
    { src: Q24(10), conf: "S", q: "8 000 kg de matière « M » à 35 DH le kg donnent, après transformation, 7 200 kg de produit fini et 800 kg de déchets. MOD : 400 heures à 70 DH ; charges indirectes : 44 800. Parmi ces propositions :",
      o: { A: "Le coût de production unitaire est de 49 DH", B: "La quantité fabriquée de produit fini est de 8 000 kg", C: "Le coût des déchets est de 28 000 DH" },
      ok: "A", ex: R`$280\,000 + 28\,000 + 44\,800 = 352\,800$ ; $352\,800 / 7\,200 = 49$ DH/kg (déchets sans valeur). B : seuls 7 200 kg sont produits. C : 28 000 est le coût de la MOD.` },
    { src: Q24(11), conf: "P", q: "Les en-cours de fabrication :",
      o: { A: "sont utilisables", B: "sont vendables", C: "nécessitent une évaluation" },
      ok: "C", ex: "Un en-cours est une production inachevée : ni utilisable ni vendable en l'état. On l'évalue à la clôture d'après les charges engagées et le degré d'avancement. Un document de correction ajoute A : nous ne le retenons pas." },
    { src: Q24(12), conf: "S", q: "Après la répartition secondaire, les charges indirectes sont :",
      o: { A: "imputées à d'autres sections", B: "regroupées dans les sections principales", C: "imputées dans les coûts" },
      ok: "B", ex: "La répartition secondaire vide les sections auxiliaires dans les sections principales. L'imputation aux coûts (C) vient ensuite, par les unités d'œuvre." },
    { src: Q24(13), conf: "P", q: "L'écart entre la charge d'usage et la dotation comptable est dû à :",
      o: { A: "la durée de vie de l'immobilisation", B: "la base d'amortissement", C: "l'état du bien amortissable" },
      ok: "AB", ex: "La charge d'usage se calcule sur une valeur économique (valeur actuelle ou de remplacement) et sur la durée d'utilisation réelle, alors que la dotation part du coût historique et d'une durée comptable ou fiscale." },
    { src: Q24("14 et 17"), conf: "P", q: "Pour l'année N+3, l'entreprise envisage de grosses réparations liées à l'installation électrique, d'un montant probable de 360 000 DH. En comptabilité analytique, la charge étalée de l'exercice N est estimée à 80 000 DH. La différence d'incorporation de 40 000 DH est :",
      o: { A: "une charge incorporable", B: "une charge non incorporable", C: "une charge de substitution" },
      ok: "BC", ex: R`En supposant une provision comptable de $360\,000 / 3 = 120\,000$ par an : l'analytique remplace cette charge par une charge étalée de 80 000 (charge de substitution), et l'écart de 40 000 est la part de la charge comptable non retenue. Le même énoncé figure sous deux numéros dans le document de correction 2024.` },
    { src: Q24(25), conf: "S", q: "Production normale : 30 000 unités pour 12 500 heures-machine ; coût prévisionnel 450 000 DH dont 250 000 de fixe. Activité réelle : 20 000 heures pour 35 000 unités ; coût réel : 500 000 DH. Le budget flexible de l'activité réelle est de :",
      o: { A: "500 000 DH", B: "570 000 DH", C: "525 000 DH" },
      ok: "B", ex: R`Coût variable par heure : $200\,000 / 12\,500 = 16$. Budget flexible : $250\,000 + 16 \times 20\,000 = 570\,000$. Le budget de la production réelle (activité préétablie de 14 583 h) donnerait 483 333.` },
    { src: REC(20), conf: "S", q: "Stock initial de 500 unités à 40 DH ; une entrée de 1 500 unités à 48 DH. Le coût moyen unitaire pondéré de fin de période est de :",
      o: { A: "44 DH", B: "46 DH", C: "48 DH", D: "88 DH" },
      ok: "B", ex: R`$\frac{500 \times 40 + 1\,500 \times 48}{2\,000} = \frac{92\,000}{2\,000} = 46$. A est la moyenne simple des deux prix, qui ignore les quantités.` },
    { src: REC(21), conf: "S", q: "En juin, 1 000 produits « X » sont vendus 120 DH HT l'unité. Coût de production unitaire (CMUP) : 55 DH. Charges directes de distribution : 7 000 DH. Section distribution : 5 DH pour 100 DH de CA HT. Le résultat analytique est de :",
      o: { A: "57 500 DH", B: "46 000 DH", C: "52 000 DH", D: "53 000 DH" },
      ok: "C", ex: R`$120\,000 - (55\,000 + 7\,000 + 6\,000) = 52\,000$.` },
    { src: REC(22), conf: "S", q: "Matières consommées 80 000 ; MOD 30 000 ; charges indirectes imputées 20 000 ; en-cours initial 10 000 ; en-cours final 15 000. Le coût de production des produits achevés est de :",
      o: { A: "115 000 DH", B: "125 000 DH", C: "130 000 DH", D: "145 000 DH" },
      ok: "B", ex: R`$80\,000 + 30\,000 + 20\,000 + 10\,000 - 15\,000 = 125\,000$. Ajoute l'en-cours initial, retranche l'en-cours final.` },
    { src: REC(23), conf: "S", q: "Dans le modèle coût-volume-profit, le seuil de rentabilité est atteint lorsque :",
      o: { A: "la marge sur coût variable est égale aux charges fixes", B: "le chiffre d'affaires est égal aux seules charges variables", C: "les charges fixes deviennent nulles", D: "la marge sur coût variable devient nulle" },
      ok: "A", ex: "Au seuil, la marge sur coût variable couvre exactement les charges fixes : le résultat est nul." },
    { src: REC(24), conf: "S", q: "Chiffre d'affaires annuel prévu : 1 200 000 DH ; charges variables proportionnelles : 720 000 ; charges fixes : 300 000. Le seuil de rentabilité en chiffre d'affaires est de :",
      o: { A: "480 000 DH", B: "600 000 DH", C: "750 000 DH", D: "900 000 DH" },
      ok: "C", ex: R`Taux de MCV : $480\,000 / 1\,200\,000 = 40\,\%$. Seuil : $300\,000 / 0{,}40 = 750\,000$.` },
    { src: REC(25), conf: "S", q: "Même entreprise, ventes réalisées régulièrement sur une année conventionnelle de 360 jours. Le point mort est atteint après :",
      o: { A: "180 jours", B: "225 jours", C: "270 jours", D: "300 jours" },
      ok: "B", ex: R`$\frac{750\,000}{1\,200\,000} \times 360 = 225$ jours, soit vers la mi-août pour un exercice civil.` },
    { src: ENT, conf: "E", q: "Même entreprise (CA 1 200 000, seuil 750 000). L'indice de sécurité est de :",
      o: { A: "62,5 %", B: "37,5 %", C: "40 %", D: "60 %" },
      ok: "B", ex: R`Marge de sécurité : $1\,200\,000 - 750\,000 = 450\,000$. Indice : $450\,000 / 1\,200\,000 = 37{,}5\,\%$. A est le rapport seuil / CA.` },
    { src: ENT, conf: "E", q: "Même entreprise (MCV 480 000, charges fixes 300 000). Le coefficient de levier opérationnel est d'environ :",
      o: { A: "1,6", B: "2,67", C: "0,4", D: "4" },
      ok: "B", ex: R`Levier $= \frac{MCV}{\text{résultat}} = \frac{480\,000}{180\,000} \approx 2{,}67$ : une hausse de 10 % du CA augmente le résultat d'environ 26,7 %. C'est l'inverse de l'indice de sécurité ($1 / 0{,}375$).` },
    { src: ENT, conf: "E", q: "Charges fixes d'un atelier : 120 000 DH pour une activité normale de 10 000 heures. Activité réelle : 9 000 heures. Les charges fixes imputées aux coûts sont de :",
      o: { A: "120 000 DH, avec un boni de 12 000", B: "108 000 DH, avec un coût de sous-activité de 12 000", C: "133 333 DH", D: "108 000 DH, avec un boni de 12 000" },
      ok: "B", ex: R`Coefficient d'imputation rationnelle : $9\,000 / 10\,000 = 0{,}9$. Charges fixes imputées : $108\,000$. Les 12 000 non imputés sont un coût de chômage (sous-activité), un mali.` },
    { src: ENT, conf: "E", q: "Standard : 2 kg de matière à 10 DH par unité. Production réelle : 1 000 unités ; consommation réelle : 2 100 kg à 9,50 DH. L'écart sur quantité de matière est de :",
      o: { A: "1 000 DH défavorable", B: "1 050 DH favorable", C: "50 DH favorable", D: "950 DH défavorable" },
      ok: "A", ex: R`Écart sur quantité $= (2\,100 - 2\,000) \times 10 = 1\,000$ (défavorable). Écart sur prix $= (9{,}50 - 10) \times 2\,100 = -1\,050$ (favorable). Écart global $= 19\,950 - 20\,000 = -50$ (favorable).` },
  ],

  // ───────────────────────── Partie 5 · Fiscalité
  5: [
    { key: "R9", src: REC(9), conf: "S", q: "Pour la cotisation minimale de la société « ABC », montants hors TVA : ventes 49 344 300 ; produits accessoires 284 100 ; subventions d'exploitation 370 170 ; produits de cession d'immobilisations 280 450 ; produits financiers imposables hors dividendes 235 350. Taux de 0,50 %. CM arrondie au dirham :",
      o: { A: "252 572 DH", B: "251 170 DH", C: "249 992 DH", D: "246 722 DH" },
      ok: "B", ex: R`Base : $49\,344\,300 + 284\,100 + 370\,170 + 235\,350 = 50\,233\,920$ ; $\times 0{,}5\,\% = 251\,169{,}60$. Les produits de cession sont exclus de la base ; A les inclut.` },
    { src: ADA("2020 (formation continue)"), conf: "S", q: "L'impôt dû au titre de N-1 était la cotisation minimale de 70 624 DH (IS de 30 736,75). L'IS de N s'élève à 176 550,96. Chaque acompte versé en N est de :",
      o: { A: "7 684,19 DH", B: "17 656 DH", C: "44 137,74 DH", D: "70 624 DH" },
      ok: "B", ex: R`Les acomptes de N valent chacun 25 % de l'impôt dû au titre du dernier exercice clos, IS ou CM : $70\,624 / 4 = 17\,656$, avant le 31/03, le 30/06, le 30/09 et le 31/12. A se base sur l'IS de N-1 au lieu de la CM effectivement due ; C sur l'IS de N.` },
    { src: ADA("2017"), conf: "S", q: "L'exercice N-1 s'est soldé par un déficit fiscal provenant en totalité des amortissements. Ce déficit est reportable :",
      o: { A: "sur les 4 exercices suivants", B: "sans limite de durée", C: "sur 5 ans", D: "il n'est pas reportable" },
      ok: "B", ex: "Article 12 du CGI : la part du déficit correspondant aux amortissements est reportable sans limite ; le reste, sur les quatre exercices qui suivent. En N-1, l'impôt exigible est la cotisation minimale." },
    { src: REC(10), conf: "S", q: "CA hors taxes : 42 280 500 DH. Dons : Fondation Mohammed VI de promotion des œuvres sociales de l'éducation-formation : 40 000 ; œuvres sociales de la communauté urbaine de Casablanca, légalement habilitées à recevoir des dons : 54 000 ; association des anciens ingénieurs chimistes, non reconnue d'utilité publique : 18 500. Total à réintégrer :",
      o: { A: "72 500 DH", B: "18 500 DH", C: "49 061 DH", D: "30 561 DH" },
      ok: "B", ex: R`Fondation : déductible en totalité. Œuvres sociales : plafond $2\,‰ \times 42\,280\,500 = 84\,561$, au-dessus de 54 000. Association non reconnue : réintégrée.` },
    { key: "R5", src: FC(7), conf: "S", q: "CA : 15 761 000 DH. Dons : œuvres sociales du personnel de l'entreprise 50 000 ; association de lauréats d'une école privée 10 000. Montant non déductible à réintégrer :",
      o: { A: "60 000,00 DH", B: "28 478,00 DH", C: "18 478,00 DH" },
      ok: "B", ex: R`Plafond des œuvres sociales : $15\,761\,000 \times 2\,‰ = 31\,522$ ; excédent $18\,478$. L'association de lauréats n'est pas un bénéficiaire prévu par le CGI : 10 000 réintégrés. Total 28 478. C oublie l'association.` },
    { src: Q24(26), conf: "P", q: "SA « CCA », CA 50 736 600 DH. Dons : Fondation Mohammed VI 42 500 ; œuvres sociales de la commune urbaine de Casablanca 75 000 ; association des anciens ingénieurs chimistes 25 000. Dons non déductibles à réintégrer :",
      o: { A: "25 000 DH", B: "100 000 DH", C: "67 500 DH" },
      ok: "A", ex: R`Fondation Mohammed VI : déductible en totalité. Œuvres sociales : $2\,‰ \times 50\,736\,600 = 101\,473{,}20$, au-dessus de 75 000. L'association n'est pas présentée comme reconnue d'utilité publique : 25 000. « Probable » parce que le sujet ne précise pas la fondation.` },
    { src: ADA("2018"), conf: "S", q: "CA : 86 547 900 DH. Dons aux œuvres sociales de la ville : 220 000 DH. Montant à réintégrer :",
      o: { A: "220 000", B: "46 904,20", C: "173 095,80", D: "0" },
      ok: "B", ex: R`Plafond : $86\,547\,900 \times 2\,‰ = 173\,095{,}80$. Excédent réintégré : $220\,000 - 173\,095{,}80 = 46\,904{,}20$. C est le montant déductible.` },
    { key: "R4", src: FC(9), conf: "S", q: "Capital de 2 000 000 entièrement libéré. Avances d'associés : KARIMI 800 000 et FATHI 400 000 le 01/04/N ; KARIMI 1 000 000 le 01/07/N ; remboursement à KARIMI de 1 500 000 le 01/10/N. Taux servi 3,5 %, taux fiscal 2,25 %. Intérêts à réintégrer :",
      o: { A: "13 937,50 DH", B: "12 812,50 DH", C: "13 542,50 DH" },
      ok: "A", ex: R`Comptabilisés : $10\,500 + 19\,250 + 6\,125 = 35\,875$. Admis à 2,25 %, avances plafonnées au capital : $6\,750 + 11\,250\ (2\,000\,000\ \text{retenus au lieu de}\ 2\,200\,000) + 3\,937{,}50 = 21\,937{,}50$. Réintégration : 13 937,50. B oublie le plafond au 3e trimestre.` },
    { src: REC(11), conf: "S", q: "Capital de 3 500 000 entièrement libéré. Apports en compte courant : TAKI 1 500 000 le 01/04/N ; RAMI 1 800 000 le 01/07/N. Intérêts comptabilisés à 7,5 %, taux admis 3,5 %, prorata des mois. Montant à réintégrer :",
      o: { A: "81 000 DH", B: "151 875 DH", C: "70 875 DH", D: "108 125 DH" },
      ok: "A", ex: R`Comptabilisés : $84\,375 + 67\,500 = 151\,875$. Admis : $39\,375 + 31\,500 = 70\,875$. Avances (3 300 000) inférieures au capital : seul l'excédent de taux est réintégré, soit 81 000.` },
    { src: Q24(27), conf: "S", q: "SA « CCA », capital de 4 200 000 entièrement libéré. Comptes courants rémunérés à 7 % : THAMI 1 200 000 le 1/4/23 ; NAJI 1 500 000 le 1/9/23. Taux fiscal autorisé : 3,5 %. Intérêts à réintégrer :",
      o: { A: "49 000 DH", B: "98 000 DH", C: "66 500 DH" },
      ok: "A", ex: R`$1\,200\,000 \times 3{,}5\,\% \times 9/12 + 1\,500\,000 \times 3{,}5\,\% \times 4/12 = 31\,500 + 17\,500 = 49\,000$. B réintègre la totalité des intérêts.` },
    { src: ADA("2019 (formation initiale)"), conf: "S", q: "Capital de 1 000 000 libéré, porté à 1 200 000 le 01/09/N (libéré le jour même). Avances au 01/03 : 700 000 (SAADAOUI) et 500 000 (LAMRANI) ; SAADAOUI retire 400 000 le 30/06 ; LAMRANI avance 500 000 de plus le 01/07. Intérêts comptabilisés à 6 % : 63 000. Taux fiscal 2,25 %. Montant à réintégrer :",
      o: { A: "42 750", B: "39 375", C: "44 250", D: "63 000" },
      ok: "A", ex: R`Admis, avances plafonnées au capital : mars-juin $1\,000\,000 \times 2{,}25\,\% \times 4/12 = 7\,500$ ; juillet-août $1\,000\,000 \times 2{,}25\,\% \times 2/12 = 3\,750$ ; septembre-décembre $1\,200\,000 \times 2{,}25\,\% \times 4/12 = 9\,000$. Total 20 250 ; réintégration $63\,000 - 20\,250 = 42\,750$. B oublie le plafond ; C ignore l'augmentation de capital.` },
    { key: "R7", src: REC(12), conf: "S", q: "Voiture de tourisme acquise et mise en service le 01/09/N-1 pour 300 000 HT (TVA de 20 % non récupérable), amortie au taux linéaire de 20 %. La dotation de N-1 a été omise ; en N, le comptable a enregistré 96 000 (dotation de N et rattrapage de N-1). Base fiscale plafonnée à 300 000 TTC. Montant à réintégrer :",
      o: { A: "20 000 DH", B: "96 000 DH", C: "36 000 DH", D: "12 000 DH" },
      ok: "C", ex: R`Coût TTC 360 000 ; dotation de N 72 000 et rattrapage $24\,000$. Admis en N : $300\,000 \times 20\,\% = 60\,000$. Le rattrapage d'une dotation omise est perdu fiscalement. Réintégration : $96\,000 - 60\,000 = 36\,000$.` },
    { src: FC(8), conf: "V", q: "Voiture du PDG : coût TTC 438 000, mise en service le 01/04/N-1, durée 5 ans. Le comptable a enregistré en N la dotation omise de N-1 et celle de N : 153 300. Montant à réintégrer :",
      o: { A: "27 600,00 DH", B: "48 300,00 DH", C: "115 200,00 DH" },
      ok: "B", ex: R`Calcul exact : rattrapage de N-1 perdu ($65\,700$) + excédent de N sur le plafond ($87\,600 - 60\,000 = 27\,600$) = $93\,300$, absent des options. B ($153\,300 - 45\,000 - 60\,000$) applique le plafond aux deux dotations : c'est la réponse que le correcteur attendait sans doute, mais elle contredit la règle de la dotation omise, perdue fiscalement (voir la question à 36 000 DH).` },
    { src: ADA("2020 (formation continue)"), conf: "S", q: "Voiture de tourisme immatriculée au nom de la société, acquise le 02/04/N pour 462 720 TTC, amortie en linéaire sur 5 ans : dotation comptabilisée 69 408. Montant à réintégrer :",
      o: { A: "69 408", B: "24 408", C: "9 408", D: "0" },
      ok: "B", ex: R`Admis : $300\,000 \times 20\,\% \times 9/12 = 45\,000$. Réintégration : $69\,408 - 45\,000 = 24\,408$. C applique le plafond sur une année entière.` },
    { src: ADA("2018"), conf: "S", q: "Un véhicule de transport de marchandises acquis le 08/10/N (487 500 HT, TVA 97 500) a été comptabilisé TTC et amorti linéairement sur 5 ans. Montant à réintégrer :",
      o: { A: "97 500", B: "4 875", C: "29 250", D: "0" },
      ok: "B", ex: R`La TVA d'un véhicule utilitaire est récupérable : base correcte 487 500. Dotation comptabilisée $585\,000 \times 20\,\% \times 3/12 = 29\,250$ ; admise $24\,375$ ; excédent $4\,875$.` },
    { src: ADA("2020 (formation continue)"), conf: "P", q: "Une facture de fournitures de bureau de 18 600 TTC (TVA 20 %) a été payée en espèces, en une fois, à un même fournisseur. Les charges réglées en espèces ne sont déductibles que dans la limite de 5 000 DH TTC par jour et par fournisseur. Montant HT à réintégrer :",
      o: { A: "15 500", B: "11 333,33", C: "13 600", D: "0" },
      ok: "B", ex: R`Fraction déductible : $5\,000 / 1{,}2 = 4\,166{,}67$ HT. Réintégration : $15\,500 - 4\,166{,}67 = 11\,333{,}33$, si la facture a été comptabilisée HT. C est le dépassement en TTC. Les anciens sujets (2017) appliquaient une limite de 10 000 DH.` },
    { key: "R8", src: REC(13), conf: "S", q: "Une société soumise à l'IS a reçu 71 400 DH d'intérêts nets sur un placement à terme, après une retenue à la source de 20 %, et n'a enregistré que ce net en produits financiers. Le retraitement consiste à :",
      o: { A: "réintégrer 17 850 DH", B: "réintégrer 14 280 DH", C: "réintégrer 71 400 DH", D: "n'effectuer aucun retraitement" },
      ok: "A", ex: R`Brut $= 71\,400 / 0{,}8 = 89\,250$ ; retenue $17\,850$. Le produit imposable est le brut ; la retenue s'impute ensuite sur l'IS. B applique 20 % au net.` },
    { src: FC(12), conf: "S", q: "Un intérêt sur une avance à une filiale a été comptabilisé pour son montant brut de 12 440 DH ; la filiale a retenu une TPPRF de 2 488 DH, non imputée sur les acomptes. Traitement fiscal :",
      o: { A: "réintégrer 3 110 DH", B: "réintégrer 3 110 DH et l'imputer sur l'impôt de N", C: "aucun retraitement du résultat" },
      ok: "C", ex: "Le produit est déjà comptabilisé brut : rien à réintégrer. La TPPRF de 2 488 est un crédit d'impôt, imputé à la liquidation de l'IS. 3 110 traite à tort 12 440 comme un net. Compare avec la question des 71 400 DH d'intérêts nets : tout dépend du montant comptabilisé, brut ou net." },
    { src: FC(10), conf: "S", q: "Une garantie de 12 000 DH, reçue pour le prêt d'un matériel, a été comptabilisée en « Autres produits d'exploitation ». Traitement fiscal :",
      o: { A: "à réintégrer", B: "ne rien faire", C: "à déduire" },
      ok: "C", ex: "Un dépôt de garantie sera restitué : c'est une dette (1487 « Dépôts et cautionnements reçus »), pas un produit. Comptabilisé à tort en produit, il est déduit." },
    { key: "R6", src: FC(11), conf: "S", q: "Reprises sur provisions comptabilisées en N : 16 600 sur une provision de N-1 pour un redressement fiscal ; 12 450 sur une provision de N-1 pour une perte de change latente. Montant à corriger fiscalement :",
      o: { A: "29 050,00 DH", B: "12 450,00 DH", C: "16 600,00 DH" },
      ok: "C", ex: "La provision pour redressement fiscal (pénalités, impôts non déductibles) a été réintégrée en N-1 : sa reprise est déduite. La provision pour perte de change était déductible : sa reprise est imposable, sans correction." },
    { src: ADA("non daté 1"), conf: "S", q: "Une reprise de 166 600 DH est comptabilisée en N sur une provision pour « propre assureur » (auto-assurance) constituée en N-3. Traitement fiscal en N :",
      o: { A: "aucun retraitement", B: "réintégrer 166 600", C: "déduire 166 600", D: "réintégrer la moitié" },
      ok: "C", ex: "Une provision pour propre assureur ne couvre pas une perte probable précise : elle n'est pas déductible et a été réintégrée en N-3. Sa reprise ne doit pas être imposée une seconde fois : on la déduit." },
    { key: "R11", src: ADA("2017 et 2019 (formation initiale)"), conf: "S", q: "La taxe professionnelle de l'exercice, payée en retard, a coûté : principal 12 340, pénalité 1 851, majoration de retard 617. Montant à réintégrer :",
      o: { A: "14 808", B: "2 468", C: "1 851", D: "0" },
      ok: "B", ex: "Le principal d'un impôt déductible est une charge déductible. Les pénalités et majorations ne le sont jamais : 1 851 + 617 = 2 468." },
    { src: ADA("2017 et 2019 (formation initiale)"), conf: "S", q: "Une note d'honoraires de 9 000 DH TTC (TVA 20 % récupérable) a été comptabilisée en charges pour son montant TTC. Montant à réintégrer :",
      o: { A: "9 000", B: "1 500", C: "1 800", D: "0" },
      ok: "B", ex: R`La TVA récupérable n'est pas une charge : $9\,000 \times 20/120 = 1\,500$. C calcule 20 % du TTC. Même question dans le sujet non daté 2 (avocat : 9 295 TTC, soit 1 549,17).` },
    { key: "R10", src: ADA("2020 (formation continue), non datés 1 et 2"), conf: "S", q: "Écart de conversion passif au 31/12/N-1 : 6 540 ; au 31/12/N : 8 780. Traitement fiscal en N :",
      o: { A: "déduire 8 780 et réintégrer 6 540", B: "réintégrer 8 780 et déduire 6 540", C: "réintégrer 2 240", D: "aucun retraitement" },
      ok: "B", ex: "Le gain latent de N est imposable l'année où il est constaté : on le réintègre. Celui de N-1, déjà imposé, est repris ou réalisé en N : on le déduit. Le net vaut bien +2 240, mais le correcteur attend les deux lignes." },
    { src: ADA("non daté 1"), conf: "S", q: "Cadeaux aux clients : 800 agendas (14,40 TTC l'unité, sigle de la société) ; 50 montres-bracelets (540 TTC l'unité, nom de la société), soit 27 000 TTC. Montant à réintégrer pour les montres :",
      o: { A: "38 520", B: "27 000", C: "22 500", D: "0" },
      ok: "B", ex: "Les objets publicitaires sont déductibles jusqu'à 100 DH TTC l'unité, avec le sigle ou la raison sociale. Les montres dépassent ce seuil : non déductibles, et leur TVA n'est pas récupérable, d'où une réintégration TTC. A y ajoute à tort les agendas, qui sont déductibles." },
    { src: ADA("non daté 1"), conf: "S", q: "Des fournitures de bureau comptabilisées le 24/12/N pour 62 880 TTC (TVA 20 %) n'ont été livrées que pour moitié en N ; l'autre moitié est arrivée le 08/01/N+1. Montant à réintégrer :",
      o: { A: "62 880", B: "26 200", C: "31 440", D: "0" },
      ok: "B", ex: R`Une charge se rattache à l'exercice de livraison : $62\,880 / 1{,}2 / 2 = 26\,200$ HT relèvent de N+1. C garde le TTC.` },
    { src: Q24("6-1"), conf: "S", q: "Le 20/02/2023, la société « MAF » cède à « KOLAK », pour 600 000 DH, un local commercial acquis le 10/02/2020 pour 900 000 DH TTC (TVA de 20 % déduite). La TVA à reverser est de :",
      o: { A: "90 000 DH", B: "100 000 DH", C: "50 000 DH" },
      ok: "A", ex: R`TVA déduite : $900\,000 \times 20/120 = 150\,000$. Délai de conservation d'un immeuble : 10 ans ; année d'acquisition et fraction d'année comptent : 2020 à 2023, soit 4 ans. Reversement $= 150\,000 \times 6/10 = 90\,000$. Pour un bien meuble, le délai est de 5 ans.` },
    { key: "R12", src: REC(14), conf: "S", q: "Exercice N-1 : ventes taxables HT 2 000 000 ; exonérées avec droit à déduction 800 000 ; exonérées sans droit 1 332 000 ; hors champ 600 000 ; indemnités d'assurance réparant un dommage, sans contrepartie, 240 000. TVA 20 %, taxe théorique incluse au numérateur. Prorata arrondi au dixième :",
      o: { A: "60,8 %", B: "63,5 %", C: "52,9 %", D: "59,1 %" },
      ok: "B", ex: R`$\frac{(2\,000\,000 + 800\,000) \times 1{,}2}{3\,360\,000 + 1\,332\,000 + 600\,000} = \frac{3\,360\,000}{5\,292\,000} = 63{,}49\,\%$. Les indemnités sans contrepartie sont exclues.` },
    { src: REC(15), conf: "S", q: "L'entreprise acquiert un matériel de 150 000 HT (TVA 20 %), utilisé à la fois pour des activités ouvrant droit à déduction et pour d'autres qui n'y ouvrent pas. Prorata : 63,5 %. TVA récupérable :",
      o: { A: "18 240 DH", B: "30 000 DH", C: "19 050 DH", D: "17 730 DH" },
      ok: "C", ex: R`$30\,000 \times 63{,}5\,\% = 19\,050$. Les 10 950 non récupérables augmentent le coût du matériel.` },
    { src: Q24(28), conf: "S", q: "Un immeuble abrite une supérette (rez-de-chaussée), des bureaux et des logements. CA 2023 : taxable 5 000 000 ; exonéré avec droit à déduction 750 000 ; exonéré sans droit 800 000 ; hors champ 450 000 ; indemnités d'assurance encaissées 180 000. TVA 20 %. Le prorata 2023 est de :",
      o: { A: "84,66 %", B: "82,14 %", C: "80,23 %" },
      ok: "A", ex: R`Numérateur : $(5\,000\,000 + 750\,000) \times 1{,}2 = 6\,900\,000$. Dénominateur : $6\,900\,000 + 800\,000 + 450\,000 = 8\,150\,000$. Prorata : $84{,}66\,\%$, indemnités exclues. Il servira aux déductions de 2024.` },
    { src: Q24(29), conf: "S", q: "Prorata 2023 de 84 %. Matériel acquis 350 000 HT, TVA 20 %. La TVA non admise en déduction est de :",
      o: { A: "70 000 DH", B: "58 800 DH", C: "11 200 DH" },
      ok: "C", ex: R`$70\,000 - 70\,000 \times 84\,\% = 11\,200$, ajoutés au coût d'entrée du matériel. B est la TVA déductible.` },
    { src: Q24(30), conf: "P", q: "Une société industrielle fournit à son personnel des prestations de restauration sur le lieu de travail. Au regard de la TVA, ces opérations :",
      o: { A: "sont exonérées", B: "sont imposables", C: "peuvent faire l'objet d'une option à l'imposition" },
      ok: "B", ex: "La restauration fournie directement par l'entreprise à son personnel salarié est imposable, au taux réduit de 10 %. L'imposition vient de la loi : pas d'option." },
    { key: "R16", src: ADA("2024 et 2022/23 (reconstitution)"), conf: "S", q: "Le régime suspensif de la TVA (article 94 du CGI) permet :",
      o: { A: "aux exportateurs d'acheter en suspension de TVA les biens et services nécessaires à l'export, dans la limite du CA export de l'année précédente", B: "à toute entreprise déficitaire de suspendre le paiement de sa TVA", C: "aux importateurs de différer la TVA payée en douane", D: "de ne pas facturer de TVA sur les ventes locales" },
      ok: "A", ex: "Sur demande, l'administration délivre une attestation d'achat en suspension par fournisseur ; la facture porte la mention « vente en suspension de la TVA ». L'exportateur n'avance pas une taxe qu'il devrait se faire rembourser. Question de cours posée en 2024 et dans la reconstitution 2022/23." },
    { src: Q24(4), conf: "V", q: "Société « RANZI », septembre : avances versées le 15 : 3 000 ; salaires de base 118 000 ; primes d'ancienneté 11 500 ; avantages en nature 2 800 ; indemnité de transport 3 460 ; cotisations sociales 7 422 ; CIMR 2 400. Les salaires nets imposables sont de :",
      o: { A: "122 938 DH", B: "120 138 DH", C: "121 418 DH" },
      ok: "A", ex: R`Aucune option n'est juste en toute rigueur. A se reconstitue ainsi : $135\,760 - 9\,822 - 3\,000$, c'est-à-dire tout le brut, moins les cotisations et moins l'avance. Or l'avance n'est qu'un acompte sur le net à payer, et l'indemnité de transport est exonérée dans la limite légale. Avec une indemnité entièrement exonérée : $132\,300 - 9\,822 = 122\,478$. Coche A, la seule qui retient tous les éléments imposables.` },
  ],

  // ───────────────────────── Partie 6 · Audit
  6: [
    { src: ADA("2024 · question de cours"), conf: "S", q: "Une information financière régulière et sincère doit notamment être exhaustive. Cela signifie que :",
      o: { A: "toutes les opérations et informations significatives sont enregistrées", B: "les actifs appartiennent à l'entreprise", C: "les montants sont arrondis au millier", D: "les comptes sont publiés au Bulletin officiel" },
      ok: "A", ex: "Exhaustivité : rien ne manque. B décrit l'assertion « droits et obligations ». Régularité (conformité aux règles) et sincérité (application de bonne foi) concourent à l'image fidèle." },
    { src: ENT, conf: "E", q: "L'auditeur vérifie que les ventes livrées le 30 décembre figurent bien dans l'exercice et que celles du 2 janvier n'y figurent pas. Il teste l'assertion de :",
      o: { A: "existence", B: "séparation des exercices", C: "droits et obligations", D: "présentation" },
      ok: "B", ex: "Contrôle du cut-off : chaque opération est rattachée au bon exercice, d'après la date de livraison et non celle de la facture ou du paiement." },
    { src: ENT, conf: "E", q: "La confirmation directe des soldes clients (circularisation) apporte surtout des éléments probants sur :",
      o: { A: "l'existence des créances", B: "l'exhaustivité des dettes fournisseurs", C: "la valeur nette de réalisation des stocks", D: "la présentation de l'ETIC" },
      ok: "A", ex: "Un client qui confirme son solde prouve que la créance existe. Il ne prouve pas qu'elle sera payée (évaluation) : pour cela, on examine les encaissements postérieurs et l'ancienneté des créances." },
    { src: ENT, conf: "E", q: "Si le risque inhérent et le risque lié au contrôle sont élevés, l'auditeur doit :",
      o: { A: "réduire ses contrôles", B: "réduire le risque de non-détection en étendant ses contrôles substantifs", C: "émettre une réserve d'office", D: "s'appuyer uniquement sur le contrôle interne" },
      ok: "B", ex: R`$RA = RI \times RC \times RND$. Pour garder le risque d'audit acceptable, plus RI et RC sont élevés, plus RND doit être faible : davantage de tests de détail et des échantillons plus larges.` },
    { src: ENT, conf: "E", q: "Au Maroc, les commissaires aux comptes d'une SA sont nommés pour :",
      o: { A: "un exercice", B: "trois exercices", C: "six exercices", D: "une durée illimitée" },
      ok: "B", ex: "Loi 17-95 : mandat de trois exercices, renouvelable. Une société faisant appel public à l'épargne nomme au moins deux commissaires aux comptes." },
    { src: ENT, conf: "E", q: "Une SARL doit désigner un commissaire aux comptes lorsque :",
      o: { A: "elle compte plus de 10 associés", B: "son chiffre d'affaires dépasse 50 millions de DH", C: "son capital dépasse 100 000 DH", D: "jamais" },
      ok: "B", ex: "Loi 5-96 : CAC obligatoire au-delà de 50 millions de DH de chiffre d'affaires. Les associés peuvent aussi en nommer un volontairement." },
    { src: ENT, conf: "E", q: "Un auditeur relève une anomalie significative, mais limitée à un poste et sans effet sur l'ensemble des comptes. Il émet :",
      o: { A: "une certification sans réserve", B: "une certification avec réserve", C: "un refus de certifier", D: "une impossibilité de certifier" },
      ok: "B", ex: "Avec réserve : désaccord ou limitation significatifs mais circonscrits. Refus : désaccord qui remet en cause l'image fidèle de l'ensemble. Impossibilité : limitation (ou incertitudes) empêchant de se prononcer." },
    { src: ENT, conf: "E", q: "Le test de permanence permet de vérifier que :",
      o: { A: "la procédure décrite existe réellement", B: "les contrôles identifiés fonctionnent sur toute la période", C: "les comptes annuels sont publiés", D: "l'entreprise poursuivra son exploitation" },
      ok: "B", ex: "Test de cheminement : on suit quelques opérations pour s'assurer que la procédure existe telle que décrite. Test de permanence : sur un échantillon de la période, on vérifie que les contrôles sont appliqués de façon continue." },
    { src: ENT, conf: "E", q: "Le principe de séparation des fonctions impose de confier à des personnes différentes :",
      o: { A: "la comptabilité générale et la comptabilité analytique", B: "l'autorisation, l'enregistrement et la conservation des actifs", C: "les achats et les ventes", D: "l'audit interne et l'audit externe" },
      ok: "B", ex: "Un même salarié ne doit pas pouvoir à la fois autoriser une opération, l'enregistrer et détenir les biens ou les fonds : sinon une fraude passe sans contrôle." },
    { src: ENT, conf: "E", q: "Pour préserver son indépendance, le commissaire aux comptes d'une société :",
      o: { A: "peut tenir sa comptabilité si les honoraires sont modérés", B: "ne peut pas tenir la comptabilité de la société qu'il contrôle", C: "peut en devenir dirigeant pendant son mandat", D: "peut être salarié de la société" },
      ok: "B", ex: "L'auditeur ne peut pas contrôler ce qu'il a lui-même produit (autorévision). Les incompatibilités de la loi 17-95 lui interdisent aussi des fonctions de direction ou un emploi salarié dans la société." },
    { src: ENT, conf: "E", q: "Le seuil de signification est :",
      o: { A: "le montant au-delà duquel une anomalie peut influencer le jugement des utilisateurs des comptes", B: "le montant minimal du chiffre d'affaires soumis à l'audit", C: "le plafond des honoraires de l'auditeur", D: "le seuil de rentabilité de l'entreprise" },
      ok: "A", ex: "Fixé dès la prise de connaissance (souvent en pourcentage du résultat, du CA ou des capitaux propres), il oriente l'étendue des travaux et l'évaluation des anomalies relevées." },
    { src: ENT, conf: "E", q: "Le référentiel COSO décrit le contrôle interne en :",
      o: { A: "trois composantes : actifs, passifs, résultat", B: "cinq composantes : environnement de contrôle, évaluation des risques, activités de contrôle, information et communication, pilotage", C: "quatre opinions", D: "sept principes comptables" },
      ok: "B", ex: "Le COSO sert de cadre à l'évaluation du contrôle interne par l'auditeur, interne comme externe." },
  ],
};

// Les QCM d'entraînement ont été rédigés avec la bonne réponse presque toujours en B. On fait tourner
// leurs propositions pour répartir la bonne lettre (A, B, C, D) ; les renvois « A est… » des
// explications suivent. Les QCM tirés d'un sujet gardent leurs lettres d'origine.
const CYCLE = ["C", "A", "D", "B"];
let tour = 0;
for (const q of Object.values(QCM).flat()) {
  if (q.conf !== "E" || q.ok.length !== 1) continue;
  const L = Object.keys(q.o);
  const cible = CYCLE.filter((l) => L.includes(l))[tour++ % CYCLE.filter((l) => L.includes(l)).length];
  const shift = (L.indexOf(cible) - L.indexOf(q.ok) + L.length) % L.length;
  const map = Object.fromEntries(L.map((l, i) => [l, L[(i + shift) % L.length]]));
  q.o = Object.fromEntries(L.map((l, i) => [L[i], q.o[L[(i - shift + L.length) % L.length]]]));
  q.ok = map[q.ok];
  q.ex = q.ex.replace(/(^|\. )([A-D])( est | retient )/g, (m, a, l, b) => a + map[l] + b);
}
