// QCM du cahier LCI (FP Larache), classés par partie : les 140 questions des sessions 2024 et 2025.
// conf : S = réponse sûre, P = probable, V = à vérifier. Énoncés recopiés des sujets en base
// (public/data/concours.json : 2024_Larache_FP_LCI, 2025_Larache_FP_LCI), réponses revérifiées.
const R = String.raw;
const A = (n) => `LCI 2024 · Q${n}`;
const B = (n) => `LCI 2025 · Q${n}`;

export const QCM = {
  // ───────────────────────── Partie 1 · Logistique et supply chain
  1: [
    { src: A(33), conf: "S", q: "Le terme « cross-docking » en logistique signifie :",
      o: { A: "Stocker les produits à long terme", B: "Livrer directement aux consommateurs", C: "Mélanger les produits de différents fournisseurs", D: "Transférer des marchandises sans les entreposer" },
      ok: "D", ex: "Les marchandises reçues sont triées sur le quai et réexpédiées aussitôt, sans passer par le stock. C décrit une conséquence possible (on regroupe les envois de plusieurs fournisseurs), pas la définition." },
    { src: B(1), conf: "S", q: "Le terme « cross-docking » en logistique signifie :",
      o: { A: "Stocker les produits à long terme dans un entrepôt", B: "Livrer directement les marchandises aux consommateurs", C: "Mélanger les produits de différents fournisseurs dans un stock", D: "Transférer les marchandises rapidement sans stockage intermédiaire" },
      ok: "D", ex: "Même question qu'en 2024, mot pour mot ou presque : quai de réception → tri → quai d'expédition, sans stockage intermédiaire. Délai de séjour visé : moins de 24 heures." },
    { src: A(34), conf: "S", q: "Que représente un « hub » logistique ?",
      o: { A: "Un bureau administratif pour le management de la logistique", B: "Un nœud de regroupement et de redistribution des flux", C: "Un entrepôt de vente des produits finis", D: "Un centre de distribution des produits finis" },
      ok: "B", ex: "Le hub (modèle « hub and spokes ») concentre les flux venus de nombreuses origines puis les redistribue. Tanger Med est un hub de transbordement de conteneurs. D est trop étroit : un hub ne se limite pas aux produits finis." },
    { src: A(35), conf: "S", q: "Que désigne le terme « juste-à-temps » (JAT) ?",
      o: { A: "La réduction des stocks en produisant selon la demande", B: "La livraison immédiate", C: "La vente sans stocks", D: "La fabrication en grande quantité" },
      ok: "A", ex: "Méthode Toyota : produire et approvisionner au rythme de la demande (flux tirés) pour réduire stocks et gaspillages, objectif « zéro stock ». B confond juste-à-temps et livraison express. En 2025, la même notion revient en anglais (« Just-in-time aims to… »)." },
    { src: A(42), conf: "S", q: "En matière de gestion de la chaîne d'approvisionnement, quelle est la différence entre « pull » et « push » ?",
      o: { A: "Le « pull » optimise la production et le « push » la distribution", B: "Le « pull » est basé sur la prévision et le « push » sur la demande réelle", C: "Le « pull » répond à la demande réelle, le « push » est basé sur la prévision", D: "Le « push » réduit les stocks tandis que le « pull » les augmente." },
      ok: "C", ex: "Flux tiré (pull) : on produit ou livre quand le client commande. Flux poussé (push) : on produit sur prévision et on pousse le stock vers l'aval. B inverse les deux, D aussi (c'est le pull qui réduit les stocks)." },
    { src: B(4), conf: "S", q: "La formule du stock de sécurité dépend principalement :",
      o: { A: "De la variabilité de la demande et du délai d'approvisionnement", B: "Du coût de transport et d'entreposage", C: "Du niveau moyen des ventes annuelles", D: "Du prix d'achat des marchandises" },
      ok: "A", ex: R`Le stock de sécurité couvre l'incertitude : $SS = z \times \sigma_d \times \sqrt{L}$, avec $\sigma_d$ l'écart-type de la demande par période, $L$ le délai d'approvisionnement et $z$ le coefficient du taux de service visé (1,65 pour 95 %). Le niveau moyen des ventes (C) fixe le stock d'alerte, pas la sécurité.` },
    { src: A(39), conf: "S", q: "Quelle technologie est souvent utilisée pour suivre les expéditions en temps réel ?",
      o: { A: "Code-barres", B: "RFID (Identification par radiofréquence)", C: "GPS (système de positionnement par satellite)", D: "Logiciels de comptabilité uniquement" },
      ok: "C", ex: "« En temps réel » : seul le GPS localise l'envoi en continu. Le code-barres et la RFID n'enregistrent qu'un passage devant un lecteur (traçabilité par points). En 2025, la même question met le GPS en D." },
    { src: A(44), conf: "P", q: "En logistique, la problématique qui consiste à choisir un prestataire de services est considérée :",
      o: { A: "Comme stratégique", B: "Comme tactique", C: "Comme opérationnelle", D: "Aucune bonne réponse" },
      ok: "A", ex: "Externaliser ou non, et à qui, engage l'entreprise sur plusieurs années : décision stratégique (make or buy). Le niveau tactique dimensionne les moyens (6 mois à 2 ans), l'opérationnel gère le quotidien. Certains cours classent la sélection du prestataire en tactique, une fois la décision d'externaliser prise : A reste la réponse attendue." },
    { src: A(45), conf: "S", q: "Qu'est-ce que l'arrimage ?",
      o: { A: "L'organisation des horaires de livraison pour les clients internationaux.", B: "La technique consistant à fixer et stabiliser les marchandises dans un véhicule ou conteneur pour éviter leur déplacement pendant le transport.", C: "Le processus d'étiquetage des produits avant leur exportation.", D: "L'évaluation des coûts de transport en fonction de la distance parcourue." },
      ok: "B", ex: "Arrimer = immobiliser la charge (sangles, cales, calage) dans le camion, le conteneur ou la cale du navire. Une charge mal arrimée est la première cause d'avarie en transport." },
    { src: A(46), conf: "S", q: "Qu'est-ce que l'amarrage ?",
      o: { A: "Le processus de dédouanement des marchandises à l'arrivée dans un port.", B: "L'opération consistant à attacher un navire à un quai, une bouée ou une autre structure pour le maintenir en place.", C: "La procédure de vérification des documents de transport avant l'embarquement.", D: "L'organisation des conteneurs sur le pont d'un navire pour optimiser l'espace." },
      ok: "B", ex: "Amarrer = attacher le navire au quai par des amarres. Ne pas confondre avec l'arrimage (la marchandise) ni avec l'acconage (la manutention navire-quai). D décrit le plan de chargement (gerbage des conteneurs)." },
    { src: A(48), conf: "S", q: "Qu'est-ce que l'acconage ?",
      o: { A: "Le processus de chargement et déchargement des marchandises entre le quai et le navire.", B: "L'organisation des expéditions pour les marchandises dangereuses.", C: "La vérification des documents douaniers pour les marchandises importées.", D: "Le calcul des coûts de transport en fonction de la destination." },
      ok: "A", ex: "L'acconier assure la manutention portuaire entre le navire et le quai (et la garde des marchandises sur le terminal). Au Maroc : Marsa Maroc, Somaport, les opérateurs de Tanger Med." },
    { src: B(2), conf: "S", q: "Un entrepôt de distribution a pour rôle principal :",
      o: { A: "Regrouper, stocker et préparer les commandes pour la distribution", B: "Fabriquer ou assembler des produits", C: "Dédouaner les marchandises à l'import", D: "Réaliser des audits financiers internes" },
      ok: "A", ex: "Réception, stockage, préparation des commandes (picking), emballage et expédition. La fabrication relève de l'usine, le dédouanement du transitaire." },
    { src: B(3), conf: "S", q: "Le Supply Chain Management correspond à :",
      o: { A: "La gestion des relations avec les clients uniquement", B: "La gestion intégrée des flux physiques et d'informations", C: "La planification de la production et des ventes", D: "Le contrôle de la qualité des produits finis" },
      ok: "B", ex: "Le SCM coordonne de bout en bout (du fournisseur du fournisseur au client du client) les flux physiques, d'informations et financiers. A est le CRM, C le PIC (plan industriel et commercial) : des parties seulement." },
    { src: B(5), conf: "S", q: "Le transport multimodal combine :",
      o: { A: "Le transport public uniquement", B: "Le recours à plusieurs entreprises concurrentes", C: "Le transport de passagers et de marchandises simultanément", D: "L'utilisation d'au moins deux modes de transport sous un seul contrat" },
      ok: "D", ex: "Multimodal : au moins deux modes (mer + route…) sous un contrat unique, avec un opérateur responsable de bout en bout. Intermodal : plusieurs modes avec la même unité de charge (le conteneur), sans rupture de charge." },
    { src: B(6), conf: "S", q: "La méthode 'Kaizen' consiste à :",
      o: { A: "Une amélioration continue des processus", B: "Une automatisation totale", C: "Une planification budgétaire", D: "Une centralisation des données" },
      ok: "A", ex: "Kaizen (« changement pour le mieux ») : amélioration continue par petits pas, avec tout le personnel. Outil du lean management, comme le Kanban et les 5S." },
    { src: B(7), conf: "S", q: "Dans un système Kanban, les flux sont :",
      o: { A: "Déterminés par le service commercial", B: "Variables selon les niveaux de stock", C: "Tirés par la demande réelle", D: "Poussés par la capacité de production" },
      ok: "C", ex: "Le Kanban (étiquette) ne déclenche la fabrication ou le réapprovisionnement que lorsque le poste aval a consommé : flux tirés. Les flux poussés (D) partent des prévisions. Même idée qu'en 2024 (question pull / push)." },
    { src: B(50), conf: "P", q: "Quel mode de transport est généralement considéré comme le plus écologique dans le domaine de la logistique verte ?",
      o: { A: "Fret maritime", B: "Fret ferroviaire", C: "Fret routier", D: "Fret aérien" },
      ok: "B", ex: "Dans les cours de logistique verte, le ferroviaire (traction électrique) est présenté comme le mode le plus propre pour le transport terrestre. Le maritime émet aussi très peu par tonne-kilomètre, mais il ne dessert pas les mêmes trajets : B est la réponse attendue. L'aérien est le plus polluant." },
    { src: A(79), conf: "P", q: "Le stock de sécurité permet de :",
      o: { A: "Minimiser le coût annuel de possession", B: "Faire face aux aléas de l'offre et de la demande", C: "D'augmenter le taux de service client", D: "Aucune bonne réponse" },
      ok: "B", ex: "Il couvre les aléas de la demande et des délais de livraison pour éviter la rupture. Il augmente le coût de possession (A est faux). Le meilleur taux de service (C) en est la conséquence, pas la fonction : B est la réponse attendue." },
    { src: B(9), conf: "S", q: "Quelle technologie est souvent utilisée pour suivre les expéditions en temps réel ?",
      o: { A: "Code-barres", B: "RFID", C: "ERP", D: "GPS" },
      ok: "D", ex: "Même question qu'en 2024, avec l'ERP en plus et le GPS passé de C à D. L'ERP est un progiciel de gestion intégré : il stocke les données, il ne localise rien." },
  ],

  // ───────────────────────── Partie 2 · Commerce international et douane
  2: [
    { src: A(32), conf: "S", q: "Qu'est-ce qu'une stratégie d'internationalisation ?",
      o: { A: "Une stratégie qui consiste à délocaliser uniquement la production vers un autre pays.", B: "Une stratégie visant à étendre les activités d'une entreprise sur des marchés internationaux", C: "Une stratégie qui exclut toute adaptation aux marchés locaux.", D: "Une stratégie de fusion avec des entreprises locales." },
      ok: "B", ex: "S'internationaliser = étendre ses activités à l'étranger, par l'export, une filiale, une licence, une franchise ou une coentreprise. La délocalisation (A) et la fusion (D) ne sont que des formes possibles." },
    { src: A(36), conf: "S", q: "Quel type de transport est le plus couramment utilisé pour l'exportation de marchandises à l'international ?",
      o: { A: "Transport aérien", B: "Transport terrestre", C: "Transport maritime", D: "Transport ferroviaire" },
      ok: "C", ex: "Le maritime achemine environ 80 % du volume du commerce mondial, et l'essentiel du commerce extérieur marocain (Tanger Med, Casablanca, Jorf Lasfar)." },
    { src: A(37), conf: "S", q: "Quel est le rôle des INCOTERMS dans le commerce international ?",
      o: { A: "Définir les délais de paiement", B: "Réguler la production locale", C: "Déterminer les responsabilités des acheteurs et des vendeurs dans le transport et la livraison des marchandises", D: "Fixer les prix de vente des produits" },
      ok: "C", ex: "Les Incoterms 2020 de la Chambre de commerce internationale répartissent les frais, les risques et les formalités entre vendeur et acheteur. Ils ne disent rien du paiement, du prix ni du transfert de propriété. En 2025, la même réponse est en A." },
    { src: A(38), conf: "S", q: "Quel document est essentiel pour le dédouanement des marchandises ?",
      o: { A: "Le bon de livraison", B: "La facture pro forma", C: "Le manifeste de transport", D: "La déclaration d'importation" },
      ok: "D", ex: "Le dédouanement repose sur la déclaration en douane : au Maroc, la DUM (déclaration unique de marchandises), déposée sur le système BADR, avec la facture commerciale. La pro forma n'est qu'une offre ; le manifeste liste la cargaison du navire." },
    { src: A(40), conf: "S", q: "Dans la balance commerciale d'un pays, un excédent signifie que :",
      o: { A: "Les importations sont plus élevées que les exportations", B: "Il n'y a pas de transactions internationales", C: "Les exportations sont égales aux importations", D: "Les exportations sont supérieures aux importations" },
      ok: "D", ex: "Solde commercial = exportations − importations : excédent quand X dépasse M. A est un déficit, C un équilibre. Le Maroc est en déficit structurel (question posée en 2025). En 2025, la même réponse est en A." },
    { src: B(11), conf: "P", q: "Quelle est l'utilité d'une « zone franche » dans le commerce international ?",
      o: { A: "Réduire les prix de vente sur le marché intérieur", B: "Faciliter les opérations d'import-export sans droits de douane ni formalités", C: "Accélérer la production locale des biens exportés", D: "Assurer le contrôle qualité des produits exportés" },
      ok: "B", ex: "Suspension des droits de douane et formalités allégées. « Ni formalités » est excessif (entrées et sorties restent déclarées), mais B est la seule proposition qui décrit la fonction d'une zone franche. En 2024, la même réponse était en C." },
    { src: A(41), conf: "S", q: "Quelle est l'utilité de la « zone franche » dans le commerce international ?",
      o: { A: "Réduire les prix de vente", B: "Accélérer la production locale", C: "Faciliter les opérations sans droits de douane", D: "Assurer des échanges locaux" },
      ok: "C", ex: "Espace hors du territoire douanier : on y importe, transforme et réexporte en suspension de droits. Au Maroc, ce sont les zones d'accélération industrielle (Tanger, Kénitra…). En 2025, la même réponse est en B." },
    { src: A(43), conf: "P", q: "Au niveau légal, les droits de douane sont calculés :",
      o: { A: "Sur la base de la facture du fabricant", B: "Ad valorem", C: "Sur la base de la déclaration du transitaire", D: "Aucune bonne réponse" },
      ok: "B", ex: "Les droits d'importation sont pour l'essentiel ad valorem : un pourcentage de la valeur en douane (valeur CIF de la marchandise). La facture et la déclaration servent à établir cette valeur, elles ne sont pas le mode de calcul. Quelques droits sont spécifiques (par unité) : d'où le niveau « probable »." },
    { src: A(47), conf: "S", q: "Quel est le principal intermédiaire entre l'acheteur et la douane ?",
      o: { A: "Le transitaire commissionnaire en douane, qui s'occupe des formalités douanières et de la logistique. (Bonne réponse)", B: "L'agent de fret, qui gère uniquement le transport des marchandises.", C: "L'importateur lui-même, qui s'occupe de toutes les démarches.", D: "Le mandataire, qui agit uniquement pour le compte de la douane." },
      ok: "A", ex: "Le commissionnaire en douane agréé par l'ADII accomplit les formalités pour le compte de l'importateur. Le sujet imprimé portait lui-même la mention « (Bonne réponse) » après la proposition A : un oubli de l'auteur, recopié tel quel." },
    { src: A(49), conf: "S", q: "Quel est le rôle du transitaire commissionnaire en douane ?",
      o: { A: "Il assure uniquement le transport des marchandises entre différents entrepôts.", B: "Il est responsable de la surveillance des marchandises lors du stockage en entrepôt.", C: "Il réalise les formalités douanières pour le compte des clients, facilite le passage des marchandises à la douane et organise leur transport.", D: "Il détermine les tarifs douaniers pour les produits importés et exportés." },
      ok: "C", ex: "Formalités douanières pour ses clients + organisation de l'acheminement. Les tarifs douaniers (D) sont fixés par la loi de finances, pas par un prestataire." },
    { src: B(8), conf: "S", q: "Quel est le rôle des INCOTERMS dans le commerce international ?",
      o: { A: "Déterminer les responsabilités respectives des vendeurs et acheteurs dans le transport international", B: "Définir les délais et modalités de paiement", C: "Fixer les prix des produits à l'export", D: "Imposer les normes de qualité" },
      ok: "A", ex: "Même question qu'en 2024 : la bonne réponse est passée de C à A. Les modalités de paiement (B) relèvent du contrat de vente et du crédit documentaire." },
    { src: B(10), conf: "S", q: "Dans la balance commerciale d'un pays, un excédent signifie que :",
      o: { A: "Les exportations sont supérieures aux importations", B: "Les importations sont supérieures aux exportations", C: "Les dépenses publiques sont supérieures aux recettes", D: "Aucune bonne réponse" },
      ok: "A", ex: "Solde commercial = exportations − importations de biens ; excédent s'il est positif. C décrit un déficit budgétaire. En 2024, la même réponse était en D." },
    { src: B(53), conf: "S", q: "Quelles informations figurent généralement sur une facture commerciale ?",
      o: { A: "Les noms des autorités douanières des deux pays", B: "La description, la quantité et la valeur des marchandises", C: "Les détails de l'emballage des marchandises", D: "Les ports d'origine et de destination de l'expédition" },
      ok: "B", ex: "Vendeur, acheteur, désignation, quantité, prix unitaire, valeur totale, Incoterm, conditions de paiement. Le détail de l'emballage figure sur la liste de colisage (packing list)." },
    { src: B(58), conf: "S", q: "Quel terme décrit la pratique consistant à s'approvisionner en matériaux et en produits dans les pays où les coûts de main-d'œuvre sont les plus bas ?",
      o: { A: "Approvisionnement local", B: "Nearshoring", C: "Offshoring", D: "Lowshoring" },
      ok: "C", ex: "Offshoring : produire ou s'approvisionner dans des pays lointains à bas salaires. Nearshoring : dans un pays proche (le Maroc pour l'Europe). Reshoring : relocalisation dans le pays d'origine. « Lowshoring » n'est pas un terme usuel." },
    { src: B(60), conf: "S", q: "Le document utilisé pour prouver la propriété des marchandises lors du transport international par voie maritime est …",
      o: { A: "Facture commerciale", B: "Certificat d'origine", C: "Bon de livraison", D: "Connaissement (Bill of Landing)" },
      ok: "D", ex: "Le connaissement (bill of lading ; le sujet écrit « Landing ») est à la fois reçu des marchandises, preuve du contrat de transport maritime et titre de propriété négociable. Aérien : LTA ; route : lettre de voiture CMR, non négociables." },
  ],

  // ───────────────────────── Partie 3 · Contrôle de gestion, stocks et recherche opérationnelle
  3: [
    { src: B(12), conf: "S", q: "Le contrôle de gestion logistique a pour principal objectif :",
      o: { A: "D'optimiser uniquement les coûts d'achat", B: "D'assurer la rentabilité des investissements financiers", C: "De suivre les coûts et les performances des flux physiques et d'information", D: "De contrôler la qualité des produits finis avant expédition" },
      ok: "C", ex: "Mesurer et piloter coûts et performance des flux : coût par commande, délai, taux de service, taux de remplissage. A est trop étroit (« uniquement »), D relève du contrôle qualité." },
    { src: B(13), conf: "S", q: "Selon Michael Porter, la chaîne de valeur permet au contrôle de gestion de :",
      o: { A: "Identifier uniquement les coûts de production", B: "Déterminer le seuil de rentabilité", C: "Calculer le coût unitaire de transport", D: "Analyser les activités créatrices de valeur et les sources de compétitivité" },
      ok: "D", ex: "Porter découpe l'entreprise en activités principales (logistique interne, production, logistique externe, commercialisation et vente, services) et de soutien, pour repérer celles qui créent de la valeur et fondent l'avantage concurrentiel." },
    { src: B(14), conf: "S", q: "Dans la méthode des centres d'analyse, le coût d'un centre auxiliaire est :",
      o: { A: "Réparti sur les centres principaux avant l'imputation aux produits", B: "Directement affecté au produit.", C: "Réparti sur d'autres centres auxiliaires uniquement.", D: "Non pris en compte dans le calcul du coût de revient" },
      ok: "A", ex: "Répartition primaire (charges indirectes vers tous les centres), puis secondaire (centres auxiliaires vers centres principaux), puis imputation aux coûts par unité d'œuvre. Les prestations entre auxiliaires existent (prestations croisées), mais elles finissent toujours sur les centres principaux." },
    { src: B(15), conf: "P", q: "Dans une démarche de pilotage par les coûts, le coût de stockage unitaire peut être réduit principalement par :",
      o: { A: "La réduction du délai de rotation des stocks", B: "L'augmentation du niveau de stock de sécurité", C: "L'augmentation de la capacité d'entreposage", D: "La diminution du coût d'achat" },
      ok: "A", ex: "Un stock qui tourne plus vite reste moins longtemps en entrepôt : chaque unité supporte moins de frais de possession. B et C augmentent les coûts ; D baisse un peu le coût de possession (calculé sur la valeur du stock), mais c'est d'abord le coût d'achat qui baisse." },
    { src: B(16), conf: "S", q: "La marge commerciale est égale à :",
      o: { A: "Chiffre d'affaires − Coût d'achat des marchandises stockées", B: "Chiffre d'affaires − Coût d'achat des marchandises vendues", C: "Chiffre d'affaires − Coût d'achat des marchandises achetées", D: "Chiffre d'affaires − Charges d'exploitation" },
      ok: "B", ex: R`Marge commerciale $=$ ventes de marchandises $-$ coût d'achat des marchandises vendues, avec $\text{CAMV} = \text{achats} + SI - SF$ (achats − variation de stock). C oublie la variation de stock.` },
    { src: B(17), conf: "P", q: "Dans une approche Activity-Based Costing (ABC) appliquée à la logistique, le facteur clé de répartition d'un coût d'expédition est le plus souvent :",
      o: { A: "Le nombre de salariés du service logistique", B: "Le nombre de commandes expédiées", C: "La valeur des ventes réalisées", D: "Le nombre de kilomètres parcourus" },
      ok: "B", ex: "En ABC, le coût de l'activité « expédier » se répartit par son inducteur, ce qui génère le travail : le nombre de commandes (ou d'expéditions). Les kilomètres (D) seraient l'inducteur de l'activité « transporter », pas « expédier »." },
    { src: B(19), conf: "S", q: "Le contrôle budgétaire en logistique permet principalement de :",
      o: { A: "Comparer les réalisations aux prévisions pour analyser les écarts", B: "Déterminer le seuil de rentabilité", C: "Fixer le prix de vente des produits finis", D: "Calculer les amortissements" },
      ok: "A", ex: "Contrôle budgétaire : réalisations − prévisions = écarts, puis analyse des causes et actions correctives." },
    { src: B(20), conf: "S", q: "Le coût de revient logistique d'un produit comprend généralement :",
      o: { A: "Uniquement les coûts de production", B: "Les charges financières et exceptionnelles", C: "Les frais de recherche et développement", D: "Les coûts d'achat, de stockage, de transport et de distribution" },
      ok: "D", ex: "Approvisionnement + stockage + transport + distribution. Les charges exceptionnelles (B) sont des charges non incorporables en comptabilité analytique." },
    { src: B(21), conf: "S", q: "La méthode ABC se focalise sur :",
      o: { A: "Le volume d'unité d'œuvre", B: "L'inducteur d'activité", C: "Le coût d'achat des matières premières", D: "La répartition des charges fixes selon le chiffre d'affaires" },
      ok: "B", ex: "ABC (Activity-Based Costing) : ressources → activités → produits, par les inducteurs d'activité. L'unité d'œuvre volumique (A) est l'outil de la méthode des centres d'analyse." },
    { src: B(22), conf: "S", q: "Dans une démarche de logistique durable, le contrôle de gestion doit :",
      o: { A: "Intégrer les indicateurs environnementaux et sociaux dans les tableaux de bord", B: "Remplacer les KPI économiques par des KPI écologiques", C: "Réduire la fréquence des contrôles budgétaires", D: "Éliminer les coûts non conformes" },
      ok: "A", ex: "On ajoute (CO₂ par tonne-kilomètre, taux de remplissage, accidents du travail), on ne remplace pas : B est faux à cause de « remplacer »." },
    { src: B(23), conf: "P", q: "L'écart total :",
      o: { A: "Est la somme de tous les écarts sur coûts", B: "Est synonyme de l'écart global", C: "Désigne l'écart sur chiffre d'affaires", D: "Est égal à la différence entre le coût constaté pour la production réelle et le coût prévu pour la production réelle" },
      ok: "D", ex: "Écart total (ou global) = coût réel − coût préétabli de la production réelle ; il se décompose en écart sur quantité et écart sur prix. B est exact dans beaucoup de manuels, mais D est la seule proposition qui définit la notion : c'est la réponse attendue." },
    { src: B(24), conf: "S", q: "Dans le modèle du Balanced Scorecard, la performance logistique relève principalement de la perspective :",
      o: { A: "Financière", B: "Client", C: "Processus internes", D: "Apprentissage et innovation" },
      ok: "C", ex: "Kaplan et Norton : quatre perspectives (financière, clients, processus internes, apprentissage). Délais, qualité de livraison, productivité des entrepôts : processus internes." },
    { src: A(73), conf: "S", q: "In inventory management, Wilson's model is also known as the :",
      o: { A: "Economic Order Quantity (EOQ)", B: "Gestion Prévisionnelle des Stocks (GPS)", C: "Gestion Tactique des Stocks (GTS)", D: "Stock Order Management (SOM)" },
      ok: "A", ex: R`Wilson calcule la quantité économique de commande : $Q^* = \sqrt{2 D C_c / C_p}$. Les trois autres sigles n'existent pas.` },
    { src: A(76), conf: "S", q: R`Laquelle de ces paires est une solution optimale du programme linéaire : $\min\ x_1 + 2x_2$ s.c. $3x_1 + x_2 \geq 7$ ; $x_1 + 4x_2 \geq 6$ ; $x_1, x_2 \geq 0$ ?`,
      o: { A: "(2, 1)", B: "(1, 4)", C: "(6, 0)", D: "(0, 7)" },
      ok: "A", ex: R`Les quatre couples sont admissibles ; on compare $z = x_1 + 2x_2$ : 4, 9, 6 et 14. Le minimum est $z = 4$ en (2, 1), intersection des deux droites de contrainte ($3x_1 + x_2 = 7$ et $x_1 + 4x_2 = 6$), donc un sommet du domaine.` },
    { src: A(77), conf: "S", q: R`Les inéquations suivantes définissent une région de solutions admissibles. Laquelle peut-on enlever sans changer le domaine ? (A) $x_1 - 2x_2 \geq -8$ ; (B) $-x_1 + x_2 \leq 10$ ; (C) $x_2 \geq 0$ ; (D) $x_1 + x_2 \leq 20$`,
      o: { A: R`$x_1 - 2x_2 \geq -8$`, B: R`$-x_1 + x_2 \leq 10$`, C: R`$x_2 \geq 0$`, D: R`$x_1 + x_2 \leq 20$` },
      ok: "B", ex: R`De A : $x_1 \geq 2x_2 - 8$. Comme $x_2 \geq 0$, $2x_2 - 8 \geq x_2 - 10$ (car $x_2 + 2 > 0$). Donc $x_1 \geq x_2 - 10$, soit $-x_1 + x_2 \leq 10$ : la contrainte B découle de A et C, elle est redondante. Sans A, le point $(-9, 0)$ deviendrait admissible.` },
    { src: A(78), conf: "V", q: "Une solution optimale d'un programme linéaire d'optimisation est une :",
      o: { A: "Solution réalisable", B: "Solutions faisables", C: "Solution optimale qui satisfait toutes les contraintes du programme", D: "Les deux réponses sont justes" },
      ok: "D", ex: "Une solution optimale est réalisable (A) et satisfait toutes les contraintes (C) : « les deux réponses sont justes » vise A et C. La formulation du sujet est maladroite (B dit la même chose que A au pluriel) : si ta grille n'accepte qu'une réponse, D reste la plus complète." },
    { src: A(80), conf: "S", q: "L'économie d'échelle correspond à :",
      o: { A: "Un résultat positif", B: "Des impôts latents", C: "Répartition du coût fixe sur un nombre élevé de produits, permettant de réduire le coût de revient", D: "Aucune bonne réponse" },
      ok: "C", ex: "Quand la production augmente, le coût fixe se répartit sur plus d'unités : le coût de revient unitaire baisse. C'est l'argument de la standardisation en marketing international." },
    { src: B(18), conf: "S", q: "Dans le modèle de Wilson, le nombre optimal de commandes est obtenu lorsque :",
      o: { A: "le coût de lancement est nul", B: "le coût de stockage et le coût de lancement sont égaux", C: "il n'y a pas de rupture de stock", D: "le coût de stockage est nul" },
      ok: "B", ex: R`Au point de Wilson, coût de possession $= \frac{Q}{2} C_p$ et coût de passation $= \frac{D}{Q} C_c$ sont égaux ; le coût total est alors minimal. On en tire $N^* = \sqrt{\frac{D\,C_p}{2\,C_c}}$ commandes par an.` },
  ],

  // ───────────────────────── Partie 4 · Finance d'entreprise et mathématiques financières
  4: [
    { src: A(1), conf: "S", q: "L'analyse du tableau de financement permet :",
      o: { A: "D'apprécier la rentabilité de l'entreprise.", B: "D'étudier l'évolution de l'équilibre financier.", C: "De connaître les politiques financières de l'entreprise.", D: "D'évaluer le degré de liquidité de l'entreprise." },
      ok: "B", ex: "Le tableau de financement (tableau des emplois et ressources du CGNC) explique la variation du fonds de roulement et de la trésorerie entre deux bilans : l'évolution de l'équilibre financier. La rentabilité se lit dans le CPC, la liquidité dans le bilan financier." },
    { src: A(2), conf: "S", q: "L'élaboration du bilan financier se fait dans l'hypothèse :",
      o: { A: "De la liquidation de l'entreprise.", B: "De la continuité de l'exploitation.", C: "De la restructuration de l'entreprise.", D: "De la croissance de l'entreprise." },
      ok: "A", ex: "Le bilan financier (ou bilan liquidité) adopte l'optique patrimoniale : que vaudraient les actifs, que faudrait-il payer, si l'entreprise était liquidée ? La continuité (B) est l'hypothèse du bilan fonctionnel." },
    { src: A(3), conf: "S", q: "Pour l'élaboration du bilan financier, le retraitement du résultat de l'exercice consiste à :",
      o: { A: "Intégrer la partie mise en réserve dans les fonds propres et considérer les dividendes distribués aux actionnaires comme une dette à court terme vis-à-vis de ceux-ci.", B: "Considérer le résultat comme une partie des fonds propres.", C: "Intégrer la partie du résultat hors impôt aux fonds propres et considérer l'impôt comme une dette à long terme envers l'État.", D: "Aucune de ces réponses" },
      ok: "A", ex: "Réserves → capitaux propres ; dividendes à verser → dettes à moins d'un an. B oublie la distribution ; l'impôt n'est pas une dette à long terme (C)." },
    { src: A(4), conf: "P", q: "L'excédent brut d'exploitation représente :",
      o: { A: "Un résultat qui traduit les opérations d'exploitation de l'entreprise.", B: "Un résultat net qui traduit les opérations financières de l'entreprise.", C: "Un résultat économique non influencé par la politique d'amortissement et la fiscalité", D: "Aucune de ces réponses" },
      ok: "C", ex: "L'EBE se calcule avant dotations, charges financières et impôt sur les résultats : il ne dépend ni de la politique d'amortissement, ni du financement, ni de la fiscalité. A est vrai aussi, mais décrit tout autant le résultat d'exploitation ; C est la caractéristique propre de l'EBE." },
    { src: A(5), conf: "V", q: "Le cash-flow correspond à :",
      o: { A: "La différence entre les produits et les charges d'un exercice comptable.", B: "La somme des produits encaissables et des charges décaissables", C: "La différence entre la capacité d'autofinancement et la variation du besoin en fonds de roulement.", D: "La différence entre les encaissements et les décaissements." },
      ok: "D", ex: "Au sens strict, un cash-flow est un flux de trésorerie : encaissements − décaissements. C (CAF − ΔBFR) donne l'excédent de trésorerie d'exploitation : si ton cours définit le cash-flow comme flux d'exploitation, C serait attendu. A est le résultat comptable." },
    { src: A(6), conf: "S", q: "Le Crowdfunding est un financement :",
      o: { A: "Par la foule", B: "Qui s'apparente au capital-risque", C: "Par les banques participatives", D: "Aucune de ces réponses" },
      ok: "A", ex: "Financement participatif : de nombreux particuliers apportent de petites sommes via une plateforme (don, prêt ou capital). Au Maroc : loi 15-18 sur le financement collaboratif." },
    { src: A(7), conf: "S", q: "Dans le remboursement des obligations, un amortissement in fine signifie que l'emprunteur :",
      o: { A: "Verse les intérêts annuellement et le capital est remboursé en une fois à la fin de la durée de l'emprunt.", B: "Rembourse chaque année un montant constant comprenant le capital et les intérêts.", C: "Rembourse chaque année une partie des obligations de manière aléatoire.", D: "Aucune de ces réponses" },
      ok: "A", ex: "In fine : intérêts chaque année, capital en une fois à l'échéance. B décrit les annuités constantes ; C le remboursement par tirage au sort." },
    { src: A(8), conf: "S", q: "Le capital-développement est formé de capital-risque qui consiste en :",
      o: { A: "Un financement de l'expansion de l'activité d'une entreprise qui présente un fort potentiel de croissance.", B: "Une prise de participation visant à financer le démarrage de l'activité d'une entreprise innovante.", C: "Un financement de la restructuration d'une entreprise qui a atteint la phase finale de son développement.", D: "Aucune de ces réponses" },
      ok: "A", ex: "Stades du capital-investissement : amorçage et création (B), développement (A : expansion d'une entreprise déjà rentable), transmission (LBO) et retournement (C)." },
    { src: A(9), conf: "P", q: "Les revenus des placements des excédents de trésorerie en OPCVM sont :",
      o: { A: "Exonérés de tout impôt", B: "Imposables à l'IS ou à l'IR selon la forme juridique de l'entreprise", C: "Imposables à la taxe sur la valeur ajoutée", D: "Aucune de ces réponses" },
      ok: "B", ex: "Ce sont des produits financiers : ils entrent dans le résultat fiscal soumis à l'IS pour une société, et relèvent de l'IR pour une personne physique. Pas de TVA sur un revenu de placement. Les régimes particuliers (abattements, retenue à la source) ne changent pas le principe." },
    { src: A(10), conf: "S", q: "Dans le remboursement d'un emprunt selon la modalité de l'amortissement constant, l'annuité est :",
      o: { A: "Constante", B: "Dégressive", C: "Progressive.", D: "Aucune de ces réponses" },
      ok: "B", ex: R`Part de capital identique chaque année, capital restant dû en baisse, donc intérêts en baisse : annuité $=$ amortissement constant $+$ intérêts décroissants, elle est dégressive. Exemple : 100 000 sur 4 ans à 10 % → 35 000, 32 500, 30 000, 27 500.` },
    { src: A(29), conf: "S", q: "Le FRF (Fonds de Roulement Fonctionnel) sert à :",
      o: { A: "Financer l'actif immobilisé", B: "Rembourser les dettes", C: "Alimenter la trésorerie", D: "Financer une partie du BFG" },
      ok: "D", ex: R`FRF $=$ ressources stables $-$ emplois stables : c'est ce qui reste des ressources durables une fois les immobilisations financées. Il finance le BFG ; le reste alimente la trésorerie : $TN = FRF - BFG$. A est faux : l'actif immobilisé est déjà financé avant de calculer le FRF.` },
    { src: A(30), conf: "S", q: "Le BFG est négatif :",
      o: { A: "Si les ressources circulantes sont inférieures aux emplois circulants", B: "Si les ressources circulantes sont supérieures aux emplois circulants", C: "Si la trésorerie nette est négative", D: "Jamais" },
      ok: "B", ex: "BFG = emplois circulants − ressources circulantes : négatif quand les dettes circulantes dépassent stocks et créances (grande distribution : clients payés comptant, fournisseurs à 60 jours). Ce n'est pas lié au signe de la trésorerie (C)." },
    { src: A(50), conf: "S", q: "Quel est le montant futur accumulé après 5 ans si l'on place 1 000 DH à un taux d'intérêt simple de 5 % par an ?",
      o: { A: "1 250 DH", B: "1 500 DH", C: "2 000 DH", D: "2 500 DH" },
      ok: "A", ex: R`Intérêts simples : $C_n = C_0(1 + n\,i) = 1\,000 \times (1 + 5 \times 0{,}05) = 1\,250$ DH. En intérêts composés : $1\,000 \times 1{,}05^5 \approx 1\,276{,}28$, absent des options.` },
    { src: A(51), conf: "S", q: "Quelle est la formule pour calculer la valeur actuelle (VA) d'un montant futur (MF) dans un régime d'intérêt composé ?",
      o: { A: R`$VA = MF \times (1 + i)^t$`, B: R`$VA = MF \div (1 + i)^t$`, C: R`$VA = MF \times (1 - i)^t$`, D: R`$VA = MF \div (1 - i)^t$` },
      ok: "B", ex: R`Capitalisation : $MF = VA (1 + i)^t$. Actualiser, c'est diviser : $VA = MF (1 + i)^{-t}$. A est la formule de capitalisation.` },
  ],

  // ───────────────────────── Partie 5 · Statistique, probabilités et estimation
  5: [
    { src: A(11), conf: "S", q: "Une variable est quantitative :",
      o: { A: "Si ses modalités ne sont pas mesurables ;", B: "Si ses modalités sont mesurables et se prêtent au calcul mathématique ;", C: "Si ses modalités sont ordonnées par ordre croissant", D: "Aucune de ces réponses" },
      ok: "B", ex: "Quantitative : on peut mesurer et calculer (moyenne, somme). C décrit une variable qualitative ordinale (mention : passable, bien, très bien)." },
    { src: A(12), conf: "S", q: "Une variable est discrète :",
      o: { A: "Si ses modalités sont des états non chiffrables ;", B: "Si elle porte des valeurs discontinues ;", C: "Si ses modalités ne sont pas quantifiables ;", D: "Aucune de ces réponses" },
      ok: "B", ex: "Discrète : valeurs isolées, en général entières (nombre d'enfants, de salariés, de conteneurs). A et C décrivent une variable qualitative." },
    { src: A(13), conf: "S", q: "Une variable est continue :",
      o: { A: "Si ses modalités ne sont pas chiffrables ;", B: "Si ses valeurs appartiennent à des intervalles ;", C: "Si ses modalités sont des états nominaux ;", D: "Si ses valeurs prennent uniquement des valeurs entières." },
      ok: "B", ex: "Continue : toute valeur d'un intervalle (poids, délai, chiffre d'affaires) ; les données se regroupent en classes. D décrit au contraire une variable discrète." },
    { src: A(14), conf: "S", q: "Tableau 1 : 200 entreprises selon le nombre de salariés recrutés Y (40 : 0,100 ; 60 : 0,225 ; 80 : 0,400 ; 100 : 0,150 ; 140 : 0,125). Y est :",
      o: { A: "Une variable qualitative", B: "Un caractère discret", C: "Un caractère continu", D: "Une variable nominale ordonnée" },
      ok: "B", ex: "Un nombre de salariés est un comptage : valeurs isolées 40, 60, 80… C'est un caractère quantitatif discret." },
    { src: A(15), conf: "S", q: "Selon le tableau 1, le nombre total des salariés recrutés est égal à :",
      o: { A: "15 400 salariés", B: "16 400 salariés", C: "17 400 salariés", D: "18 500 salariés" },
      ok: "B", ex: R`Effectifs $n_i = 200 f_i$ : 20, 45, 80, 30, 25. $\sum n_i y_i = 800 + 2\,700 + 6\,400 + 3\,000 + 3\,500 = 16\,400$ salariés.` },
    { src: A(16), conf: "S", q: "Selon le tableau 1, au moins 80 salariés ont été recrutés par :",
      o: { A: "120 entreprises", B: "130 entreprises", C: "135 entreprises", D: "140 entreprises" },
      ok: "C", ex: R`« Au moins 80 » $= \{80, 100, 140\}$ : $f = 0{,}400 + 0{,}150 + 0{,}125 = 0{,}675$, soit $0{,}675 \times 200 = 135$ entreprises.` },
    { src: A(17), conf: "S", q: "Selon le tableau 1, le mode de Y est égal à :",
      o: { A: "60 salariés", B: "80 salariés", C: "100 salariés", D: "80 entreprises" },
      ok: "B", ex: "Le mode est la modalité de plus forte fréquence (0,400) : Y = 80 salariés. D est le piège : 80 est aussi l'effectif de cette modalité, mais le mode s'exprime dans l'unité de Y." },
    { src: A(18), conf: "S", q: "Selon le tableau 1, la médiane de Y est égale à :",
      o: { A: "40 salariés", B: "60 salariés", C: "80 salariés", D: "100 salariés" },
      ok: "C", ex: "Fréquences cumulées : 0,100 ; 0,325 ; 0,725 ; 0,875 ; 1. Le seuil de 0,5 est franchi à Y = 80 : médiane = 80 salariés." },
    { src: A(19), conf: "S", q: "Selon le tableau 1, la moyenne de Y est égale à :",
      o: { A: "60 salariés", B: "80 salariés", C: "82 salariés", D: "100 salariés" },
      ok: "C", ex: R`$\bar{Y} = \sum f_i y_i = 4 + 13{,}5 + 32 + 15 + 17{,}5 = 82$ salariés. Contrôle : $16\,400 / 200 = 82$.` },
    { src: A(20), conf: "S", q: "Tableau 2 : marchandises importées, prix 2,75 en 2022 et 2,6 en 2023. L'indice prix des marchandises importées en 2023 par rapport à 2022 est égal à :",
      o: { A: "90,5 %", B: "94,5 %", C: "99,5 %", D: "112,5 %" },
      ok: "B", ex: R`Indice élémentaire $= \frac{P_{2023}}{P_{2022}} \times 100 = \frac{2{,}6}{2{,}75} \times 100 = 94{,}55$ : environ 94,5 %, soit une baisse de prix de 5,5 %.` },
    { src: A(21), conf: "S", q: "Tableau 2 : appareils importés, 250 en 2022 et 150 en 2023. La quantité importée des appareils a connu :",
      o: { A: "Une augmentation de 40 % en 2023 par rapport à 2022", B: "Une baisse de 20 % en 2023 par rapport à 2022.", C: "Une baisse de 40 % en 2023 par rapport à 2022", D: "Une augmentation de 20 % en 2023 par rapport à 2022" },
      ok: "C", ex: R`Taux de variation $= \frac{150 - 250}{250} = -0{,}40$ : baisse de 40 %.` },
    { src: A(22), conf: "P", q: "Quel est le deuxième théorème fondamental de la statistique ?",
      o: { A: "La loi normale centrée et réduite.", B: "Autre.", C: "La méthode de l'estimation du maximum de vraisemblance.", D: "Le théorème de la limite centrale." },
      ok: "D", ex: "Les deux théorèmes fondamentaux : la loi des grands nombres (premier) et le théorème central limite (deuxième), selon lequel la moyenne d'un grand échantillon suit approximativement une loi normale. La numérotation varie selon les cours : d'où « probable »." },
    { src: A(23), conf: "S", q: "Qu'est-ce qu'un estimateur de la variable aléatoire ?",
      o: { A: "Une fonction de variable aléatoire réelle.", B: "Une valeur estimée de l'échantillon.", C: "Une variable aléatoire indépendante.", D: "Une valeur certaine de l'échantillon." },
      ok: "A", ex: R`Un estimateur est une fonction des variables de l'échantillon, $T = g(X_1, \dots, X_n)$ : c'est lui-même une variable aléatoire. Sa valeur calculée sur un échantillon observé (B) s'appelle une estimation.` },
    { src: A(24), conf: "S", q: "Quelle est la définition d'un estimateur non biaisé ?",
      o: { A: "L'estimateur est sans biais lorsque sa variance est nulle.", B: "L'estimateur est sans biais lorsque son biais n'est pas nul.", C: "L'estimateur est sans biais lorsque son espérance est égale au paramètre à estimer.", D: "Lorsque l'échantillon est de grande taille." },
      ok: "C", ex: R`Biais $= E(T) - \theta$. Sans biais : $E(T) = \theta$. En 2025, la même définition revient avec « moyenne » à la place d'« espérance » (réponse B).` },
    { src: A(25), conf: "P", q: "Qu'est-ce que le risque quadratique minimum d'un estimateur ?",
      o: { A: "La dispersion de l'estimateur autour de la valeur à estimer est minimale.", B: "La variance de l'estimateur est minimale.", C: "Le biais de l'estimateur est minimal.", D: "Autres conditions." },
      ok: "A", ex: R`$R(T) = E[(T - \theta)^2] = V(T) + b(T)^2$ mesure la dispersion autour de la vraie valeur $\theta$. Il ne se réduit à la variance (B) que pour un estimateur sans biais.` },
    { src: A(26), conf: "S", q: "Quelle est la définition d'un estimateur consistant ?",
      o: { A: "L'estimateur converge vers la valeur du paramètre lorsque l'échantillon devient grand.", B: "L'estimateur est sans biais et sa variance est minimale.", C: "L'estimateur est indépendant de la taille de l'échantillon.", D: "Toutes les variables sont indépendantes et suivent la même loi." },
      ok: "A", ex: R`Consistant (convergent) : $T_n \to \theta$ en probabilité quand $n \to \infty$. B définit un estimateur efficace ; D décrit un échantillon i.i.d.` },
    { src: A(27), conf: "P", q: "Qu'est-ce que l'information de Fisher ?",
      o: { A: "La quantité qui mesure la dispersion de l'estimateur autour de la valeur à estimer.", B: "La quantité qui mesure la précision de l'estimateur.", C: "La quantité qui mesure la qualité de l'estimateur.", D: "Autre." },
      ok: "B", ex: R`$I_n(\theta)$ mesure l'information que l'échantillon apporte sur $\theta$. Plus elle est grande, plus un estimateur sans biais peut être précis, puisque $V(T) \geq 1/I_n(\theta)$. A décrit le risque quadratique.` },
    { src: A(28), conf: "S", q: "Qu'est-ce que la borne de Cramer-Rao ?",
      o: { A: "Une borne supérieure de la variance de l'estimateur.", B: "Une borne supérieure du biais de l'estimateur.", C: "Autre.", D: "Une borne inférieure de la variance de l'estimateur." },
      ok: "D", ex: R`Pour tout estimateur sans biais : $V(T) \geq \frac{1}{I_n(\theta)}$. Borne inférieure de la variance ; un estimateur qui l'atteint est efficace.` },
    { src: B(29), conf: "S", q: "La loi hypergéométrique s'applique lorsque :",
      o: { A: "Les tirages sont indépendants", B: "On a un grand nombre d'essais", C: "La probabilité reste constante", D: "Les tirages se font sans remise" },
      ok: "D", ex: "Tirages sans remise dans une population finie : la composition change à chaque tirage, donc les tirages ne sont pas indépendants et la probabilité varie (A et C décrivent la loi binomiale, avec remise)." },
    { src: B(30), conf: "S", q: R`Soit $E = \{a, b, c, d\}$. Le cardinal de l'ensemble des parties $\mathcal{P}(E)$ est :`,
      o: { A: R`$2 \times 4 = 8$`, B: R`$2^4 = 16$`, C: R`$4! = 24$`, D: R`$4^2 = 16$` },
      ok: "B", ex: R`Chaque élément est dans la partie ou n'y est pas : $2^n = 2^4 = 16$. D donne aussi 16 par hasard, mais avec une formule fausse : pour 3 éléments, $2^3 = 8$ alors que $3^2 = 9$.` },
    { src: B(31), conf: "S", q: "Le nombre de groupes de 3 élèves qu'on peut former dans une classe de 10 élèves est :",
      o: { A: R`$\frac{10!}{3!\,7!} = 120$`, B: R`$10^3 = 1000$`, C: R`$\frac{10!}{(10-3)!} = 720$`, D: R`$3! = 6$` },
      ok: "A", ex: R`Un groupe ne tient pas compte de l'ordre : $C_{10}^3 = \frac{10!}{3!\,7!} = 120$. C (720) compte les arrangements, où l'ordre compte : $A_{10}^3 = 3! \times C_{10}^3$.` },
    { src: B(32), conf: "S", q: "Que signifie qu'un estimateur est plus efficace ?",
      o: { A: "Il a une espérance plus élevée", B: "Il a une variance plus faible", C: "Il a un biais plus faible", D: "Aucune bonne réponse" },
      ok: "B", ex: "Entre deux estimateurs sans biais, le plus efficace a la plus petite variance. L'efficace absolu atteint la borne de Cramér-Rao (question de 2024)." },
    { src: B(33), conf: "S", q: "Un estimateur est dit non biaisé si :",
      o: { A: "Sa variance est nulle", B: "Sa moyenne est égale à la vraie valeur du paramètre estimé", C: "Il dépend de la taille de l'échantillon", D: "Son écart-type est minimal" },
      ok: "B", ex: R`$E(T) = \theta$ : son espérance (« moyenne ») est la vraie valeur. Même question qu'en 2024, où la réponse était en C.` },
  ],

  // ───────────────────────── Partie 6 · Économie, Maroc et marketing
  6: [
    { src: B(25), conf: "S", q: "Quel type de discrimination permet au monopole d'appliquer un prix différent pour chaque unité vendue ?",
      o: { A: "Discrimination du second degré", B: "Discrimination du troisième degré", C: "Discrimination parfaite", D: "Aucune des réponses n'est juste" },
      ok: "C", ex: "Premier degré (parfaite) : chaque unité au prix maximal que l'acheteur accepte. Second degré : prix selon la quantité achetée. Troisième degré : prix selon le groupe de clients (étudiants, seniors)." },
    { src: B(26), conf: "S", q: "La pente d'une courbe d'indifférence est appelée :",
      o: { A: "Taux marginal de substitution", B: "Élasticité prix de la demande", C: "Taux de croissance du revenu", D: "Taux de satisfaction absolu" },
      ok: "A", ex: R`En valeur absolue, la pente est le TMS : $TMS_{1/2} = \frac{U'_1}{U'_2}$, quantité de bien 2 à laquelle on renonce pour une unité de bien 1 de plus.` },
    { src: B(27), conf: "S", q: "L'équilibre du consommateur correspond au point où :",
      o: { A: "Le revenu est maximal", B: "La satisfaction est maximale sous contrainte de revenu", C: "Le TMS est nul", D: "La courbe d'indifférence est la plus éloignée de l'origine" },
      ok: "B", ex: R`Maximiser l'utilité sous la contrainte budgétaire : point de tangence où $TMS = \frac{p_1}{p_2}$. D est incomplet tant que la contrainte de revenu n'est pas mentionnée.` },
    { src: B(28), conf: "S", q: "Quel type de monopole est créé par une loi ou un règlement gouvernemental ?",
      o: { A: "Monopole naturel", B: "Monopole technologique", C: "Monopole local", D: "Monopole institutionnel" },
      ok: "D", ex: "Monopole institutionnel (ou légal) : créé par la loi. Le monopole naturel vient des rendements croissants (réseaux), le technologique d'un brevet ou d'une innovation." },
    { src: B(34), conf: "S", q: R`Si le TMS est supérieur à $\frac{p_1}{p_2}$ (où $p_1$ et $p_2$ sont les prix unitaires des biens 1 et 2), alors le consommateur :`,
      o: { A: "Achète plus du bien 2", B: "Est déjà à l'équilibre", C: "Achète plus du bien 1 et moins du bien 2", D: "Ne consomme plus rien" },
      ok: "C", ex: R`$\frac{U'_1}{U'_2} > \frac{p_1}{p_2} \iff \frac{U'_1}{p_1} > \frac{U'_2}{p_2}$ : le dernier dirham rapporte plus en bien 1. Il substitue du bien 1 au bien 2 jusqu'à l'égalité.` },
    { src: A(31), conf: "S", q: "Le cartel se définit par :",
      o: { A: "Concentration financière qui s'effectue par la propriété d'une partie du capital dans différentes entreprises.", B: "Plusieurs entreprises se mettent d'accord sur un objectif particulier pour maximiser le profit en évitant une concurrence sauvage.", C: "Ensemble d'entreprises réunies par des liens juridiques et financiers plus ou moins précis et s'adonnant à des activités très diverses ayant parfois peu de rapport entre elles.", D: "Aucune réponse n'est juste." },
      ok: "B", ex: "Cartel = entente entre entreprises indépendantes (prix, quotas, partage des marchés). A décrit la concentration financière (holding), C le conglomérat. Au Maroc, les ententes sont interdites par la loi 104-12 et sanctionnées par le Conseil de la concurrence." },
    { src: A(62), conf: "S", q: "Quel est le rôle principal de la Banque centrale dans une économie ?",
      o: { A: "Fabriquer des billets et pièces et les mettre à la disposition des ménages", B: "Réguler le taux d'intérêt pour contrôler l'inflation", C: "Accorder des prêts aux entreprises en difficulté", D: "Gérer les comptes bancaires des particuliers" },
      ok: "B", ex: "Elle conduit la politique monétaire en pilotant les taux (taux directeur) pour tenir l'inflation. L'émission de monnaie fiduciaire (A) est une mission réelle mais secondaire ; C et D relèvent des banques commerciales." },
    { src: A(63), conf: "S", q: "Quel est l'objectif principal de la politique monétaire ?",
      o: { A: "Favoriser la croissance économique", B: "Stabiliser les prix", C: "Augmenter l'emploi", D: "Réduire les inégalités" },
      ok: "B", ex: "La stabilité des prix : c'est l'objectif fixé à Bank Al-Maghrib par son statut (loi 40-17). La croissance et l'emploi viennent en appui, sans préjudice de cet objectif." },
    { src: A(64), conf: "S", q: "Quelle institution est responsable de la régulation bancaire au Maroc ?",
      o: { A: "Le trésor public", B: "La Banque centrale", C: "Le Ministère des Finances", D: "L'AMMC" },
      ok: "B", ex: "Bank Al-Maghrib agrée et contrôle les banques et établissements de crédit (loi bancaire 103-12). L'AMMC régule le marché des capitaux, l'ACAPS les assurances." },
    { src: B(45), conf: "S", q: "La politique monétaire vise :",
      o: { A: "La gestion des impôts", B: "La création de dettes publiques", C: "Le contrôle de la masse monétaire et la stabilité des prix", D: "L'augmentation de la masse monétaire" },
      ok: "C", ex: "Contrôle de la masse monétaire (par les taux et les réserves obligatoires) pour la stabilité des prix, objectif de Bank Al-Maghrib (loi 40-17). A et B relèvent de la politique budgétaire ; D n'est qu'un sens possible (expansion)." },
    { src: B(48), conf: "S", q: "La Banque Centrale du Maroc s'appelle :",
      o: { A: "Banque Maghrebine", B: "Bank Al-Maghrib", C: "Banque Africaine", D: "Bank Al-Watani" },
      ok: "B", ex: "Bank Al-Maghrib (BAM), créée en 1959. Elle émet le dirham, conduit la politique monétaire, supervise les banques et gère les réserves de change." },
    { src: A(65), conf: "S", q: "Qu'est-ce qu'un taux d'intérêt directeur ?",
      o: { A: "Le taux auquel les banques prêtent aux particuliers", B: "Le taux auquel la Banque centrale prête aux banques de second rang", C: "Le taux d'intérêt des obligations d'État", D: "Le taux de rendement des actions" },
      ok: "B", ex: "Taux de refinancement des banques par la banque centrale ; il se répercute ensuite sur les taux des crédits. Il est fixé par le conseil de Bank Al-Maghrib à chaque réunion trimestrielle." },
    { src: A(66), conf: "S", q: "Qu'est-ce qu'un actif liquide ?",
      o: { A: "Un bien difficile à vendre", B: "Un bien facilement convertible en espèces", C: "Un bien qui génère des revenus passifs", D: "Un bien avec une valeur volatile" },
      ok: "B", ex: "Liquidité = capacité à se transformer rapidement en monnaie sans perte de valeur (dépôts, titres négociables). L'immobilier est peu liquide." },
    { src: A(67), conf: "S", q: "Quel est l'impact d'une dévaluation du dirham marocain ?",
      o: { A: "Augmentation des importations du Maroc", B: "Diminution des exportations du Maroc", C: "Augmentation de la compétitivité des exportations marocaines", D: "Stabilisation des prix internes" },
      ok: "C", ex: "Les produits marocains deviennent moins chers en devises : exportations plus compétitives. Les importations renchérissent (A est l'inverse) et l'inflation importée augmente (D est faux)." },
    { src: A(68), conf: "P", q: "Quelle est la principale source de financement pour les entreprises au Maroc ?",
      o: { A: "Les fonds propres", B: "Les prêts bancaires", C: "Les subventions publiques", D: "Les investissements étrangers" },
      ok: "B", ex: "Le financement externe des entreprises marocaines repose surtout sur le crédit bancaire ; la Bourse de Casablanca reste peu utilisée, surtout par les PME. L'autofinancement pèse aussi lourd : la question vise le financement externe." },
    { src: A(69), conf: "S", q: "Qu'est-ce que la notion de consommation ostentatoire ?",
      o: { A: "La finalité est exclusivement utilisée pour l'immobilier", B: "La finalité est la consommation utile et économique", C: "La finalité est de manifester la richesse ou le statut social", D: "La finalité est d'identifier son style de vie (quel que soit celui-ci)" },
      ok: "C", ex: "Veblen (1899) : on consomme pour afficher sa richesse et son rang. L'« effet Veblen » : la demande d'un bien de luxe peut monter avec son prix." },
    { src: A(70), conf: "P", q: "Dans la matrice de McKinsey, on utilise 2 critères d'évaluation (chassez l'intrus) :",
      o: { A: "Attrait du marché", B: "Atouts de l'entreprise", C: "Parts de marché", D: "Aucune de ces propositions ne convient" },
      ok: "C", ex: "McKinsey croise l'attrait du marché et les atouts (position concurrentielle) de l'entreprise. L'intrus est la part de marché, axe de la matrice BCG (avec la croissance du marché). Libellé du sujet ambigu : d'où « probable »." },
    { src: A(71), conf: "P", q: "Parmi ces différentes études marketing se cache un intrus, lequel ?",
      o: { A: "Analyse de la concurrence", B: "Analyse de la notoriété", C: "Baromètre de qualité", D: "Lancement de produit" },
      ok: "D", ex: "A, B et C sont des études ; le lancement de produit est une action du marketing opérationnel. On peut faire un « test de lancement », mais la proposition ne le dit pas." },
    { src: A(72), conf: "P", q: "La diversification concentrique, c'est développer une ou plusieurs activités :",
      o: { A: "Nouvelles auprès d'une clientèle nouvelle", B: "Auprès d'une clientèle existante", C: "Complémentaires à un segment produit/marché existant", D: "En imitant la concurrence" },
      ok: "C", ex: "Concentrique (liée) : activités nouvelles mais liées à l'existant (technologie, savoir-faire, circuits). A décrit la diversification conglomérale. B est trop vague pour définir la notion." },
    { src: A(74), conf: "S", q: "Que signifie le terme « standardisation » dans une stratégie de marketing international ?",
      o: { A: "Adapter le produit et la communication en fonction des spécificités de chaque marché.", B: "Appliquer la même stratégie marketing et le même produit dans tous les pays.", C: "Créer de nouveaux produits spécifiques à chaque région.", D: "Utiliser uniquement les normes locales pour s'adapter aux réglementations du marché cible." },
      ok: "B", ex: "Standardiser : même produit, même marketing partout, pour des économies d'échelle. A décrit l'adaptation, son contraire." },
    { src: A(75), conf: "S", q: "Qu'est-ce que le concept de « glocalisation » en marketing international ?",
      o: { A: "La création de produits pour un seul marché.", B: "L'exportation d'un produit sans aucune modification.", C: "L'adaptation de produits globaux aux spécificités locales des marchés.", D: "La délocalisation des activités de production." },
      ok: "C", ex: "« Think global, act local » : un produit mondial adapté aux goûts locaux (menus des chaînes de restauration rapide pendant le Ramadan, par exemple). B est la standardisation." },
    { src: B(43), conf: "S", q: "L'inflation correspond à :",
      o: { A: "Une hausse générale et durable des prix", B: "Une baisse générale des prix", C: "Une stabilité des prix", D: "Une augmentation de la production" },
      ok: "A", ex: "Hausse générale et durable du niveau des prix, mesurée au Maroc par l'indice des prix à la consommation du HCP. B est la déflation." },
    { src: B(44), conf: "S", q: "Une politique budgétaire restrictive consiste à :",
      o: { A: "Augmenter les dépenses publiques", B: "Réduire les dépenses publiques ou augmenter les impôts", C: "Créer plus de monnaie", D: "Stimuler la demande globale" },
      ok: "B", ex: "Restrictive (rigueur) : moins de dépenses publiques ou plus d'impôts, pour réduire le déficit ou freiner la demande. C relève de la politique monétaire ; A et D décrivent une relance." },
    { src: B(46), conf: "S", q: "La croissance économique se mesure généralement par :",
      o: { A: "L'évolution du taux de change", B: "L'évolution du PIB réel", C: "Le déficit commercial", D: "La masse monétaire" },
      ok: "B", ex: "Taux de croissance = variation du PIB réel (en volume, hors effet des prix). Le PIB nominal gonfle avec l'inflation." },
    { src: B(47), conf: "S", q: "Le tourisme représente pour le Maroc :",
      o: { A: "Une source importante de devises", B: "Un secteur marginal", C: "Un secteur en déclin structurel", D: "Une activité réservée aux étrangers" },
      ok: "A", ex: "Avec les transferts des Marocains résidant à l'étranger, les phosphates et l'automobile, le tourisme est l'une des grandes sources de devises du pays." },
    { src: B(49), conf: "S", q: "Le secteur agricole marocain dépend fortement :",
      o: { A: "Des importations de machines", B: "Des industries minières", C: "Des conditions climatiques", D: "Du commerce électronique" },
      ok: "C", ex: "Agriculture en grande partie pluviale : une sécheresse fait chuter la récolte céréalière, et avec elle la croissance du PIB." },
    { src: B(51), conf: "S", q: "Le Maroc importe principalement :",
      o: { A: "Produits électroniques", B: "Produits énergétiques", C: "Phosphates", D: "Textiles" },
      ok: "B", ex: "L'énergie (gasoil, fiouls, gaz, charbon) est le premier poste d'importation : le Maroc importe l'essentiel de son énergie. Les phosphates sont au contraire exportés (OCP)." },
    { src: B(52), conf: "S", q: "Le secteur automobile marocain est principalement développé à :",
      o: { A: "Tanger", B: "Marrakech", C: "Agadir", D: "Rabat" },
      ok: "A", ex: "Tanger : usine Renault de Melloussa et Tanger Automotive City, reliées à Tanger Med. Second pôle : Kénitra (Stellantis, Atlantic Free Zone)." },
    { src: B(54), conf: "S", q: "Le capital humain désigne :",
      o: { A: "Les salariés au sens strict", B: "Les compétences et connaissances de la population", C: "Les infrastructures", D: "Les matières premières" },
      ok: "B", ex: "Becker : compétences, connaissances et savoir-faire qui accroissent la productivité ; ils s'acquièrent par l'éducation, la formation et l'expérience." },
    { src: B(55), conf: "S", q: "Le rôle du vendeur dans une négociation est :",
      o: { A: "Éviter les objections", B: "Limiter la discussion", C: "Imposer son produit", D: "Comprendre et satisfaire les besoins du client" },
      ok: "D", ex: "Vente consultative : découvrir les besoins, argumenter, traiter les objections (pas les éviter), conclure." },
    { src: B(56), conf: "S", q: "Le taux de chômage représente :",
      o: { A: "Le pourcentage de personnes sans emploi et en recherche active", B: "Le nombre de retraités", C: "Les personnes âgées", D: "Les étudiants" },
      ok: "A", ex: R`Taux de chômage $= \frac{\text{chômeurs}}{\text{population active}}$ ; un chômeur est sans emploi, disponible et en recherche active (définition du BIT, reprise par le HCP).` },
    { src: B(57), conf: "S", q: "La balance commerciale du Maroc est généralement :",
      o: { A: "Excédentaire", B: "Équilibrée", C: "Déficitaire", D: "Stable" },
      ok: "C", ex: "Structurellement déficitaire : les importations (énergie, biens d'équipement, céréales) dépassent les exportations. Le déficit est en partie couvert par le tourisme et les transferts des MRE." },
    { src: B(59), conf: "S", q: "La demande globale inclut :",
      o: { A: "Les salaires des fonctionnaires", B: "Les consommations de biens et services", C: "La consommation, l'investissement, les dépenses publiques et les exportations nettes", D: "Les exportations uniquement" },
      ok: "C", ex: R`$DG = C + I + G + (X - M)$. B n'en est qu'une composante.` },
  ],

  // ───────────────────────── Partie 7 · Anglais
  7: [
    { src: A(52), conf: "S", q: "The internet has truly …………… both our time and energy :",
      o: { A: "saved", B: "filled", C: "reduced", D: "protected" },
      ok: "A", ex: "Save time and energy : « économiser » temps et énergie. Reduced (C) se dirait de coûts, pas de « both our time and energy » dans ce sens positif." },
    { src: A(53), conf: "S", q: "Why …………… you come to class last Friday ?",
      o: { A: "don't", B: "didn't", C: "weren't", D: "doesn't" },
      ok: "B", ex: "Last Friday impose le prétérit ; la question se forme avec did + base verbale : Why didn't you come…?" },
    { src: A(54), conf: "S", q: "When did the modern Olympic Games …………… ?",
      o: { A: "starts", B: "started", C: "start", D: "starting" },
      ok: "C", ex: "Après l'auxiliaire did, le verbe reste à la base verbale : did … start. Started ferait une double marque du passé." },
    { src: A(55), conf: "P", q: "A lot of activists are calling for an urgent intervention to …………… the environment.",
      o: { A: "hide", B: "protect", C: "keep", D: "save" },
      ok: "B", ex: "Protect the environment est la collocation usuelle. Save the environment se dit aussi : d'où « probable ». Hide et keep ne conviennent pas." },
    { src: A(56), conf: "S", q: "Our teacher never tells us …………… to do.",
      o: { A: "where", B: "what", C: "who", D: "when" },
      ok: "B", ex: "What + infinitif = ce qu'il faut faire. Where / when to do n'ont pas de complément logique ici." },
    { src: A(57), conf: "S", q: "If you're buying things with Yen, you must be in ……………",
      o: { A: "South Korea", B: "China", C: "Taiwan", D: "Japan" },
      ok: "D", ex: "Le yen est la monnaie du Japon. Chine : yuan (renminbi) ; Corée du Sud : won ; Taïwan : nouveau dollar de Taïwan." },
    { src: A(58), conf: "S", q: "On Saturday, Ali and …………… are going to Spain",
      o: { A: "Mine", B: "My", C: "Me", D: "I" },
      ok: "D", ex: "Sujet du verbe are going : pronom sujet I. Me est complément (with Ali and me)." },
    { src: A(59), conf: "P", q: "The baby is sneezing a lot. She …………… have a cold",
      o: { A: "Should", B: "May", C: "Must", D: "Can" },
      ok: "C", ex: "Déduction quasi certaine à partir d'un indice : must have a cold. May (B) exprime une simple possibilité, défendable mais moins attendue." },
    { src: A(60), conf: "S", q: "Lily: What time is it now Carol? — Carol: It's 10 ……………",
      o: { A: "at night", B: "by night", C: "in the night", D: "of the night" },
      ok: "A", ex: "Expression figée : at night (in the morning, in the afternoon, in the evening, mais at night)." },
    { src: A(61), conf: "S", q: "After they picked up their kids from school, they …………… home",
      o: { A: "drive", B: "drives", C: "drove", D: "are driving" },
      ok: "C", ex: "Récit au passé (picked up) : la suite se met au prétérit, drove (drive, drove, driven)." },
    { src: B(35), conf: "S", q: "The term 'outsourcing' refers to :",
      o: { A: "Using external suppliers", B: "Producing internally", C: "Merging companies", D: "Hiring temporary staff" },
      ok: "A", ex: "Outsourcing = externalisation : confier une activité à un prestataire externe (un 3PL pour la logistique). B est l'insourcing." },
    { src: B(36), conf: "S", q: "'Just-in-time' aims to :",
      o: { A: "Increase inventory", B: "Reduce waste and inventory", C: "Speed up production without control", D: "Raise product prices" },
      ok: "B", ex: "Le juste-à-temps vise à réduire les gaspillages (muda) et les stocks, en produisant au rythme de la demande. Même notion qu'en 2024 (question en français)." },
    { src: B(37), conf: "S", q: "'Procurement' means :",
      o: { A: "Buying goods and services", B: "Transporting goods", C: "Selling abroad", D: "Warehousing" },
      ok: "A", ex: "Procurement = achats et approvisionnement. Warehousing = entreposage ; shipping = expédition." },
    { src: B(38), conf: "S", q: "'SWOT analysis' helps to identify:",
      o: { A: "Strengths, Weaknesses, Opportunities, Threats", B: "Strengths, Weaknesses, Offers, Trends", C: "Systems, Weaknesses, Opportunities, Threats", D: "Strengths, Wastes, Opportunities, Threats" },
      ok: "A", ex: "Forces et faiblesses (internes), opportunités et menaces (externes) : la matrice FFOM en français." },
    { src: B(39), conf: "S", q: "'Benchmarking' means:",
      o: { A: "Comparing with best practices", B: "Analyzing internal HR", C: "Reducing costs", D: "Auditing finances" },
      ok: "A", ex: "Se comparer aux meilleures pratiques d'autres entreprises (étalonnage concurrentiel), pour s'en inspirer." },
    { src: B(40), conf: "S", q: "'KPI' stands for :",
      o: { A: "Knowledge Process Index", B: "Key Planning Item", C: "Key Performance Indicator", D: "Known Product Indicator" },
      ok: "C", ex: "Indicateur clé de performance : taux de service, OTIF (on time in full), coût par commande, rotation des stocks." },
    { src: B(41), conf: "S", q: "'Return on investment' measures:",
      o: { A: "Profitability of an investment", B: "Debt ratio", C: "Market share", D: "Liquidity" },
      ok: "A", ex: R`$ROI = \dfrac{\text{gain} - \text{investissement}}{\text{investissement}}$ : la rentabilité d'un investissement.` },
    { src: B(42), conf: "S", q: "'Corporate social responsibility' (CSR) includes:",
      o: { A: "Financial objectives", B: "Legal compliance", C: "Cost reduction programs", D: "Ethical, social, and environmental commitments" },
      ok: "D", ex: "RSE : engagements éthiques, sociaux et environnementaux, au-delà de la simple conformité légale (B)." },
  ],
};
