// QCM du cahier AIF, classés par partie. conf : S = réponse sûre, P = probable, V = à vérifier, E = entraînement.
const R = String.raw;
const B = (n) => `AIF 2025/26 · Quest. B · Q${n}`;
const C = (n) => `AIF 2025/26 · Quest. C · Q${n}`;
const A22c = (n) => `ACGSI 2022 · Techn. comptables · Q${n}`;
const A22f = (n) => `ACGSI 2022 · Fiscalité · Q${n}`;
const A23c = (n) => `ACGSI 2023 · Techn. comptables · Q${n}`;
const A23tf = (n) => `ACGSI 2023 · Techn. fiscales · Q${n}`;
const A23f = (n) => `ACGSI 2023 · Fiscalité · Q${n}`;
const ENT = "Entraînement SaadConcours (hors annales)";

export const QCM = {
  // ───────────────────────── Partie 1 · Comptabilité générale
  1: [
    { src: B(10), conf: "S", q: "Les avances versées sur l'achat des marchandises sont comptabilisées parmi :",
      o: { A: "les dettes du financement permanent", B: "les dettes du passif circulant", C: "les créances de l'actif immobilisé", D: "les créances de l'actif circulant" },
      ok: "D", ex: "Avances et acomptes versés sur commandes d'exploitation : compte 3411 « Fournisseurs débiteurs, avances et acomptes », à l'actif circulant. Ce sont des créances (l'entreprise attend la livraison), pas des dettes." },
    { src: B(11), conf: "S", q: "Les écarts de conversion passif représentent des :",
      o: { A: "gains latents", B: "gains certains", C: "pertes certaines", D: "pertes latentes" },
      ok: "A", ex: "Écart de conversion passif = gain latent de change (créance en devise dont le cours monte, dette dont le cours baisse). Il n'est pas constaté en produit comptable. L'écart actif est une perte latente, couverte par une provision pour perte de change." },
    { src: B(12), conf: "S", q: "Les actifs fictifs sont dénommés par le plan comptable marocain :",
      o: { A: "charges externes", B: "immobilisations incorporelles", C: "immobilisations en non-valeurs", D: "actifs immatériels" },
      ok: "C", ex: "Le CGNC regroupe les actifs fictifs dans les immobilisations en non-valeurs (rubrique 21) : frais préliminaires, charges à répartir sur plusieurs exercices, primes de remboursement des obligations." },
    { src: B(13), conf: "S", q: "Le principe de prudence :",
      o: { A: "consiste à enregistrer un gain et une perte lorsqu'ils sont probables", B: "consiste à enregistrer la valeur actuelle des biens par prudence", C: "consiste à enregistrer une perte lorsqu'elle est probable", D: "aucune réponse n'est correcte" },
      ok: "C", ex: "Prudence : une perte probable est constatée (provision), un gain n'est enregistré que lorsqu'il est réalisé. A est faux à cause du gain." },
    { src: C(35), conf: "S", q: "Le principe de prudence impose :",
      o: { A: "d'équilibrer le bilan à tout moment", B: "de ne pas anticiper les pertes possibles", C: "de toujours anticiper les produits futurs", D: "de comptabiliser les pertes probables mais pas les gains incertains" },
      ok: "D", ex: "Même principe que la question précédente, formulé autrement : pertes probables constatées, gains incertains ignorés. B et C disent exactement l'inverse." },
    { src: B(14), conf: "P", q: "Lors de la facturation du transport forfaitaire au client :",
      o: { A: "il est un produit d'exploitation accessoire pour le fournisseur", B: "il se traduit par une facture de transport séparée", C: "le fournisseur doit payer une compagnie de transport", D: "aucune réponse n'est correcte" },
      ok: "A", ex: "Un transport facturé forfaitairement au client (le vendeur transporte lui-même ou absorbe le coût réel) est un produit accessoire des ventes pour le fournisseur. Il figure sur la facture de vente, pas sur une facture séparée." },
    { src: C(12), conf: "S", q: "Une facture d'achat donne lieu à l'écriture suivante :",
      o: { A: "Débit : Achats / Crédit : Fournisseurs", B: "Débit : Banque / Crédit : Achats", C: "Débit : Achats / Crédit : Banque", D: "Débit : Fournisseurs / Crédit : Achats" },
      ok: "A", ex: "Achat à crédit : débit 6111 (ou 6121) Achats et 34552 TVA récupérable sur charges, crédit 4411 Fournisseurs. C serait un achat payé comptant, D un avoir." },
    { src: C(13), conf: "S", q: "Quelle opération comptable permet de déterminer la performance nette d'une entité sur un exercice donné ?",
      o: { A: "Addition des produits d'exploitation et des charges externes", B: "Différence entre les emplois et les ressources du bilan", C: "Soustraction des dettes de l'ensemble des capitaux propres", D: "Écart entre les ressources générées et les consommations enregistrées" },
      ok: "D", ex: "Résultat net = produits (ressources générées) − charges (consommations). B et C décrivent des grandeurs du bilan, pas du CPC." },
    { src: C(18), conf: "S", q: "Une dotation aux amortissements est :",
      o: { A: "un produit de l'exercice", B: "une charge de l'exercice", C: "une charge non décaissée et non comptabilisée", D: "une dette financière" },
      ok: "B", ex: "Charge calculée de l'exercice (compte 619) : non décaissée, mais bien comptabilisée. C est faux à cause de « non comptabilisée »." },
    { src: C(11), conf: "P", q: "Expliquez la différence entre l'écart de conversion actif et l'écart de conversion passif.",
      o: { A: "L'écart de conversion actif correspond aux dettes en devises, l'écart de conversion passif aux créances en devises.", B: "Les deux écarts sont identiques et affectent toujours le résultat.", C: "L'écart de conversion actif apparaît sur les créances en devises, l'écart de conversion passif sur les dettes en devises.", D: "L'écart de conversion actif concerne uniquement les stocks importés, le passif uniquement les emprunts étrangers." },
      ok: "C", ex: "Réponse attendue, mais imprécise : l'écart actif est une perte latente, l'écart passif un gain latent, et chacun peut naître sur une créance comme sur une dette. A, B et D sont franchement fausses. Coche C, mais retiens la vraie définition (voir la question sur les gains latents)." },
    { src: C(1), conf: "S", q: "Une entité détient une créance commerciale de 50 000 DH inscrite à l'actif circulant. Suite à des indices de perte de valeur, une estimation prudente prévoit un recouvrement partiel à hauteur de 70 %. Quelle correction de valeur doit être comptabilisée afin de respecter le principe de prudence ?",
      o: { A: "15 000 DH", B: "20 000 DH", C: "10 000 DH", D: "35 000 DH" },
      ok: "A", ex: R`Recouvrement attendu : $70\,\% \times 50\,000 = 35\,000$. Dépréciation : $50\,000 - 35\,000 = 15\,000$ DH (dotation, compte 3942). D (35 000) est le montant récupérable, pas la perte. En pratique, la provision se calcule sur le HT ; l'énoncé ne distinguant pas HT et TTC, on garde 50 000.` },
    { src: B(15), conf: "V", q: "Énoncé commun aux questions 15 à 17 : le 1/6/2024, l'entreprise ALPHA a acquis deux ordinateurs pour son service commercial au prix unitaire TTC de 7 500 DH, à crédit sur 6 mois (TVA 20 %). Durée de vie 5 ans, amortissement linéaire. À l'acquisition, on utilise les comptes suivants :",
      o: { A: "2355 ; 4455 ; 1486", B: "2355 ; 3455 ; 1486", C: "aucune réponse n'est correcte", D: "2355 ; 3455 ; 4411" },
      ok: "C", ex: "Écriture correcte : débit 2355 Matériel informatique 12 500, débit 3455 État, TVA récupérable sur immobilisations 2 500, crédit 4481 Dettes sur acquisitions d'immobilisations 15 000 (crédit à court terme). A utilise 4455 (TVA facturée), D utilise 4411 (fournisseurs d'exploitation). Un correcteur qui range tout fournisseur d'immobilisations en 1486 attendrait B ; selon le CGNC, 1486 est une dette de financement (plus d'un an). En cas de doute, laisse blanc." },
    { src: B(16), conf: "S", q: "Mêmes données. La première annuité d'amortissement est de :",
      o: { A: "1458,33", B: "3000", C: "aucune réponse n'est correcte", D: "2500" },
      ok: "A", ex: R`Base HT : $2 \times 7\,500 / 1{,}2 = 12\,500$ (TVA récupérable sur le matériel informatique). Annuité pleine : $12\,500 / 5 = 2\,500$. Du 1/6 au 31/12, 7 mois : $2\,500 \times \frac{7}{12} = 1\,458{,}33$ DH. D oublie le prorata temporis, B garde le TTC.` },
    { src: B(17), conf: "S", q: "Mêmes données. L'entreprise vend un des deux ordinateurs le 31/12/2024 au prix de 4 000 DH :",
      o: { A: "Elle va réaliser une plus-value de cession de 1000 DH", B: "Elle va réaliser une moins-value de cession de 1000 DH", C: "Aucune réponse n'est correcte", D: "Elle ne va réaliser ni plus-value ni moins-value" },
      ok: "C", ex: R`Un ordinateur : $6\,250$ HT. Amortissement 2024 : $1\,250 \times \frac{7}{12} = 729{,}17$. VNC $= 6\,250 - 729{,}17 = 5\,520{,}83$. Résultat de cession $= 4\,000 - 5\,520{,}83 = -1\,520{,}83$ : moins-value de 1 520,83 DH, absente des options.` },
    { src: B(18), conf: "S", q: "Le client « PLASTIC S.A » figure au 31/12/N dans le tableau des clients douteux pour une créance initiale de 6 000 TTC. Une provision de 50 % a été constituée à la clôture de N. Le 29/10/N+1, il règle pour solde 3 000 DH par chèque. Les écritures suivantes sont passées :",
      o: { A: "perte sur créances irrécouvrables au crédit avec un montant de 2500", B: "perte sur créances irrécouvrables au débit avec un montant de 3000", C: "perte sur créances irrécouvrables au crédit avec un montant de 3000", D: "perte sur créances irrécouvrables au débit avec un montant de 2500" },
      ok: "D", ex: "Créance 6 000 TTC = 5 000 HT + 1 000 TVA. Perte TTC 3 000 = 2 500 HT + 500 de TVA à régulariser. Écriture : débit 5141 Banque 3 000, débit 6182 Pertes sur créances irrécouvrables 2 500, débit 4455 TVA facturée 500, crédit 3424 Clients douteux 6 000. Une perte est toujours au débit." },
    { src: B(19), conf: "S", q: "Mêmes données. La provision pour dépréciation déjà constituée en N :",
      o: { A: "est annulée d'un montant 2500", B: "est annulée d'un montant 1250", C: "est annulée d'un montant 1500", D: "est annulée d'un montant 3000" },
      ok: "A", ex: "La provision portait sur le HT : 50 % × 5 000 = 2 500. Elle devient sans objet : reprise de 2 500 (débit 3942, crédit 7196). D (3 000) la calcule à tort sur le TTC." },
    { src: C(40), conf: "S", q: "Une machine achetée à 200 000 DH, amortie sur 5 ans, est vendue au bout de 3 ans pour 90 000 DH. Quelle est la valeur comptable nette (VCN) au moment de la vente ?",
      o: { A: "80 000 DH", B: "100 000 DH", C: "90 000 DH", D: "120 000 DH" },
      ok: "A", ex: R`Annuité $= 200\,000 / 5 = 40\,000$. VNC $= 200\,000 - 3 \times 40\,000 = 80\,000$ DH. Plus-value de cession : $90\,000 - 80\,000 = 10\,000$. C est le prix de cession, D le cumul des amortissements.` },
    { src: A22c(4), conf: "S", q: "Le 01/07/2022, l'entreprise a contracté un emprunt de 500 000 Dhs. Les intérêts annuels s'élèvent à 36 000 Dhs. Le 31/12/2022, le comptable devra enregistrer dans un compte de régularisation le montant suivant :",
      o: { A: "536 000 Dhs", B: "518 000 Dhs", C: "8 000 Dhs", D: "36 000 Dhs", E: "Aucune réponse" },
      ok: "E", ex: R`Intérêts courus du 1/7 au 31/12 : $36\,000 \times \frac{6}{12} = 18\,000$ DH (intérêts courus et non échus à payer, compte 4493). 18 000 n'est pas proposé ici ; dans la version 2023 du même sujet, il l'est (réponse « 18 000 »).` },
    { src: A22c(6), conf: "P", q: "Une entreprise a acquis un véhicule utilitaire le 31/10/2019 à 480 000 Dhs TTC. Elle a décidé de l'amortir sur 5 ans selon le mode dégressif. Au 31/12/2020, avant inventaire, son cumul d'amortissement s'élève à :",
      o: { A: "40 000 Dhs", B: "26 667 Dhs", C: "48 000 Dhs", D: "184 000 Dhs", E: "88 700 dhs", F: "Aucune réponse" },
      ok: "A", ex: R`TVA récupérable sur un utilitaire : base $480\,000/1{,}2 = 400\,000$. Taux dégressif $= 20\,\% \times 2 = 40\,\%$ (coefficient 2 pour 5 ou 6 ans). En dégressif, l'amortissement court dès le 1er jour du mois d'acquisition : octobre, novembre, décembre = 3 mois. « Avant inventaire 2020 », seul 2019 est passé : $400\,000 \times 40\,\% \times \frac{3}{12} = 40\,000$. B (26 667) compte 2 mois comme en linéaire. Même question en 2017 (un camion) et en 2023 ; en 2023, 40 000 n'est pas proposé : réponse « aucune ».` },
    { src: A22c(7), conf: "S", q: "Dans une entreprise individuelle, le propriétaire a retiré 6 000 Dhs du compte bancaire de l'entreprise pour payer l'assurance de la voiture de sa femme. Pour enregistrer cette opération, le comptable doit :",
      o: { A: "Débiter le compte « 5141 » et créditer le compte « 11175 »", B: "Débiter le compte « 6134 » et créditer le compte « 5141 »", C: "Débiter le compte « 11175 » et créditer le compte « 5141 »", D: "Débiter le compte « 6134 » et créditer le compte « 11175 »", E: "Aucune réponse" },
      ok: "C", ex: "Dépense personnelle de l'exploitant payée par l'entreprise (question posée en 2017, 2022 et 2023) : c'est un prélèvement, pas une charge. Débit compte de l'exploitant (1117), crédit 5141 Banque. B passerait en charge (6134 primes d'assurance) une dépense privée." },
    { src: A22c(8), conf: "S", q: "Le 20/09, l'entreprise a acquis une machine de production : prix d'achat HT 200 000 Dhs ; frais d'installation 3 500 Dhs ; frais de transport 500 Dhs ; frais d'essai 1 000 Dhs. Quelle sera la valeur d'entrée de cette machine ?",
      o: { A: "200 000 Dhs", B: "203 500 Dhs", C: "204 000 Dhs", D: "205 000 Dhs", E: "214 000" },
      ok: "D", ex: "Coût d'acquisition = prix d'achat + frais accessoires nécessaires pour mettre le bien en état d'utilisation : transport, installation, essais et mise au point. 200 000 + 3 500 + 500 + 1 000 = 205 000. C oublie les essais." },
    { src: A22c(13), conf: "S", q: "L'entreprise a acheté une machine de production : prix d'achat 500 000 Dhs ; transport 2 000 ; installation 5 000 ; essai et mise au point 4 000 ; formation du personnel 15 000 ; TVA 20 %. Le coût d'acquisition est de :",
      o: { A: "526 000 Dhs", B: "631 000 Dhs", C: "507 000 Dhs", D: "607 000 Dhs", E: "517 000 Dhs", F: "Aucune réponse" },
      ok: "F", ex: "500 000 + 2 000 + 5 000 + 4 000 = 511 000 DH. La formation du personnel est une charge (elle ne rend pas le bien utilisable), la TVA est récupérable. 511 000 est absent : « Aucune réponse ». A inclut la formation." },
    { src: A22c(11), conf: "S", q: "Des titres de participation ont été acquis à 245 000 Dhs. Ils avaient fait l'objet d'une provision pour dépréciation de 32 000 Dhs. Leur valeur actuelle s'élève à 250 000 Dhs. Le comptable devra donc :",
      o: { A: "Constater une dotation aux provisions de 5 000 Dhs", B: "Constater une reprise sur provisions de 5 000 Dhs", C: "Annuler la dotation aux provisions de 32 000 Dhs", D: "Constater une reprise aux provisions de 27 000 Dhs", E: "Aucune réponse" },
      ok: "C", ex: "La valeur actuelle (250 000) dépasse le coût d'acquisition (245 000) : plus aucune dépréciation, la provision de 32 000 est reprise en totalité. La plus-value latente de 5 000 n'est pas constatée (prudence). Question posée à l'identique en ACGSI 2017." },
    { src: A22c(9), conf: "P", q: "Au cours de l'exercice 2021, l'entreprise a réalisé : ventes de produits au Maroc 840 000 ; ventes de produits à l'étranger 35 000 ; bonis sur reprise d'emballages consignés 2 000 ; RRR accordés par l'entreprise 46 000 ; subvention d'exploitation reçue 12 000. Quel est le chiffre d'affaires réalisé en 2021 ?",
      o: { A: "888 000 Dhs", B: "935 000 Dhs", C: "875 000 Dhs", D: "831 000 Dhs", E: "923 000 dhs", F: "Aucune réponse" },
      ok: "D", ex: "CA = 840 000 + 35 000 + 2 000 (les bonis sur reprises d'emballages sont classés dans les ventes) − 46 000 (RRR accordés, qui viennent en déduction des ventes) = 831 000. La subvention d'exploitation est un produit d'exploitation, mais pas du chiffre d'affaires." },
    { src: A22c(12), conf: "P", q: "L'entreprise détient des actions BOA acquises en 2021 : 500 actions à 199,80 Dhs et 200 actions à 190 Dhs. Au 31/12/2021, le cours est de 194 Dhs. Le comptable devra constater :",
      o: { A: "Une dotation aux provisions de 2 900 Dhs", B: "Une dotation de 2 900 Dhs et une reprise de 800 Dhs", C: "Une reprise sur provisions de 800 Dhs", D: "Une dotation aux provisions de 2 100 Dhs", E: "Aucune réponse" },
      ok: "D", ex: R`Pour des titres de même nature, on compare le coût global à la valeur d'inventaire globale. Coût : $500 \times 199{,}80 + 200 \times 190 = 137\,900$. Valeur au cours : $700 \times 194 = 135\,800$. Dotation : 2 100. A (2 900) ne regarde que le lot en moins-value ; B compense en « reprise » une plus-value latente, ce que la prudence interdit.` },
    { src: A23c(4), conf: "S", q: "L'acquisition de voitures et camions par un concessionnaire automobile s'enregistre :",
      o: { A: "Au débit du compte « 6111 »", B: "Au débit du compte « 3151 »", C: "Au débit du compte « 6142 »", D: "Au débit du compte « 2340 »" },
      ok: "A", ex: "Pour un concessionnaire, les véhicules sont achetés pour être revendus : ce sont des marchandises (6111 Achats de marchandises), pas du matériel de transport (2340)." },
    { src: A23c(20), conf: "S", q: "La subvention d'exploitation bénéficie à l'entreprise pour :",
      o: { A: "Acquérir ou créer des immobilisations ou financer des activités à long terme", B: "Compenser l'insuffisance de certains produits d'exploitation", C: "Couvrir la perte globale constatée en comptabilité", D: "Encourager l'entreprise à embaucher les jeunes diplômés", E: "Aucune réponse" },
      ok: "B", ex: "Subvention d'exploitation (compte 716) : compenser l'insuffisance de certains produits ou faire face à certaines charges d'exploitation. A définit la subvention d'investissement, C la subvention d'équilibre." },
  ],

  // ───────────────────────── Partie 2 · Comptabilité des sociétés
  2: [
    { src: B(1), conf: "S", q: "Dans la SA, la distribution des dividendes ne peut pas s'effectuer, tant que :",
      o: { A: "il n'existe pas de réserves libres au moins égales au montant des frais restant à amortir", B: "le capital n'est pas entièrement libéré", C: "les frais de constitution ne sont pas totalement amortis", D: "aucune réponse ne convient" },
      ok: "A", ex: "Loi 17-95 : pas de distribution tant que les frais d'établissement ne sont pas amortis, sauf si des réserves libres au moins égales aux frais restant à amortir existent. A reprend cette condition exacte ; C l'oublie. Un capital non entièrement libéré n'empêche pas de distribuer (B)." },
    { src: B(2), conf: "S", q: "Pour l'exercice 2020, les intérêts statutaires d'une société s'élèvent à 250 000 dh et le super dividende à 1 450 000 dh. Le 15/06/2021, la société paie par chèque les dividendes nets. L'écriture correcte est :",
      o: { A: "on débite le compte 4465 Associés, dividendes à payer de 1 350 500 dh", B: "on crédite le compte 4465 Associés, dividendes à payer de 1 445 000 dh", C: "on débite le compte 4465 Associés, dividendes à payer de 1 445 000 dh", D: "aucune réponse ne convient" },
      ok: "C", ex: R`Dividendes bruts $= 250\,000 + 1\,450\,000 = 1\,700\,000$. Retenue à la source de 15 % en 2021 : net $= 1\,700\,000 \times 85\,\% = 1\,445\,000$. Au paiement, on solde la dette : débit 4465, crédit 5141. On crédite 4465 lors de l'affectation (B), pas lors du paiement. Le taux de retenue baisse ensuite jusqu'à 10 % en 2026 : regarde l'année des faits.` },
    { src: B(3), conf: "S", q: "Capitaux propres d'une SA au 31/12/2021, avant répartition : capital 900 000 (4 500 actions) ; réserve légale 45 000 ; réserves facultatives 250 000 ; report à nouveau −80 000 ; résultat net 700 000. Le bénéfice distribuable est égal à :",
      o: { A: "aucune réponse ne convient", B: "620 000 DH", C: "700 000 DH", D: "780 000 DH" },
      ok: "A", ex: R`Le report débiteur s'impute d'abord : $700\,000 - 80\,000 = 620\,000$. Réserve légale : $5\,\% \times 620\,000 = 31\,000$ (plafond 10 % du capital = 90 000, la réserve n'en a que 45 000). Bénéfice distribuable $= 620\,000 - 31\,000 = 589\,000$, absent des options. B oublie la réserve légale.` },
    { src: C(4), conf: "S", q: "Lors d'une augmentation de capital en numéraire, la prime d'émission a pour but de :",
      o: { A: "compenser la différence entre la valeur nominale et la valeur de souscription", B: "être distribuée comme dividende", C: "être enregistrée dans les charges de constitution", D: "réduire le capital social" },
      ok: "A", ex: "Prime d'émission = prix d'émission − valeur nominale. Elle protège les anciens actionnaires de la dilution des réserves et va en capitaux propres (1121), jamais en charges." },
    { src: C(26), conf: "S", q: "La réserve légale devient facultative dès que :",
      o: { A: "les statuts l'autorisent", B: "le capital social dépasse 1 million de dirhams", C: "elle atteint 10 % du capital social", D: "le résultat net est déficitaire" },
      ok: "C", ex: "Loi 17-95 : prélèvement de 5 % du bénéfice (diminué des pertes antérieures) jusqu'à ce que la réserve légale atteigne 10 % du capital. Au-delà, la dotation n'est plus obligatoire." },
    { src: C(37), conf: "S", q: "Une subvention d'investissement est enregistrée :",
      o: { A: "en trésorerie d'exploitation", B: "en diminution du coût de l'actif", C: "en capitaux propres, puis étalée au compte de résultat", D: "en produits exceptionnels" },
      ok: "C", ex: "CGNC : compte 1311 (capitaux propres assimilés), puis reprise au CPC (7577) au rythme des amortissements du bien financé. B est une autre méthode, non retenue au Maroc." },
    { src: A22c(14), conf: "S", q: "La société MASSROUR a été créée avec un capital de 800 000 Dhs divisé en 8 000 actions, dont 3 000 actions d'apport en nature. Seul le minimum légal a été exigé des associés, qui l'ont libéré dans les délais. Le compte 1119 « Actionnaires, capital souscrit non appelé » sera :",
      o: { A: "Débité de 600 000 Dhs", B: "Crédité de 600 000 dhs", C: "Débité de 375 000 Dhs", D: "Crédité de 375 000 dhs", E: "Aucune réponse" },
      ok: "C", ex: R`Nominal $= 800\,000 / 8\,000 = 100$. Apports en nature (3 000 actions) : libérés en totalité. Numéraire : $5\,000 \times 100 = 500\,000$, dont un quart appelé (125 000). Non appelé $= 375\,000$, porté au débit du 1119 (compte soustractif du capital).` },
    { src: A22c(15), conf: "S", q: "Un actionnaire qui détient 500 actions de nominal 120 Dhs ne libère le 3e quart que 35 jours après la date limite. L'entreprise lui applique des intérêts de retard de 12 % et des frais de recouvrement de 375 Dhs. Au moment du paiement, le compte bancaire de l'entreprise sera :",
      o: { A: "Débité de 15 550 Dhs", B: "Crédité de 700 dhs", C: "Débité de 16 075 Dhs", D: "Crédité de 15 550 Dhs", E: "Aucune réponse" },
      ok: "A", ex: R`3e quart $= 500 \times 120 \times 25\,\% = 15\,000$. Intérêts $= 15\,000 \times 12\,\% \times \frac{35}{360} = 175$. Total encaissé $= 15\,000 + 175 + 375 = 15\,550$. La banque de l'entreprise reçoit l'argent : elle est débitée.` },
    { src: A22c(18), conf: "P", q: "Une entreprise au capital de 2 500 000 Dhs libéré à 75 % depuis plus d'un an décide une augmentation de capital par émission de 2 000 actions nouvelles de nominal 200 Dhs. Le cours des anciennes actions est de 160 Dhs. En se référant au droit des sociétés, le montant de cette augmentation de capital devra être :",
      o: { A: "400 000 Dhs", B: "320 000 Dhs", C: "300 000 Dhs", D: "200 000 Dhs", E: "00 Dhs", F: "Aucune réponse" },
      ok: "E", ex: "Loi 17-95 : le capital doit être intégralement libéré avant toute émission d'actions nouvelles à libérer en numéraire, à peine de nullité. Avec un capital libéré à 75 %, l'augmentation en numéraire est impossible : 0. Si l'opération était permise, ce serait 400 000 (A), puisqu'on n'émet jamais en dessous du nominal, quel que soit le cours (160). Le piège est dans « libéré à 75 % »." },
  ],

  // ───────────────────────── Partie 3 · Comptabilité analytique et contrôle de gestion
  3: [
    { src: B(4), conf: "S", q: "Les entrées en stock des produits finis s'évaluent au :",
      o: { A: "coût de production", B: "coût d'achat", C: "coût de revient", D: "coût de distribution" },
      ok: "A", ex: "Produits finis : coût de production. Marchandises et matières : coût d'achat. Le coût de revient (C) inclut la distribution, qui n'a pas encore eu lieu." },
    { src: B(5), conf: "S", q: "Parmi les charges suivantes, celles incorporables aux coûts des produits et/ou des services sont :",
      o: { A: "l'impôt sur les bénéfices", B: "les charges exceptionnelles", C: "les charges sur exercices antérieurs", D: "les charges de personnel" },
      ok: "D", ex: "Non incorporables : IS, charges non courantes, charges sur exercices antérieurs, dotations aux immobilisations en non-valeurs. Les charges de personnel sont incorporables." },
    { src: B(6), conf: "S", q: "Le coût de revient d'un produit :",
      o: { A: "aucune réponse ne convient", B: "est un coût partiel", C: "représente le total des charges supportées par ce produit", D: "concerne la totalité des produits fabriqués" },
      ok: "C", ex: "Coût de revient = coût de production des produits vendus + coûts hors production (distribution, administration). C'est un coût complet (B faux), propre à un produit (D faux)." },
    { src: C(29), conf: "S", q: "Le coût de revient d'un produit correspond à :",
      o: { A: "la totalité des coûts de production de l'ensemble des produits fabriqués.", B: "l'ensemble des charges directes et indirectes supportées par ce produit.", C: "aucune réponse ne convient.", D: "un coût partiel calculé à partir des seules charges variables." },
      ok: "B", ex: "Même notion, autre formulation : toutes les charges directes et indirectes du produit. D définit le coût variable." },
    { src: B(7), conf: "S", q: "La répartition secondaire est :",
      o: { A: "l'attribution des charges indirectes aux différents centres", B: "l'imputation des coûts aux produits", C: "la répartition des prestations des centres auxiliaires dans le coût des centres principaux", D: "aucune réponse ne convient" },
      ok: "C", ex: "Répartition primaire : charges indirectes réparties entre tous les centres (A). Répartition secondaire : on vide les centres auxiliaires dans les centres principaux. Imputation (B) : les centres principaux vers les coûts, par les unités d'œuvre." },
    { src: B(8), conf: "P", q: "L'unité d'œuvre d'une section analytique représente :",
      o: { A: "aucune réponse ne convient", B: "l'unité de mesure de la rentabilité de cette section", C: "le temps de travail nécessaire pour produire une pièce", D: "la clé de répartition de ce centre" },
      ok: "A", ex: "L'unité d'œuvre est l'unité de mesure de l'activité d'un centre principal, qui sert à imputer son coût aux produits. B parle de rentabilité (faux), D confond avec la clé de répartition (centres auxiliaires). C est un exemple d'unité d'œuvre, pas sa définition." },
    { src: C(5), conf: "S", q: "Une charge indirecte est :",
      o: { A: "une charge variable dépendant du niveau de production", B: "une charge non incorporable", C: "une charge qui concerne plusieurs produits et nécessite une clé de répartition", D: "une charge rattachée directement à un produit ou service" },
      ok: "C", ex: "Charge indirecte : commune à plusieurs coûts, elle transite par les centres d'analyse. D définit la charge directe. Directe/indirecte et fixe/variable sont deux classements indépendants (A)." },
    { src: C(20), conf: "S", q: "Le coût d'achat comprend :",
      o: { A: "le prix d'achat hors taxes seulement", B: "le prix d'achat diminué des remises", C: "le prix d'achat plus les frais accessoires", D: "les coûts de production des matières" },
      ok: "C", ex: "Coût d'achat = prix d'achat net (après remises) + frais accessoires d'achat (transport, réception, centre approvisionnement). B oublie les frais accessoires." },
    { src: B(9), conf: "S", q: "Une société a acquis, en avril, une marchandise ayant coûté 4 320 DH TTC (TVA au taux normal). Frais de transport incorporables : 90 DH. Lors de la réception, d'autres charges ont été supportées à 67 DH l'heure ; la réception a duré 30 minutes. Le centre « approvisionnement » a pour unité d'œuvre la « commande réceptionnée », à 210 DH. Le coût d'approvisionnement de cette commande est de :",
      o: { A: "4653,5", B: "4800", C: "2670", D: "aucune réponse ne convient" },
      ok: "D", ex: R`TVA récupérable, donc hors coût : $4\,320 / 1{,}2 = 3\,600$. Coût $= 3\,600 + 90 + 0{,}5 \times 67 + 210 = 3\,933{,}50$ DH, absent des options. A (4 653,50) garde le TTC. Même méthode en ACGSI 2022 et 2023, avec 2 880 TTC (voir la partie 3).` },
    { src: A23c(18), conf: "S", q: "Le 20 mars, une société a acheté un lot de marchandises ayant coûté 2 880 Dhs TTC (TVA au taux normal). Frais de transport incorporables : 60 Dhs. La réception a été assurée par un contrôleur au coût de 45 Dhs par heure et a duré 20 minutes. Le centre « Approvisionnement » a pour unité d'œuvre la « commande réceptionnée », évaluée à 140 Dhs. Le coût d'achat de cette commande sera de :",
      o: { A: "3 125 dhs", B: "Aucune réponse", C: "3 095 dhs", D: "2 615 dhs", E: "2 645 dhs" },
      ok: "D", ex: R`$2\,880/1{,}2 = 2\,400$ ; $+ 60$ ; $+ 45 \times \frac{20}{60} = 15$ ; $+ 140$ : coût d'achat $= 2\,615$ DH. Même méthode que la question AIF (4 320 TTC) des questions qui retombent : le jury recycle ses énoncés. Dans la version 2022, 2 615 n'était pas proposé.` },
    { src: C(3), conf: "S", q: "La marge sur coût variable (MCV) sert à :",
      o: { A: "calculer le coût de revient complet", B: "évaluer la rotation des stocks", C: "couvrir les charges fixes", D: "déterminer la rentabilité financière" },
      ok: "C", ex: "MCV = CA − charges variables. Elle doit couvrir les charges fixes ; le surplus est le résultat. Seuil de rentabilité : MCV = charges fixes." },
    { src: C(8), conf: "S", q: "Pour un produit : CA 1 200 000 DH ; charges variables 720 000 DH ; charges fixes 400 000 DH. Quelle interprétation correcte peut-on tirer de la marge sur coût variable ?",
      o: { A: "La MCV de 480 000 DH couvre les charges fixes et dégage un résultat d'exploitation de 80 000 DH.", B: "La MCV permet uniquement de calculer le coût de revient complet.", C: "La MCV n'a pas de lien avec la rentabilité opérationnelle.", D: "La MCV de 480 000 DH ne couvre pas entièrement les charges fixes, entraînant une perte d'exploitation." },
      ok: "A", ex: R`MCV $= 1\,200\,000 - 720\,000 = 480\,000$ ; résultat $= 480\,000 - 400\,000 = 80\,000$ DH. Taux de MCV 40 %, SR $= 400\,000 / 0{,}4 = 1\,000\,000$ DH.` },
    { src: C(21), conf: "S", q: "Le seuil de rentabilité correspond :",
      o: { A: "à la marge brute", B: "au niveau de chiffre d'affaires à partir duquel l'entreprise couvre au moins ses charges", C: "au chiffre d'affaires maximal", D: "au résultat net positif" },
      ok: "B", ex: "Au seuil de rentabilité, le CA couvre toutes les charges : résultat nul. Au-delà, bénéfice." },
    { src: C(23), conf: "S", q: "Comment se calcule le taux de couverture des charges fixes ?",
      o: { A: "Chiffre d'affaires / Coûts fixes", B: "MCV / Coûts fixes", C: "Résultat net / Chiffre d'affaires", D: "Résultat d'exploitation / MCV" },
      ok: "B", ex: "Taux de couverture = MCV / charges fixes. Supérieur à 1 (100 %) : bénéfice." },
    { src: A22c(16), conf: "V", q: "Un hôtel de 50 chambres : charges fixes 1 000 000 Dhs par mois ; charges variables 100 Dhs par chambre louée ; chambres louées 1 000 Dhs la nuit. Le premier mois, taux d'occupation de 30 % (450 nuitées sur 1 500 possibles). Avec la méthode de l'imputation rationnelle, quel est le résultat de ce premier mois ?",
      o: { A: "Un bénéfice de 105 000 Dhs", B: "Une perte de 595 000 Dhs", C: "Une perte de 555 000 Dhs", D: "Une perte de 150 000 Dhs", E: "Un bénéfice de 150 000 Dhs", F: "Aucune réponse" },
      ok: "A", ex: R`Charges fixes imputées $= 1\,000\,000 \times 30\,\% = 300\,000$. Résultat analytique $= 450\,000 - 45\,000 - 300\,000 = 105\,000$ : c'est le résultat « en imputation rationnelle », débarrassé du coût de la sous-activité. Le coût de chômage (700 000) est isolé à part ; le résultat comptable réel reste $105\,000 - 700\,000 = -595\,000$ (B). Le libellé « avec la méthode de l'imputation rationnelle » vise A, mais un correcteur peut attendre B : en cas de doute, laisse blanc.` },
    { src: C(31), conf: "S", q: "Qu'est-ce qu'un coût standard ?",
      o: { A: "Un coût d'opportunité", B: "Un coût réel constaté", C: "Un coût préétabli servant de référence pour mesurer les écarts", D: "Un coût moyen observé sur plusieurs périodes" },
      ok: "C", ex: "Coût standard (préétabli) : référence calculée à l'avance. Écart = coût réel − coût préétabli." },
    { src: C(38), conf: "V", q: "Main-d'œuvre directe : temps standard 1,5 h/unité ; temps réel 1,6 h/unité ; taux horaire standard 40 DH ; production 1 000 unités. Quel est l'écart sur productivité de la main-d'œuvre ?",
      o: { A: "+6 000 DH", B: "-6 000 DH", C: "+4 000 DH", D: "-4 000 DH" },
      ok: "C", ex: R`Écart sur rendement $= (T_r - T_s) \times \text{taux standard} \times Q_r = (1{,}6 - 1{,}5) \times 40 \times 1\,000 = +4\,000$. Les ouvriers ont travaillé plus longtemps que prévu : écart défavorable, positif dans la convention « réel − prévu ». Si ton cours note les écarts défavorables en négatif, la réponse devient D. Vérifie la convention de ton enseignant.` },
    { src: C(14), conf: "P", q: "Quelles sont les fonctions essentielles du contrôle de gestion ?",
      o: { A: "Planification, suivi des performances, aide à la décision", B: "Planification, coordination, analyse des écarts", C: "Audit financier, contrôle fiscal, reporting légal", D: "Planification, suivi budgétaire, audit interne" },
      ok: "A", ex: "Le contrôle de gestion planifie (budgets), suit les performances (tableaux de bord, écarts) et aide à la décision. C et D le confondent avec l'audit et le contrôle fiscal ; l'analyse des écarts (B) est un outil du suivi, pas une fonction à part entière." },
  ],

  // ───────────────────────── Partie 4 · Analyse financière et investissement
  4: [
    { src: C(2), conf: "S", q: "Une entreprise rentable mais non liquide signifie que :",
      o: { A: "elle a une rotation de stock lente", B: "elle est endettée à long terme", C: "elle ne réalise pas de bénéfice", D: "elle a des profits mais manque de trésorerie" },
      ok: "D", ex: "Rentabilité (bénéfice) et liquidité (trésorerie) sont distinctes : un BFR élevé ou des investissements lourds peuvent assécher la trésorerie d'une entreprise bénéficiaire." },
    { src: C(6), conf: "S", q: "Bilan simplifié. Actif : immobilisations nettes 1 500 000 ; stocks 400 000 ; créances clients 350 000 ; disponibilités 50 000. Passif : capitaux propres 1 000 000 ; dettes financières à long terme 600 000 ; dettes fournisseurs 300 000 ; autres dettes d'exploitation 150 000. Déterminez la trésorerie nette (TN).",
      o: { A: "150.000 DH", B: "40.000 DH", C: "- 100.000 DH", D: "- 200.000 DH" },
      ok: "D", ex: R`$FR = (1\,000\,000 + 600\,000) - 1\,500\,000 = 100\,000$. $BFR = (400\,000 + 350\,000) - (300\,000 + 150\,000) = 300\,000$. $TN = FR - BFR = -200\,000$. Le bilan n'est pas équilibré (actif 2 300 000, passif 2 050 000) : les 250 000 manquants sont une trésorerie-passif, et $50\,000 - 250\,000 = -200\,000$ confirme le résultat.` },
    { src: C(17), conf: "S", q: "Le fonds de roulement net global (FRNG) positif signifie que :",
      o: { A: "l'entreprise finance une partie de son actif circulant avec des ressources stables", B: "l'entreprise a des dettes supérieures à ses actifs à long terme", C: "l'entreprise est en faillite", D: "Les stocks sont supérieurs aux créances" },
      ok: "A", ex: "FR > 0 : les ressources stables couvrent les emplois stables et financent en plus une partie de l'actif circulant (marge de sécurité)." },
    { src: C(24), conf: "S", q: "Un besoin en fonds de roulement (BFR) positif signifie que :",
      o: { A: "le fonds de roulement est négatif", B: "les ressources d'exploitation financent les emplois d'exploitation", C: "les emplois d'exploitation sont supérieurs aux ressources d'exploitation", D: "l'entreprise dispose d'une trésorerie excédentaire" },
      ok: "C", ex: "BFR > 0 : stocks + créances d'exploitation dépassent les dettes d'exploitation. Le cycle d'exploitation consomme des ressources qu'il faut financer." },
    { src: C(28), conf: "S", q: "Une augmentation du délai de paiement clients impacte le BFR de la manière suivante :",
      o: { A: "aucun impact", B: "augmentation du BFR", C: "diminution du BFR", D: "amélioration de la trésorerie" },
      ok: "B", ex: "Clients plus lents = créances plus élevées = BFR plus élevé, donc trésorerie dégradée (D est l'inverse)." },
    { src: C(15), conf: "S", q: "Le ratio d'endettement se calcule par :",
      o: { A: "Dettes financières / Capitaux propres", B: "Chiffre d'affaires / Total du bilan", C: "Résultat net / Capitaux propres", D: "Capitaux propres / Dettes financières" },
      ok: "A", ex: "Ratio d'endettement (gearing) = dettes financières / capitaux propres. D est son inverse, C la rentabilité financière, B la rotation de l'actif." },
    { src: C(7), conf: "S", q: "Une entreprise a une rentabilité économique (RE) de 12 %, un coût de la dette de 6 % et un ratio d'endettement de 1. Calculer la rentabilité financière (RF).",
      o: { A: "12 %", B: "9 %", C: "15 %", D: "18 %" },
      ok: "D", ex: R`$RF = RE + (RE - i) \times \frac{D}{CP} = 12\,\% + (12\,\% - 6\,\%) \times 1 = 18\,\%$ (avant impôt, l'énoncé ne donnant pas de taux d'IS).` },
    { src: C(22), conf: "S", q: "L'effet de levier financier traduit :",
      o: { A: "le rapport entre le chiffre d'affaires et le résultat d'exploitation", B: "le niveau de risque opérationnel", C: "l'impact de l'endettement sur la rentabilité financière", D: "l'efficacité de la gestion de trésorerie" },
      ok: "C", ex: "Levier financier : effet de la dette sur la rentabilité des capitaux propres (voir la formule ci-dessus). B décrit le levier opérationnel." },
    { src: C(19), conf: "S", q: "Le coût moyen pondéré du capital (CMPC) correspond à :",
      o: { A: "la moyenne des coûts des dettes et des capitaux propres pondérée par leur part dans le financement", B: "le taux de rentabilité exigé par les actionnaires", C: "le taux d'intérêt bancaire", D: "le coût des dettes uniquement" },
      ok: "A", ex: R`$CMPC = k_{cp} \frac{CP}{CP + D} + k_d (1 - t) \frac{D}{CP + D}$. B ne retient que le coût des fonds propres, D que celui de la dette.` },
    { src: C(9), conf: "S", q: "La Valeur Actualisée Nette (VAN) d'un projet permet de :",
      o: { A: "connaître uniquement la trésorerie disponible à la fin du projet", B: "déterminer le montant exact des flux futurs générés par le projet", C: "comparer la rentabilité d'un projet en tenant compte du coût du capital et du temps", D: "mesurer le niveau d'endettement nécessaire pour financer le projet" },
      ok: "C", ex: "La VAN actualise les flux au coût du capital : elle intègre la valeur temps de l'argent et la rémunération exigée par les financeurs. VAN > 0 : le projet crée de la valeur." },
    { src: C(30), conf: "S", q: "Le taux d'actualisation utilisé pour évaluer un projet d'investissement doit refléter :",
      o: { A: "la valeur temps de l'argent, le risque spécifique du projet et le coût moyen pondéré du capital", B: "le taux d'intérêt bancaire à court terme uniquement", C: "la croissance historique du chiffre d'affaires de l'entreprise", D: "l'inflation prévue sur la période d'investissement" },
      ok: "A", ex: "On part du CMPC, majoré d'une prime si le projet est plus risqué que l'entreprise. B, C et D ne retiennent qu'un élément, ou un élément sans rapport." },
    { src: C(27), conf: "S", q: "Un projet nécessite un investissement initial de 200 000 DH et génère des flux nets de trésorerie de 60 000 DH par an pendant 5 ans. Le taux d'actualisation est de 10 %. Quelle est la VAN du projet ?",
      o: { A: "30 000 DH", B: "25 000 DH", C: "33 500 DH", D: "27 400 DH" },
      ok: "D", ex: R`$VAN = 60\,000 \times \frac{1 - 1{,}1^{-5}}{0{,}1} - 200\,000 = 60\,000 \times 3{,}7908 - 200\,000 \approx 27\,447$ DH, soit environ 27 400. Retiens le facteur $3{,}7908$ (5 ans à 10 %) : il revient souvent.` },
    { src: C(34), conf: "S", q: "Une entreprise contracte un prêt de 1 000 000 DH sur 5 ans au taux de 10 %, remboursé par amortissement constant. La caractéristique principale de ce mode de remboursement est :",
      o: { A: "le capital remboursé chaque année reste constant, et les intérêts diminuent au fil des échéances.", B: "les paiements sont proportionnels aux profits de l'entreprise.", C: "les paiements totaux (capital + intérêts) sont identiques chaque année.", D: "le capital est remboursé intégralement à la fin, seuls les intérêts étant payés chaque année." },
      ok: "A", ex: "Amortissement constant : 200 000 de capital par an ; intérêts sur le capital restant dû : 100 000, 80 000, 60 000, 40 000, 20 000. C décrit l'annuité constante, D le remboursement in fine." },
  ],

  // ───────────────────────── Partie 5 · Fiscalité
  5: [
    { src: B(20), conf: "P", q: "Le critère de distinction entre une taxe et une redevance est :",
      o: { A: "la contrepartie", B: "l'équivalence", C: "la proportionnalité", D: "la contribution" },
      ok: "B", ex: "La redevance rémunère un service rendu avec une équivalence (au moins approximative) entre son montant et le coût du service. La taxe est perçue à l'occasion d'un service, sans équivalence. Les deux ont une contrepartie : ce n'est donc pas le critère. Même question en ACGSI 2017 et 2022 (voir la partie 5)." },
    { src: A22f(12), conf: "P", q: "Le critère de distinction entre une taxe et une redevance est :",
      o: { A: "L'équivalence", B: "La contrepartie", C: "La contribution", D: "La proportionnalité", E: "Aucune réponse" },
      ok: "A", ex: "Question posée en 2017 (réponse a), en 2022 (A) et en 2025/26 (B) : la bonne réponse reste « l'équivalence ». Ne mémorise jamais une lettre, mémorise la réponse." },
    { src: B(21), conf: "P", q: "La rémunération du dirigeant :",
      o: { A: "est déductible du bénéfice imposable", B: "n'est pas déductible du bénéfice imposable", C: "aucune réponse ne convient", D: "est déductible du bénéfice imposable sous certaines conditions" },
      ok: "D", ex: "Déductible si elle correspond à un travail effectif et n'est pas excessive. D est plus précise que A, et c'est ce que le jury attend en général." },
    { src: B(22), conf: "P", q: "En matière d'impôt sur les sociétés, les pertes sont :",
      o: { A: "reportables sur les exercices suivants sans limite de temps", B: "aucune réponse ne convient", C: "déductibles du résultat de l'exercice", D: "reportables sur les bénéfices des quatre exercices suivants" },
      ok: "D", ex: "Article 12 du CGI : le déficit s'impute sur les bénéfices des quatre exercices suivants. Seule la part du déficit qui correspond aux amortissements est reportable sans limite (A ne vaut que pour cette part)." },
    { src: B(25), conf: "S", q: "Les charges déductibles sont celles qui affectent le résultat de l'exercice :",
      o: { A: "au cours duquel elles ont été engagées quelle que soit la date de paiement", B: "au cours duquel elles ont été effectivement payées", C: "au cours duquel elles ont été payées même si elles ne sont pas encore comptabilisées", D: "aucune réponse ne convient" },
      ok: "A", ex: "Principe des droits constatés : une charge se rattache à l'exercice où elle est engagée, quelle que soit la date de paiement. Question recyclée de l'ACGSI 2023 (voir la partie 5)." },
    { src: A23tf(9), conf: "S", q: "Les charges déductibles sont celles qui affectent le résultat de l'exercice :",
      o: { A: "Au cours duquel elles ont été payées même si elles ne sont pas encore comptabilisées", B: "Au cours duquel elles ont été engagées quelle que soit leur date de comptabilisation", C: "Au cours duquel elles ont été effectivement payées", D: "Au cours duquel elles ont été comptabilisées et payées", E: "Autre réponse" },
      ok: "B", ex: "Même règle : l'exercice d'engagement. La version AIF 2025/26 reprend la question en déplaçant la bonne réponse en A." },
    { src: B(26), conf: "S", q: "Parmi les charges suivantes, lesquelles ne sont pas déductibles en matière d'IS :",
      o: { A: "les montants des achats et prestations revêtant un caractère de libéralité", B: "les dotations non courantes y compris les dotations aux amortissements dégressifs", C: "les dons en argent ou en nature octroyés aux associations reconnues d'utilité publique", D: "aucune réponse ne convient" },
      ok: "A", ex: "Les libéralités ne servent pas l'intérêt de l'entreprise : non déductibles. Les dotations dégressives (B) et les dons aux associations reconnues d'utilité publique (C) sont déductibles." },
    { src: B(24), conf: "S", q: "Sont déductibles sans limitation les dons accordés aux :",
      o: { A: "Œuvres sociales des entreprises publiques", B: "clubs de sport", C: "associations reconnues d'utilité publique", D: "Aucune réponse n'est exacte" },
      ok: "C", ex: "Article 10 du CGI : les dons aux associations reconnues d'utilité publique sont déductibles en totalité. Les dons aux œuvres sociales des entreprises sont plafonnés à 2 ‰ du chiffre d'affaires." },
    { src: C(16), conf: "S", q: "Résultat comptable avant impôt : 1 000 000 DH. Amendes et pénalités : 30 000 ; dotations aux amortissements non déductibles : 20 000 ; produits de participation exonérés : 50 000 ; provision pour litige non déductible : 10 000. Déterminer l'assiette de l'IS.",
      o: { A: "1 080 000 DH", B: "1 010 000 DH", C: "1 000 000 DH", D: "1 060 000 DH" },
      ok: "B", ex: R`Réintégrations : $30\,000 + 20\,000 + 10\,000 = 60\,000$. Déduction : dividendes $50\,000$ (abattement de 100 %). Assiette $= 1\,000\,000 + 60\,000 - 50\,000 = 1\,010\,000$. A ajoute les dividendes au lieu de les retirer, D oublie de les déduire.` },
    { src: C(32), conf: "S", q: "Parmi les produits à déduire du résultat fiscal, on trouve :",
      o: { A: "les écarts de conversion Passif", B: "le chiffre d'affaires à l'export", C: "aucune réponse n'est exacte", D: "les dividendes" },
      ok: "D", ex: "Dividendes reçus : abattement de 100 %, on les déduit. Les écarts de conversion passif (gains latents) sont au contraire réintégrés au résultat fiscal au Maroc. Le CA à l'export reste imposable." },
    { src: A23tf(13), conf: "S", q: "Parmi les produits suivants, lequel n'est pas imposable à l'IS :",
      o: { A: "Le loyer reçu sur un local appartenant à l'entreprise et loué au directeur général", B: "Les dividendes reçus sur les titres de participation et les titres de valeurs de placement", C: "Les subventions d'exploitation reçues de l'État", D: "Les commissions acquises à l'entreprise", E: "Autre réponse" },
      ok: "B", ex: "Même idée que la question AIF précédente : les dividendes bénéficient d'un abattement de 100 %. Loyers, subventions d'exploitation et commissions sont imposables." },
    { src: B(27), conf: "V", q: "Parmi les produits comptabilisés, on trouve des intérêts nets de la TPPRF de 12 000 DH. Ceci nécessite un :",
      o: { A: "aucune réponse n'est exacte.", B: "retraitement fiscal générant une réintégration de 3 000 DH.", C: "retraitement fiscal générant une réintégration de 12 000 DH.", D: "retraitement comptable générant une augmentation du résultat comptable de 3 000 DH." },
      ok: "D", ex: R`TPPRF de 20 % : brut $= 12\,000 / 0{,}8 = 15\,000$, retenue $= 3\,000$. La retenue est un acompte d'IS imputable : le produit doit figurer brut. La correction rigoureuse est comptable (débit État, crédit produits financiers 3 000), d'où D. Beaucoup de cours font la même correction dans le tableau de passage (« réintégrer la TPPRF »), ce qui donne B. Les deux montants sont 3 000 : le doute porte sur la nature du retraitement. Laisse blanc si ton cours ne tranche pas.` },
    { src: B(28), conf: "P", q: "Frais de mission alloués au directeur commercial : 14 000 DH TTC. Pour rectifier :",
      o: { A: "il faut procéder à une réintégration fiscale de 14.000 DH", B: "il faut procéder à une réintégration fiscale de 4.000 DH", C: "aucune réponse n'est exacte.", D: "aucun retraitement ne doit être opéré." },
      ok: "D", ex: "Frais de mission engagés dans l'intérêt de l'entreprise et justifiés : déductibles. Leur TVA n'est pas récupérable, elle reste dans la charge TTC, elle-même déductible. Rien à rectifier (sauf paiement en espèces au-delà des seuils, non mentionné)." },
    { src: C(36), conf: "P", q: "Frais de mission alloués au directeur commercial : 12 000 DH TTC. Pour rectifier :",
      o: { A: "il faut procéder à une réintégration fiscale de 2.000 DH", B: "aucun retraitement ne doit être opéré.", C: "aucune réponse n'est exacte.", D: "il faut procéder à une réintégration fiscale de 12.000 DH" },
      ok: "B", ex: "Même question qu'au questionnaire B, avec 12 000 au lieu de 14 000. A (2 000 = TVA de 12 000 / 6) confond TVA non récupérable et charge non déductible." },
    { src: B(33), conf: "S", q: "Une dotation de 56 000 DH, comptabilisée au 31/12/2023, concerne une voiture de tourisme acquise le 01/04/2023 pour 280 000 DH HT et amortie sur 5 ans.",
      o: { A: "Il faut procéder à une réintégration fiscale de 11.000 DH", B: "Aucune réponse n'est exacte", C: "Aucun retraitement ne doit être opéré.", D: "Il faut effectuer un retraitement comptable générant une augmentation du résultat comptable de 14.000 DH." },
      ok: "A", ex: R`TVA non récupérable sur une voiture de tourisme : coût $= 336\,000$ TTC. Base fiscale plafonnée à 300 000 TTC, 9 mois en 2023 : $300\,000 / 5 \times \frac{9}{12} = 45\,000$. À réintégrer : $56\,000 - 45\,000 = 11\,000$. D raisonne sur une base HT.` },
    { src: C(10), conf: "S", q: "Une dotation de 56 000 DH, comptabilisée au 31/12/2023, concerne une voiture de tourisme acquise le 01/04/2023 pour 280 000 DH HT et amortie sur 5 ans.",
      o: { A: "Aucune réponse n'est exacte", B: "Aucun retraitement ne doit être opéré.", C: "Il faut opérer un retraitement comptable générant une augmentation du résultat comptable de 11.000 DH.", D: "Il faut procéder à une réintégration fiscale de 11.000 DH" },
      ok: "D", ex: "Énoncé identique au questionnaire B, options mélangées : réintégration fiscale de 11 000 (ici en D). C retient le bon montant mais la mauvaise nature : la limite de 300 000 TTC est fiscale, pas comptable." },
    { src: A23tf(12), conf: "S", q: "Une entreprise a acquis une voiture de tourisme le 06 octobre 2019 à 480 000 Dhs TTC, amortissable au taux constant de 20 %. Pour l'exercice 2020, l'amortissement déductible s'élève à :",
      o: { A: "96 000 Dhs", B: "80 000 dhs", C: "60 000 dhs", D: "20 000 dhs", E: "Autre réponse" },
      ok: "C", ex: R`2020 est une année pleine : $300\,000 \times 20\,\% = 60\,000$ (base plafonnée à 300 000 TTC). A est l'amortissement comptable ($480\,000 \times 20\,\%$) ; l'écart de 36 000 est réintégré.` },
    { src: A22f(8), conf: "V", q: "L'entreprise a acquis en crédit-bail un véhicule de transport de personnel en janvier 2022. Redevance mensuelle : 8 000 Dhs. Valeur à neuf : 450 000 Dhs HT. La redevance annuelle déductible à la fin de 2022 est de :",
      o: { A: "8 000 Dhs", B: "60 000 dhs", C: "90 000 dhs", D: "96 000 dhs", E: "12 000 Dhs", F: "Autre" },
      ok: "D", ex: R`Cet énoncé (8 000 par mois, 450 000) est posé en 2017, 2022 et 2023. En 2017, il s'agit d'un « véhicule de tourisme » : la réponse attendue est $300\,000 \times 20\,\% = 60\,000$ (B). En 2022 et 2023, le jury a écrit « transport de personnel » sans changer les chiffres. Or l'article 10 du CGI exclut du plafond de 300 000 TTC les véhicules de transport collectif du personnel : redevance entièrement déductible, $12 \times 8\,000 = 96\,000$ (D). Le jour J, lis le mot clé : « tourisme » → 60 000 ; « transport de personnel » → 96 000.` },
    { src: "ACGSI 2017 · Fiscalité · Q20", conf: "P", q: "SA « PIMPOM » : résultat comptable avant impôt 521 600. CA HT : sucre 7 500 000 ; farine 12 810 000 ; huile 5 250 000 ; beurre 8 121 440 ; autres produits alimentaires 12 000 000. Produits accessoires 250 000. Produits financiers 240 000, dont 20 % de produits de participation, 10 % de gains de change et 10 % d'écart de conversion passif. Dons reçus de l'État 120 000. Production stockée 170 000. Le montant de la cotisation minimale sera de :",
      o: { A: "84 203,60 Dhs", B: "62 930 Dhs", C: "147 133,60 Dhs", D: "173 796 Dhs", E: "Autre" },
      ok: "C", ex: R`Barème du sujet : 0,25 % pour le sucre, la farine, l'huile et le beurre ; 0,5 % pour le reste. Taux réduit : $33\,681\,440 \times 0{,}25\,\% = 84\,203{,}60$. Taux normal : $12\,000\,000 + 250\,000 + 216\,000 + 120\,000 = 12\,586\,000$ (produits financiers sans l'écart de conversion passif, latent ; production stockée exclue), soit $62\,930$. Total : 147 133,60. Ce cas revient en 2022 (avec 500 000 de sucre : le total change, refais-le) et en 2023. A et B ne sont que l'une des deux parts.` },
    { src: C(33), conf: "S", q: "Cadeaux à la clientèle : 400 articles publicitaires portant le sigle de la société, d'une valeur unitaire de 90 DH HT (TVA 20 %) :",
      o: { A: "43.200 DH à réintégrer", B: "Charge déductible", C: "36.000 DH à réintégrer", D: "aucune réponse n'est juste" },
      ok: "A", ex: R`Plafond : 100 DH TTC par unité. $90 \times 1{,}2 = 108$ TTC $> 100$ : non déductible, et la TVA n'est pas récupérable. Charge TTC $= 400 \times 108 = 43\,200$ à réintégrer. C oublie la TVA, B oublie de passer en TTC.` },
    { src: B(23), conf: "P", q: "Parmi les opérations considérées hors champ en matière de TVA, on trouve :",
      o: { A: "les ventes à l'export", B: "les opérations réalisées selon le régime suspensif", C: "les opérations de location de locaux nus", D: "aucune réponse ne convient" },
      ok: "C", ex: "La location de locaux nus n'est pas une activité commerciale : hors champ. L'export (A) est dans le champ, exonéré avec droit à déduction ; le régime suspensif (B) vise aussi des opérations imposables." },
    { src: A22f(15), conf: "S", q: "Le prorata de déduction est applicable lorsqu'une entreprise exerce :",
      o: { A: "Une activité taxable et une activité exonérée avec droit à déduction", B: "Une activité taxable et une activité exonérée sans droit à déduction", C: "Une activité hors champ et une activité exonérée sans droit à déduction", D: "Une activité exonérée sans droit à déduction et une activité exonérée avec droit à déduction" },
      ok: "B", ex: "Le prorata sert quand une partie du CA n'ouvre pas droit à déduction (exonéré sans droit, hors champ). Prorata = (CA taxable + CA exonéré avec droit) / CA total. En A, tout ouvre droit à déduction : pas de prorata." },
    { src: B(31), conf: "P", q: "Achat de mobilier à 162 000 DH TTC. Règlement : 60 % par chèque, le reste à crédit. Prorata de 72 %. La TVA récupérable s'élève à :",
      o: { A: "11.664 DH", B: "10.800 DH", C: "16.200 DH", D: "aucune réponse ne convient" },
      ok: "A", ex: R`TVA $= 162\,000 / 6 = 27\,000$. Le droit à déduction naît du paiement (article 101 du CGI) : seuls les 60 % payés ouvrent droit à déduction, puis on applique le prorata : $27\,000 \times 60\,\% \times 72\,\% = 11\,664$. Le solde sera récupéré au paiement du crédit.` },
    { src: B(29), conf: "S", q: "Vente de marchandises pour 250 000 DH TTC. Le client règle 60 % au comptant et le reste dans 30 jours en acceptant une traite. Selon le régime des encaissements :",
      o: { A: "pas de TVA facturée à déclarer.", B: "la TVA facturée s'élève à 25.000 DH.", C: "la TVA facturée s'élève à 35.000 DH.", D: "aucune réponse n'est exacte." },
      ok: "B", ex: R`Encaissé : $60\,\% \times 250\,000 = 150\,000$ TTC. TVA due $= 150\,000 / 6 = 25\,000$. L'acceptation d'une traite n'est pas un encaissement : le reste sera déclaré à l'échéance.` },
    { src: A23tf(15), conf: "S", q: "Le 12 mars, l'entreprise ABC facture : brut 17 500 Dhs ; remise 2 % ; transport forfaitaire 1 250 ; emballage 720 ; intérêts pour règlement à terme 860. Règlement : avance de 25 % à la commande (15 février), 25 % par chèque à réception de la facture, solde fin avril. La TVA payable au titre de mars (régime des encaissements, taux 20 %) s'élève à :",
      o: { A: "999 dhs", B: "1 998 dhs", C: "3 996 dhs", D: "802,5 dhs", E: "Autre réponse" },
      ok: "A", ex: R`Base HT $= 17\,500 - 350 + 1\,250 + 720 + 860 = 19\,980$ (tout ce qui est facturé entre dans la base, intérêts de paiement à terme compris). TVA totale $= 3\,996$. En mars, seuls les 25 % payés à réception : $3\,996 \times 25\,\% = 999$. L'avance de février a été taxée en février. B additionne à tort février et mars.` },
    { src: B(30), conf: "S", q: "Le taux cible à l'horizon 2026 des sociétés industrielles dont le bénéfice net est inférieur à 100 MDH est :",
      o: { A: "23 %", B: "10 %", C: "26 %", D: "20 %" },
      ok: "D", ex: "Loi de finances 2023 : convergence des taux d'IS sur 2023-2026. En 2026 : 20 % pour un bénéfice net inférieur à 100 MDH, 35 % au-delà, 40 % pour les établissements de crédit et les assurances." },
    { src: B(32), conf: "P", q: "Une entreprise a encaissé une facture de vente de 675 000 DH en espèces. En matière d'IS, elle doit :",
      o: { A: "aucun retraitement ne doit être opéré.", B: "payer une amende de 25 000 DH", C: "aucune réponse n'est exacte", D: "payer une amende de 40 500 DH" },
      ok: "D", ex: R`Le CGI sanctionne d'une amende de 6 % les transactions entre professionnels réglées en espèces au-delà du seuil légal : $675\,000 \times 6\,\% = 40\,500$.` },
    { src: A23f(5), conf: "S", q: "L'entreprise AZ AGRO est soumise à l'IS au taux de 20 %. Résultat comptable avant impôt : 643 900 Dhs. Charges non déductibles : 52 700. Parmi les produits comptabilisés : un lot de produits finis évalué au prix de vente de 140 000 (taux de marge : 20 % du prix de vente) ; une subvention d'exploitation de 210 000 ; des arrhes de 25 000 reçues d'un client qui n'a pas encore pris livraison. L'IS dû est de :",
      o: { A: "75 640 Dhs", B: "128 720 Dhs", C: "65 640 Dhs", D: "666 200 Dhs", E: "Autre réponse" },
      ok: "B", ex: R`Le stock doit être au coût : $140\,000 \times 80\,\% = 112\,000$, soit 28 000 de surévaluation à déduire. Les arrhes ne sont pas encore acquises : déduire 25 000. La subvention d'exploitation est imposable. Résultat fiscal $= 643\,900 + 52\,700 - 28\,000 - 25\,000 = 643\,600$ ; IS $= 20\,\% \times 643\,600 = 128\,720$. Même cas en 2017 (société AZERTY, IS à 30 % : 193 080), 2022 et 2023 : seul le taux change.` },
    { src: B(34), conf: "V", q: "Un marchand revend au détail des marchandises dont 50 % sont importées et le reste acheté localement. Son chiffre d'affaires 2023 s'élève à 800 000 DH, dont 450 000 DH sur le marché local et le reste à l'étranger. Le chiffre d'affaires soumis à la TVA s'élève à :",
      o: { A: "0 DH", B: "aucune réponse ne convient", C: "450.000 DH", D: "800.000 DH" },
      ok: "B", ex: "Lecture retenue par le corrigé du site : un détaillant n'est assujetti de plein droit qu'à partir de 2 000 000 DH de CA (article 89 du CGI), mais les ventes de produits importés par un commerçant importateur sont imposables quel que soit le CA. On obtient 350 000, absent des options. L'énoncé est flou : « le reste à l'étranger » peut aussi désigner des exportations, exonérées. La même question existe en ACGSI 2023 (40 % importés, 1 000 000 de CA). Laisse blanc si tu hésites." },
  ],

  // ───────────────────────── Partie 6 · Audit et contrôle interne
  6: [
    { src: C(25), conf: "P", q: "Quel type de risque est principalement évalué lors de l'élaboration d'une matrice des risques en audit ?",
      o: { A: "Risque stratégique", B: "Risque d'audit (d'émission d'une opinion erronée)", C: "Risque de contrôle interne", D: "Risque opérationnel" },
      ok: "B", ex: "Démarche par les risques (normes ISA 315 et 330) : réduire le risque d'audit, c'est-à-dire le risque d'exprimer une opinion inappropriée. Il combine risque inhérent, risque lié au contrôle interne (C, une composante seulement) et risque de non-détection. Pour une cartographie des risques de l'entité (audit interne), D serait défendable." },
    { src: C(39), conf: "S", q: "Dans un audit, l'indépendance de l'auditeur signifie :",
      o: { A: "il peut effectuer des tâches de gestion opérationnelle", B: "il ne doit pas être influencé par la direction ou les actionnaires", C: "il peut fixer librement le prix de ses honoraires", D: "il peut décider des décisions stratégiques de l'entreprise" },
      ok: "B", ex: "Indépendance : aucune influence de la direction ni des actionnaires. L'auditeur ne prend aucune décision de gestion (A et D), sinon il s'auditerait lui-même." },
    { src: ENT, conf: "E", q: "Au Maroc, le commissaire aux comptes d'une société anonyme est nommé pour :",
      o: { A: "un exercice", B: "trois exercices", C: "six exercices", D: "une durée illimitée" },
      ok: "B", ex: "Loi 17-95 : mandat de trois exercices, renouvelable. Le commissaire aux comptes est un expert-comptable inscrit à l'Ordre (loi 15-89)." },
    { src: ENT, conf: "E", q: "Le risque d'audit se décompose en :",
      o: { A: "risque inhérent, risque lié au contrôle, risque de non-détection", B: "risque de marché, risque de crédit, risque de liquidité", C: "risque fiscal, risque social, risque juridique", D: "risque d'échantillonnage uniquement" },
      ok: "A", ex: R`$RA = RI \times RC \times RND$. L'auditeur ne maîtrise que le risque de non-détection : plus RI et RC sont élevés, plus il étend ses contrôles pour baisser RND.` },
    { src: ENT, conf: "E", q: "Un test de cheminement consiste à :",
      o: { A: "vérifier un contrôle sur un large échantillon d'opérations de l'exercice", B: "suivre quelques opérations de bout en bout pour vérifier que la procédure décrite existe", C: "circulariser les clients", D: "recalculer les amortissements" },
      ok: "B", ex: "Cheminement = compréhension : une ou deux opérations suivies de l'origine à la comptabilisation. A décrit le test de permanence (le contrôle fonctionne-t-il toute l'année ?)." },
    { src: ENT, conf: "E", q: "La circularisation des clients (confirmation directe des soldes) permet surtout de vérifier :",
      o: { A: "l'exhaustivité des dettes fournisseurs", B: "l'existence des créances", C: "l'évaluation des stocks", D: "la séparation des exercices des charges" },
      ok: "B", ex: "Le client confirme qu'il doit la somme : la créance existe. Pour l'exhaustivité des dettes, on circularise les fournisseurs, y compris ceux dont le solde est nul." },
    { src: ENT, conf: "E", q: "L'auditeur légal est tenu à :",
      o: { A: "une obligation de résultat : il garantit l'absence de toute erreur", B: "une obligation de moyens : il délivre une assurance raisonnable", C: "aucune obligation", D: "une obligation de résultat limitée aux fraudes" },
      ok: "B", ex: "Assurance raisonnable, pas absolue : sondages, limites du contrôle interne, jugement. Il répond de ses diligences, pas de l'absence de toute anomalie." },
    { src: ENT, conf: "E", q: "Le seuil de signification (matérialité) correspond :",
      o: { A: "au montant total du bilan", B: "au montant au-delà duquel une anomalie peut influencer le jugement des utilisateurs des comptes", C: "aux honoraires de l'auditeur", D: "au chiffre d'affaires minimum soumis à l'audit légal" },
      ok: "B", ex: "Une anomalie est significative si elle peut modifier les décisions des utilisateurs. Le seuil se fixe souvent en pourcentage du résultat, du CA ou des capitaux propres." },
    { src: ENT, conf: "E", q: "Le principe de séparation des fonctions impose que soient confiées à des personnes différentes :",
      o: { A: "la vente et l'achat", B: "l'autorisation, l'enregistrement et la détention des actifs (conservation)", C: "la comptabilité générale et la comptabilité analytique", D: "la paie et la gestion des congés" },
      ok: "B", ex: "Celui qui autorise une opération ne doit ni l'enregistrer ni détenir l'actif concerné : sinon il peut commettre et dissimuler une fraude seul." },
    { src: ENT, conf: "E", q: "Selon le référentiel COSO, le contrôle interne comprend cinq composantes. Laquelle n'en fait pas partie ?",
      o: { A: "Environnement de contrôle", B: "Évaluation des risques", C: "Activités de contrôle", D: "Certification des comptes" },
      ok: "D", ex: "COSO : environnement de contrôle, évaluation des risques, activités de contrôle, information et communication, pilotage. La certification des comptes est la mission de l'auditeur légal, extérieure au contrôle interne." },
    { src: ENT, conf: "E", q: "Une certification « avec réserve » signifie que l'auditeur :",
      o: { A: "refuse de certifier les comptes", B: "certifie les comptes, sauf pour des anomalies ou limitations significatives mais circonscrites", C: "n'a pas pu réaliser sa mission", D: "certifie sans aucune remarque" },
      ok: "B", ex: "Quatre opinions : sans réserve, avec réserve (problème significatif mais limité), refus de certifier (désaccord majeur) et impossibilité de certifier (limitation majeure). Une observation n'est pas une réserve." },
  ],
};
